-- TRIGGER: MAXIMO.A_JOBTASK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."A_JOBTASK_T" BEFORE INSERT OR UPDATE ON A_JOBTASK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."A_JOBTASK_T" ENABLE
