-- TRIGGER: MAXIMO.A_PM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."A_PM_T" BEFORE INSERT OR UPDATE ON A_PM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."A_PM_T" ENABLE
