-- TRIGGER: MAXIMO.ACCOUNTDEFAULTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACCOUNTDEFAULTS_T" BEFORE INSERT OR UPDATE ON ACCOUNTDEFAULTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "ACCOUNTDEFAULTS_T" ENABLE
ALTER TRIGGER "MAXIMO"."ACCOUNTDEFAULTS_T" ENABLE
