-- TRIGGER: MAXIMO.ACTCI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACTCI_T" BEFORE INSERT OR UPDATE ON ACTCI FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ACTCI_T" ENABLE
