-- TRIGGER: MAXIMO.ACTCIRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACTCIRELATION_T" BEFORE INSERT OR UPDATE ON ACTCIRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ACTCIRELATION_T" ENABLE
