-- TRIGGER: MAXIMO.ACTCISPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACTCISPEC_T" BEFORE INSERT OR UPDATE ON ACTCISPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ACTCISPEC_T" ENABLE
