-- TRIGGER: MAXIMO.ACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACTION_T" BEFORE INSERT OR UPDATE ON ACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ACTION_T" ENABLE
