-- TRIGGER: MAXIMO.ACTIONSCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACTIONSCFG_T" BEFORE INSERT OR UPDATE ON ACTIONSCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ACTIONSCFG_T" ENABLE
