-- TRIGGER: MAXIMO.ACTIONGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ACTIONGROUP_T" BEFORE INSERT OR UPDATE ON ACTIONGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ACTIONGROUP_T" ENABLE
