-- TRIGGER: MAXIMO.ADDRESS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ADDRESS_T" BEFORE INSERT OR UPDATE ON ADDRESS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "ADDRESS_T" ENABLE
ALTER TRIGGER "MAXIMO"."ADDRESS_T" ENABLE
