-- TRIGGER: MAXIMO.AHBLTHRESHOLD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHBLTHRESHOLD_T" BEFORE INSERT OR UPDATE ON AHBLTHRESHOLD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHBLTHRESHOLD_T" ENABLE
