-- TRIGGER: MAXIMO.AHBLTHRESHOLDRANG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHBLTHRESHOLDRANG_T" BEFORE INSERT OR UPDATE ON AHBLTHRESHOLDRANGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHBLTHRESHOLDRANG_T" ENABLE
