-- TRIGGER: MAXIMO.AHCAPAD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHCAPAD_T" BEFORE INSERT OR UPDATE ON AHCAPAD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."AHCAPAD_T" ENABLE
