-- TRIGGER: MAXIMO.AHDRIVERHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHDRIVERHISTORY_T" BEFORE INSERT OR UPDATE ON AHDRIVERHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHDRIVERHISTORY_T" ENABLE
