-- TRIGGER: MAXIMO.AHDRIVERFACTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHDRIVERFACTOR_T" BEFORE INSERT OR UPDATE ON AHDRIVERFACTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHDRIVERFACTOR_T" ENABLE
