-- TRIGGER: MAXIMO.AHFACTORHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHFACTORHISTORY_T" BEFORE INSERT OR UPDATE ON AHFACTORHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHFACTORHISTORY_T" ENABLE
