-- TRIGGER: MAXIMO.AHHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHHISTORY_T" BEFORE INSERT OR UPDATE ON AHHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHHISTORY_T" ENABLE
