-- TRIGGER: MAXIMO.AHMETHODOLOGY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHMETHODOLOGY_T" BEFORE INSERT OR UPDATE ON AHMETHODOLOGY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHMETHODOLOGY_T" ENABLE
