-- TRIGGER: MAXIMO.AHMETHODDRIVER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHMETHODDRIVER_T" BEFORE INSERT OR UPDATE ON AHMETHODDRIVER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AHMETHODDRIVER_T" ENABLE
