-- TRIGGER: MAXIMO.AHQTOSLCREF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHQTOSLCREF_T" BEFORE INSERT OR UPDATE ON AHQTOSLCREF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."AHQTOSLCREF_T" ENABLE
