-- TRIGGER: MAXIMO.AHRRPLAN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHRRPLAN_T" BEFORE INSERT OR UPDATE ON AHRRPLAN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "AHRRPLAN_T" ENABLE
ALTER TRIGGER "MAXIMO"."AHRRPLAN_T" ENABLE
