-- TRIGGER: MAXIMO.AHSCOREMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AHSCOREMAP_T" BEFORE INSERT OR UPDATE ON AHSCOREMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."AHSCOREMAP_T" ENABLE
