-- TRIGGER: MAXIMO.ALLWEATHERPRODUCT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ALLWEATHERPRODUCT_T" BEFORE INSERT OR UPDATE ON ALLWEATHERPRODUCTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ALLWEATHERPRODUCT_T" ENABLE
