-- TRIGGER: MAXIMO.ALNDOMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ALNDOMAIN_T" BEFORE INSERT OR UPDATE ON ALNDOMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ALNDOMAIN_T" ENABLE
