-- TRIGGER: MAXIMO.AMCREWWOLAB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWWOLAB_T" BEFORE INSERT OR UPDATE ON AMCREWWOLAB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWWOLAB_T" ENABLE
