-- TRIGGER: MAXIMO.AMCREWMODAVAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWMODAVAIL_T" BEFORE INSERT OR UPDATE ON AMCREWMODAVAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWMODAVAIL_T" ENABLE
