-- TRIGGER: MAXIMO.AMCREWWORKZONE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWWORKZONE_T" BEFORE INSERT OR UPDATE ON AMCREWWORKZONE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWWORKZONE_T" ENABLE
