-- TRIGGER: MAXIMO.AMCREWSTATHIS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWSTATHIS_T" BEFORE INSERT OR UPDATE ON AMCREWSTATHIS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWSTATHIS_T" ENABLE
