-- TRIGGER: MAXIMO.AMCREWQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWQUAL_T" BEFORE INSERT OR UPDATE ON AMCREWQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWQUAL_T" ENABLE
