-- TRIGGER: MAXIMO.AMCREWLABOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWLABOR_T" BEFORE INSERT OR UPDATE ON AMCREWLABOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWLABOR_T" ENABLE
