-- TRIGGER: MAXIMO.AMCREWT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWT_T" BEFORE INSERT OR UPDATE ON AMCREWT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWT_T" ENABLE
