-- TRIGGER: MAXIMO.AMCREW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREW_T" BEFORE INSERT OR UPDATE ON AMCREW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREW_T" ENABLE
