-- TRIGGER: MAXIMO.AMCREWLABPOS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWLABPOS_T" BEFORE INSERT OR UPDATE ON AMCREWLABPOS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWLABPOS_T" ENABLE
