-- TRIGGER: MAXIMO.AMCREWTOOL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWTOOL_T" BEFORE INSERT OR UPDATE ON AMCREWTOOL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWTOOL_T" ENABLE
