-- TRIGGER: MAXIMO.AMCREWWOTL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWWOTL_T" BEFORE INSERT OR UPDATE ON AMCREWWOTL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWWOTL_T" ENABLE
