-- TRIGGER: MAXIMO.AMCREWTOOLSQ_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCREWTOOLSQ_T" BEFORE INSERT OR UPDATE ON AMCREWTOOLSQ FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCREWTOOLSQ_T" ENABLE
