-- TRIGGER: MAXIMO.AMCTCRAFT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCTCRAFT_T" BEFORE INSERT OR UPDATE ON AMCTCRAFT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCTCRAFT_T" ENABLE
