-- TRIGGER: MAXIMO.AMCTSTATHIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCTSTATHIST_T" BEFORE INSERT OR UPDATE ON AMCTSTATHIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCTSTATHIST_T" ENABLE
