-- TRIGGER: MAXIMO.AMCTQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AMCTQUAL_T" BEFORE INSERT OR UPDATE ON AMCTQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AMCTQUAL_T" ENABLE
