-- TRIGGER: MAXIMO.ANALYTICDATASET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ANALYTICDATASET_T" BEFORE INSERT OR UPDATE ON ANALYTICDATASET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."ANALYTICDATASET_T" ENABLE
