-- TRIGGER: MAXIMO.ANYWHERERESOURCEV_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ANYWHERERESOURCEV_T" BEFORE INSERT OR UPDATE ON ANYWHERERESOURCEVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ANYWHERERESOURCEV_T" ENABLE
