-- TRIGGER: MAXIMO.ANYWHEREPROPVALUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ANYWHEREPROPVALUE_T" BEFORE INSERT OR UPDATE ON ANYWHEREPROPVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ANYWHEREPROPVALUE_T" ENABLE
