-- TRIGGER: MAXIMO.ANYWHEREAPP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ANYWHEREAPP_T" BEFORE INSERT OR UPDATE ON ANYWHEREAPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ANYWHEREAPP_T" ENABLE
