-- TRIGGER: MAXIMO.ANYWHEREPROPERTY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ANYWHEREPROPERTY_T" BEFORE INSERT OR UPDATE ON ANYWHEREPROPERTY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ANYWHEREPROPERTY_T" ENABLE
