-- TRIGGER: MAXIMO.APICSRFTOKEN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APICSRFTOKEN_T" BEFORE INSERT OR UPDATE ON APICSRFTOKEN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APICSRFTOKEN_T" ENABLE
