-- TRIGGER: MAXIMO.APILINKEDOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APILINKEDOBJECT_T" BEFORE INSERT OR UPDATE ON APILINKEDOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APILINKEDOBJECT_T" ENABLE
