-- TRIGGER: MAXIMO.APIROUTE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APIROUTE_T" BEFORE INSERT OR UPDATE ON APIROUTE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APIROUTE_T" ENABLE
