-- TRIGGER: MAXIMO.APIROUTEPROP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APIROUTEPROP_T" BEFORE INSERT OR UPDATE ON APIROUTEPROP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APIROUTEPROP_T" ENABLE
