-- TRIGGER: MAXIMO.APMVALUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APMVALUE_T" BEFORE INSERT OR UPDATE ON APMVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APMVALUE_T" ENABLE
