-- TRIGGER: MAXIMO.APPDOCTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPDOCTYPE_T" BEFORE INSERT OR UPDATE ON APPDOCTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."APPDOCTYPE_T" ENABLE
