-- TRIGGER: MAXIMO.APPFIELDDEFAULTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPFIELDDEFAULTS_T" BEFORE INSERT OR UPDATE ON APPFIELDDEFAULTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."APPFIELDDEFAULTS_T" ENABLE
