-- TRIGGER: MAXIMO.APPLICATIONAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPLICATIONAUTH_T" BEFORE INSERT OR UPDATE ON APPLICATIONAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."APPLICATIONAUTH_T" ENABLE
