-- TRIGGER: MAXIMO.APPPROPCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPPROPCFG_T" BEFORE INSERT OR UPDATE ON APPPROPCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPPROPCFG_T" ENABLE
