-- TRIGGER: MAXIMO.APPTBKWINDOWS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBKWINDOWS_T" BEFORE INSERT OR UPDATE ON APPTBKWINDOWS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBKWINDOWS_T" ENABLE
