-- TRIGGER: MAXIMO.APPTBOOKJOBPLAN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBOOKJOBPLAN_T" BEFORE INSERT OR UPDATE ON APPTBOOKJOBPLAN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBOOKJOBPLAN_T" ENABLE
