-- TRIGGER: MAXIMO.APPTBKSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBKSTATUS_T" BEFORE INSERT OR UPDATE ON APPTBKSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBKSTATUS_T" ENABLE
