-- TRIGGER: MAXIMO.APPTRACKER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTRACKER_T" BEFORE INSERT OR UPDATE ON APPTRACKER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTRACKER_T" ENABLE
