-- TRIGGER: MAXIMO.APPTBOOK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBOOK_T" BEFORE INSERT OR UPDATE ON APPTBOOK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBOOK_T" ENABLE
