-- TRIGGER: MAXIMO.APPTBKWINDOWAVAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBKWINDOWAVAIL_T" BEFORE INSERT OR UPDATE ON APPTBKWINDOWAVAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBKWINDOWAVAIL_T" ENABLE
