-- TRIGGER: MAXIMO.APPTBOOKASSIGNMEN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBOOKASSIGNMEN_T" BEFORE INSERT OR UPDATE ON APPTBOOKASSIGNMENTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBOOKASSIGNMEN_T" ENABLE
