-- TRIGGER: MAXIMO.APPTBKCOMMITGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPTBKCOMMITGROUP_T" BEFORE INSERT OR UPDATE ON APPTBKCOMMITGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPTBKCOMMITGROUP_T" ENABLE
