-- TRIGGER: MAXIMO.APPUSERPROPCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."APPUSERPROPCFG_T" BEFORE INSERT OR UPDATE ON APPUSERPROPCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."APPUSERPROPCFG_T" ENABLE
