-- TRIGGER: MAXIMO.ARCHIVE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ARCHIVE_T" BEFORE INSERT OR UPDATE ON ARCHIVE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ARCHIVE_T" ENABLE
