-- TRIGGER: MAXIMO.AREASAFFECTED_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AREASAFFECTED_T" BEFORE INSERT OR UPDATE ON AREASAFFECTED FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AREASAFFECTED_T" ENABLE
