-- TRIGGER: MAXIMO.ASSETTOPOCACHE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETTOPOCACHE_T" BEFORE INSERT OR UPDATE ON ASSETTOPOCACHE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETTOPOCACHE_T" ENABLE
