-- TRIGGER: MAXIMO.ASSETROLLUPSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETROLLUPSTATUS_T" BEFORE INSERT OR UPDATE ON ASSETROLLUPSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."ASSETROLLUPSTATUS_T" ENABLE
