-- TRIGGER: MAXIMO.ASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSET_T" BEFORE INSERT OR UPDATE ON ASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSET_T" ENABLE
