-- TRIGGER: MAXIMO.ASSETGEOHASH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETGEOHASH_T" BEFORE INSERT OR UPDATE ON ASSETGEOHASH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."ASSETGEOHASH_T" ENABLE
