-- TRIGGER: MAXIMO.ASSETLOCCOMM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETLOCCOMM_T" BEFORE INSERT OR UPDATE ON ASSETLOCCOMM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETLOCCOMM_T" ENABLE
