-- TRIGGER: MAXIMO.ASSETLOCUSERCUST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETLOCUSERCUST_T" BEFORE INSERT OR UPDATE ON ASSETLOCUSERCUST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "ASSETLOCUSERCUST_T" ENABLE
ALTER TRIGGER "MAXIMO"."ASSETLOCUSERCUST_T" ENABLE
