-- TRIGGER: MAXIMO.ASSETOPSKD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETOPSKD_T" BEFORE INSERT OR UPDATE ON ASSETOPSKD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETOPSKD_T" ENABLE
