-- TRIGGER: MAXIMO.ASSETTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETTYPE_T" BEFORE INSERT OR UPDATE ON ASSETTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."ASSETTYPE_T" ENABLE
