-- TRIGGER: MAXIMO.ASSETMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETMETER_T" BEFORE INSERT OR UPDATE ON ASSETMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETMETER_T" ENABLE
