-- TRIGGER: MAXIMO.ASSETHIERARCHY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETHIERARCHY_T" BEFORE INSERT OR UPDATE ON ASSETHIERARCHY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETHIERARCHY_T" ENABLE
