-- TRIGGER: MAXIMO.ASSETTRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETTRANS_T" BEFORE INSERT OR UPDATE ON ASSETTRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETTRANS_T" ENABLE
