-- TRIGGER: MAXIMO.ASSETFEATURESPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETFEATURESPEC_T" BEFORE INSERT OR UPDATE ON ASSETFEATURESPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETFEATURESPEC_T" ENABLE
