-- TRIGGER: MAXIMO.ASSETWORKZONE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETWORKZONE_T" BEFORE INSERT OR UPDATE ON ASSETWORKZONE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETWORKZONE_T" ENABLE
