-- TRIGGER: MAXIMO.ASSETFEATURE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETFEATURE_T" BEFORE INSERT OR UPDATE ON ASSETFEATURE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETFEATURE_T" ENABLE
