-- TRIGGER: MAXIMO.ASSETFEASPECHIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETFEASPECHIST_T" BEFORE INSERT OR UPDATE ON ASSETFEASPECHIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETFEASPECHIST_T" ENABLE
