-- TRIGGER: MAXIMO.ASSETSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETSTATUS_T" BEFORE INSERT OR UPDATE ON ASSETSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETSTATUS_T" ENABLE
