-- TRIGGER: MAXIMO.ASSETSPECHIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETSPECHIST_T" BEFORE INSERT OR UPDATE ON ASSETSPECHIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETSPECHIST_T" ENABLE
