-- TRIGGER: MAXIMO.ASSETANCESTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETANCESTOR_T" BEFORE INSERT OR UPDATE ON ASSETANCESTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETANCESTOR_T" ENABLE
