-- TRIGGER: MAXIMO.ASSETHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETHISTORY_T" BEFORE INSERT OR UPDATE ON ASSETHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETHISTORY_T" ENABLE
