-- TRIGGER: MAXIMO.ASSETMNTSKD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETMNTSKD_T" BEFORE INSERT OR UPDATE ON ASSETMNTSKD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETMNTSKD_T" ENABLE
