-- TRIGGER: MAXIMO.ASSETATTRIBUTE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETATTRIBUTE_T" BEFORE INSERT OR UPDATE ON ASSETATTRIBUTE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETATTRIBUTE_T" ENABLE
