-- TRIGGER: MAXIMO.ASSETFEATUREHIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETFEATUREHIST_T" BEFORE INSERT OR UPDATE ON ASSETFEATUREHIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETFEATUREHIST_T" ENABLE
