-- TRIGGER: MAXIMO.ASSETLOCRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETLOCRELATION_T" BEFORE INSERT OR UPDATE ON ASSETLOCRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETLOCRELATION_T" ENABLE
