-- TRIGGER: MAXIMO.ASSETAUDIT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETAUDIT_T" BEFORE INSERT OR UPDATE ON ASSETAUDIT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETAUDIT_T" ENABLE
