-- TRIGGER: MAXIMO.ASSETSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASSETSPEC_T" BEFORE INSERT OR UPDATE ON ASSETSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASSETSPEC_T" ENABLE
