-- TRIGGER: MAXIMO.ASTSPECMSOVER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASTSPECMSOVER_T" BEFORE INSERT OR UPDATE ON ASTSPECMSOVER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ASTSPECMSOVER_T" ENABLE
