-- TRIGGER: MAXIMO.ASYNCJOBOBJSNAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ASYNCJOBOBJSNAP_T" BEFORE INSERT OR UPDATE ON ASYNCJOBOBJSNAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."ASYNCJOBOBJSNAP_T" ENABLE
