-- TRIGGER: MAXIMO.ATTENDANCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ATTENDANCE_T" BEFORE INSERT OR UPDATE ON ATTENDANCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ATTENDANCE_T" ENABLE
