-- TRIGGER: MAXIMO.ATTRFORMULACOND_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ATTRFORMULACOND_T" BEFORE INSERT OR UPDATE ON ATTRFORMULACOND FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."ATTRFORMULACOND_T" ENABLE
