-- TRIGGER: MAXIMO.ATTRFORMULA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ATTRFORMULA_T" BEFORE INSERT OR UPDATE ON ATTRFORMULA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ATTRFORMULA_T" ENABLE
