-- TRIGGER: MAXIMO.AUTHROLEUSER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AUTHROLEUSER_T" BEFORE INSERT OR UPDATE ON AUTHROLEUSER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."AUTHROLEUSER_T" ENABLE
