-- TRIGGER: MAXIMO.AUTHROLE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AUTHROLE_T" BEFORE INSERT OR UPDATE ON AUTHROLE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."AUTHROLE_T" ENABLE
