-- TRIGGER: MAXIMO.AUTOKEY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AUTOKEY_T" BEFORE INSERT OR UPDATE ON AUTOKEY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AUTOKEY_T" ENABLE
