-- TRIGGER: MAXIMO.AUTOATTRUPDATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AUTOATTRUPDATE_T" BEFORE INSERT OR UPDATE ON AUTOATTRUPDATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AUTOATTRUPDATE_T" ENABLE
