-- TRIGGER: MAXIMO.AUTOSCRIPT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AUTOSCRIPT_T" BEFORE INSERT OR UPDATE ON AUTOSCRIPT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AUTOSCRIPT_T" ENABLE
