-- TRIGGER: MAXIMO.AUTOSCRIPTVARS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."AUTOSCRIPTVARS_T" BEFORE INSERT OR UPDATE ON AUTOSCRIPTVARS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."AUTOSCRIPTVARS_T" ENABLE
