-- TRIGGER: MAXIMO.BBOARDAUDIENCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BBOARDAUDIENCE_T" BEFORE INSERT OR UPDATE ON BBOARDAUDIENCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."BBOARDAUDIENCE_T" ENABLE
