-- TRIGGER: MAXIMO.BBOARDMSGSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BBOARDMSGSTATUS_T" BEFORE INSERT OR UPDATE ON BBOARDMSGSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."BBOARDMSGSTATUS_T" ENABLE
