-- TRIGGER: MAXIMO.BBSTATUSHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BBSTATUSHISTORY_T" BEFORE INSERT OR UPDATE ON BBSTATUSHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."BBSTATUSHISTORY_T" ENABLE
