-- TRIGGER: MAXIMO.BILLTOSHIPTO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BILLTOSHIPTO_T" BEFORE INSERT OR UPDATE ON BILLTOSHIPTO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."BILLTOSHIPTO_T" ENABLE
