-- TRIGGER: MAXIMO.BIMATTRIBUTEMAPEN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMATTRIBUTEMAPEN_T" BEFORE INSERT OR UPDATE ON BIMATTRIBUTEMAPENTRY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMATTRIBUTEMAPEN_T" ENABLE
