-- TRIGGER: MAXIMO.BIMATTRIBUTEMAPLI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMATTRIBUTEMAPLI_T" BEFORE INSERT OR UPDATE ON BIMATTRIBUTEMAPLIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMATTRIBUTEMAPLI_T" ENABLE
