-- TRIGGER: MAXIMO.BIMCOMMISSION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMCOMMISSION_T" BEFORE INSERT OR UPDATE ON BIMCOMMISSION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMCOMMISSION_T" ENABLE
