-- TRIGGER: MAXIMO.BIMCOMMENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMCOMMENT_T" BEFORE INSERT OR UPDATE ON BIMCOMMENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMCOMMENT_T" ENABLE
