-- TRIGGER: MAXIMO.BIMCONFIGURATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMCONFIGURATION_T" BEFORE INSERT OR UPDATE ON BIMCONFIGURATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMCONFIGURATION_T" ENABLE
