-- TRIGGER: MAXIMO.BIMDESIGNSPECPROD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMDESIGNSPECPROD_T" BEFORE INSERT OR UPDATE ON BIMDESIGNSPECPROD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMDESIGNSPECPROD_T" ENABLE
