-- TRIGGER: MAXIMO.BIMFILTERLIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMFILTERLIST_T" BEFORE INSERT OR UPDATE ON BIMFILTERLIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMFILTERLIST_T" ENABLE
