-- TRIGGER: MAXIMO.BIMFILTERENTRY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMFILTERENTRY_T" BEFORE INSERT OR UPDATE ON BIMFILTERENTRY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMFILTERENTRY_T" ENABLE
