-- TRIGGER: MAXIMO.BIMFILTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMFILTER_T" BEFORE INSERT OR UPDATE ON BIMFILTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMFILTER_T" ENABLE
