-- TRIGGER: MAXIMO.BIMLMVWORKVIEW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVWORKVIEW_T" BEFORE INSERT OR UPDATE ON BIMLMVWORKVIEW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVWORKVIEW_T" ENABLE
