-- TRIGGER: MAXIMO.BIMLMVMODELLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVMODELLINK_T" BEFORE INSERT OR UPDATE ON BIMLMVMODELLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVMODELLINK_T" ENABLE
