-- TRIGGER: MAXIMO.BIMLMVVIEWABLE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVVIEWABLE_T" BEFORE INSERT OR UPDATE ON BIMLMVVIEWABLE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVVIEWABLE_T" ENABLE
