-- TRIGGER: MAXIMO.BIMLMVBUCKET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVBUCKET_T" BEFORE INSERT OR UPDATE ON BIMLMVBUCKET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVBUCKET_T" ENABLE
