-- TRIGGER: MAXIMO.BIMLMVSAVEDVIEW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVSAVEDVIEW_T" BEFORE INSERT OR UPDATE ON BIMLMVSAVEDVIEW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVSAVEDVIEW_T" ENABLE
