-- TRIGGER: MAXIMO.BIMLMVMODELUPLOAD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVMODELUPLOAD_T" BEFORE INSERT OR UPDATE ON BIMLMVMODELUPLOAD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVMODELUPLOAD_T" ENABLE
