-- TRIGGER: MAXIMO.BIMLMVMODEL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMLMVMODEL_T" BEFORE INSERT OR UPDATE ON BIMLMVMODEL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMLMVMODEL_T" ENABLE
