-- TRIGGER: MAXIMO.BIMOMNICLASSIMPOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMOMNICLASSIMPOR_T" BEFORE INSERT OR UPDATE ON BIMOMNICLASSIMPORT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMOMNICLASSIMPOR_T" ENABLE
