-- TRIGGER: MAXIMO.BIMPRODUCTBASE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMPRODUCTBASE_T" BEFORE INSERT OR UPDATE ON BIMPRODUCTBASE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMPRODUCTBASE_T" ENABLE
