-- TRIGGER: MAXIMO.BIMPRODUCTJOB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMPRODUCTJOB_T" BEFORE INSERT OR UPDATE ON BIMPRODUCTJOB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMPRODUCTJOB_T" ENABLE
