-- TRIGGER: MAXIMO.BIMPRODUCTPARTSUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMPRODUCTPARTSUP_T" BEFORE INSERT OR UPDATE ON BIMPRODUCTPARTSUPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMPRODUCTPARTSUP_T" ENABLE
