-- TRIGGER: MAXIMO.BIMPROJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMPROJECT_T" BEFORE INSERT OR UPDATE ON BIMPROJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMPROJECT_T" ENABLE
