-- TRIGGER: MAXIMO.BIMPRODUCTPART_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMPRODUCTPART_T" BEFORE INSERT OR UPDATE ON BIMPRODUCTPART FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMPRODUCTPART_T" ENABLE
