-- TRIGGER: MAXIMO.BIMPRODUCTBASESPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMPRODUCTBASESPE_T" BEFORE INSERT OR UPDATE ON BIMPRODUCTBASESPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMPRODUCTBASESPE_T" ENABLE
