-- TRIGGER: MAXIMO.BIMSESSION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMSESSION_T" BEFORE INSERT OR UPDATE ON BIMSESSION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMSESSION_T" ENABLE
