-- TRIGGER: MAXIMO.BIMSYSTEMMAPENTRY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMSYSTEMMAPENTRY_T" BEFORE INSERT OR UPDATE ON BIMSYSTEMMAPENTRY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMSYSTEMMAPENTRY_T" ENABLE
