-- TRIGGER: MAXIMO.BIMTYPEMAPLIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMTYPEMAPLIST_T" BEFORE INSERT OR UPDATE ON BIMTYPEMAPLIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMTYPEMAPLIST_T" ENABLE
