-- TRIGGER: MAXIMO.BIMTYPEMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMTYPEMAP_T" BEFORE INSERT OR UPDATE ON BIMTYPEMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMTYPEMAP_T" ENABLE
