-- TRIGGER: MAXIMO.BIMUPLOAD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BIMUPLOAD_T" BEFORE INSERT OR UPDATE ON BIMUPLOAD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BIMUPLOAD_T" ENABLE
