-- TRIGGER: MAXIMO.BOOKMARK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BOOKMARK_T" BEFORE INSERT OR UPDATE ON BOOKMARK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."BOOKMARK_T" ENABLE
