-- TRIGGER: MAXIMO.BUDGETRULETRANSDA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETRULETRANSDA_T" BEFORE INSERT OR UPDATE ON BUDGETRULETRANSDATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETRULETRANSDA_T" ENABLE
