-- TRIGGER: MAXIMO.BUDGETRULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETRULE_T" BEFORE INSERT OR UPDATE ON BUDGETRULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETRULE_T" ENABLE
