-- TRIGGER: MAXIMO.BUDGETRULEPROCTRA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETRULEPROCTRA_T" BEFORE INSERT OR UPDATE ON BUDGETRULEPROCTRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETRULEPROCTRA_T" ENABLE
