-- TRIGGER: MAXIMO.BUDGETRULEPROC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETRULEPROC_T" BEFORE INSERT OR UPDATE ON BUDGETRULEPROC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETRULEPROC_T" ENABLE
