-- TRIGGER: MAXIMO.BUDGETANALYSISAX2_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETANALYSISAX2_T" BEFORE INSERT OR UPDATE ON BUDGETANALYSISAXISNUMBER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETANALYSISAX2_T" ENABLE
