-- TRIGGER: MAXIMO.BUDGETLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETLINE_T" BEFORE INSERT OR UPDATE ON BUDGETLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETLINE_T" ENABLE
