-- TRIGGER: MAXIMO.BUDGETFLAG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETFLAG_T" BEFORE INSERT OR UPDATE ON BUDGETFLAG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETFLAG_T" ENABLE
