-- TRIGGER: MAXIMO.BUDGETANALYSISAXI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETANALYSISAXI_T" BEFORE INSERT OR UPDATE ON BUDGETANALYSISAXIS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETANALYSISAXI_T" ENABLE
