-- TRIGGER: MAXIMO.BUDGETSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETSTATUS_T" BEFORE INSERT OR UPDATE ON BUDGETSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETSTATUS_T" ENABLE
