-- TRIGGER: MAXIMO.BUDGETRULEASSOC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUDGETRULEASSOC_T" BEFORE INSERT OR UPDATE ON BUDGETRULEASSOC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUDGETRULEASSOC_T" ENABLE
