-- TRIGGER: MAXIMO.BUILDINGMODEL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BUILDINGMODEL_T" BEFORE INSERT OR UPDATE ON BUILDINGMODEL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."BUILDINGMODEL_T" ENABLE
