-- TRIGGER: MAXIMO.BULLETINBOARD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."BULLETINBOARD_T" BEFORE INSERT OR UPDATE ON BULLETINBOARD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."BULLETINBOARD_T" ENABLE
