-- TRIGGER: MAXIMO.CALENDARBREAK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CALENDARBREAK_T" BEFORE INSERT OR UPDATE ON CALENDARBREAK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CALENDARBREAK_T" ENABLE
