-- TRIGGER: MAXIMO.CALENDAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CALENDAR_T" BEFORE INSERT OR UPDATE ON CALENDAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CALENDAR_T" ENABLE
