-- TRIGGER: MAXIMO.CARDAPMVALUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CARDAPMVALUE_T" BEFORE INSERT OR UPDATE ON CARDAPMVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."CARDAPMVALUE_T" ENABLE
