-- TRIGGER: MAXIMO.CDMCITYPES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CDMCITYPES_T" BEFORE INSERT OR UPDATE ON CDMCITYPES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CDMCITYPES_T" ENABLE
