-- TRIGGER: MAXIMO.CHARTOFACCOUNTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CHARTOFACCOUNTS_T" BEFORE INSERT OR UPDATE ON CHARTOFACCOUNTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CHARTOFACCOUNTS_T" ENABLE
