-- TRIGGER: MAXIMO.CI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CI_T" BEFORE INSERT OR UPDATE ON CI FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CI_T" ENABLE
