-- TRIGGER: MAXIMO.CIRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CIRELATION_T" BEFORE INSERT OR UPDATE ON CIRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CIRELATION_T" ENABLE
