-- TRIGGER: MAXIMO.CIRELATIONHIS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CIRELATIONHIS_T" BEFORE INSERT OR UPDATE ON CIRELATIONHIS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CIRELATIONHIS_T" ENABLE
