-- TRIGGER: MAXIMO.CISPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CISPEC_T" BEFORE INSERT OR UPDATE ON CISPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CISPEC_T" ENABLE
