-- TRIGGER: MAXIMO.CISTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CISTATUS_T" BEFORE INSERT OR UPDATE ON CISTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CISTATUS_T" ENABLE
