-- TRIGGER: MAXIMO.CITEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CITEMPLATE_T" BEFORE INSERT OR UPDATE ON CITEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CITEMPLATE_T" ENABLE
