-- TRIGGER: MAXIMO.CITYPESTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CITYPESTATUS_T" BEFORE INSERT OR UPDATE ON CITYPESTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CITYPESTATUS_T" ENABLE
