-- TRIGGER: MAXIMO.CLASSSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CLASSSPEC_T" BEFORE INSERT OR UPDATE ON CLASSSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CLASSSPEC_T" ENABLE
