-- TRIGGER: MAXIMO.CLASSIFICATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CLASSIFICATION_T" BEFORE INSERT OR UPDATE ON CLASSIFICATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CLASSIFICATION_T" ENABLE
