-- TRIGGER: MAXIMO.CLASSSTRUCTURE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CLASSSTRUCTURE_T" BEFORE INSERT OR UPDATE ON CLASSSTRUCTURE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CLASSSTRUCTURE_T" ENABLE
