-- TRIGGER: MAXIMO.CLASSSPECUSEWITH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CLASSSPECUSEWITH_T" BEFORE INSERT OR UPDATE ON CLASSSPECUSEWITH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CLASSSPECUSEWITH_T" ENABLE
