-- TRIGGER: MAXIMO.CLASSANCESTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CLASSANCESTOR_T" BEFORE INSERT OR UPDATE ON CLASSANCESTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CLASSANCESTOR_T" ENABLE
