-- TRIGGER: MAXIMO.CLASSUSEWITH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CLASSUSEWITH_T" BEFORE INSERT OR UPDATE ON CLASSUSEWITH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CLASSUSEWITH_T" ENABLE
