-- TRIGGER: MAXIMO.COLLECTDETAILS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COLLECTDETAILS_T" BEFORE INSERT OR UPDATE ON COLLECTDETAILS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COLLECTDETAILS_T" ENABLE
