-- TRIGGER: MAXIMO.COLLECTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COLLECTION_T" BEFORE INSERT OR UPDATE ON COLLECTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COLLECTION_T" ENABLE
