-- TRIGGER: MAXIMO.COLLECTIONAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COLLECTIONAUTH_T" BEFORE INSERT OR UPDATE ON COLLECTIONAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COLLECTIONAUTH_T" ENABLE
