-- TRIGGER: MAXIMO.COMMODITIES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMODITIES_T" BEFORE INSERT OR UPDATE ON COMMODITIES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMODITIES_T" ENABLE
