-- TRIGGER: MAXIMO.COMMTMPLTSENDTO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMTMPLTSENDTO_T" BEFORE INSERT OR UPDATE ON COMMTMPLTSENDTO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMTMPLTSENDTO_T" ENABLE
