-- TRIGGER: MAXIMO.COMMTEMPLATEDOCS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMTEMPLATEDOCS_T" BEFORE INSERT OR UPDATE ON COMMTEMPLATEDOCS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMTEMPLATEDOCS_T" ENABLE
