-- TRIGGER: MAXIMO.COMMITGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMITGROUP_T" BEFORE INSERT OR UPDATE ON COMMITGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMITGROUP_T" ENABLE
