-- TRIGGER: MAXIMO.COMMTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMTEMPLATE_T" BEFORE INSERT OR UPDATE ON COMMTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMTEMPLATE_T" ENABLE
