-- TRIGGER: MAXIMO.COMMITPERSON_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMITPERSON_T" BEFORE INSERT OR UPDATE ON COMMITPERSON FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMITPERSON_T" ENABLE
