-- TRIGGER: MAXIMO.COMMLOGDOCS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMLOGDOCS_T" BEFORE INSERT OR UPDATE ON COMMLOGDOCS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMLOGDOCS_T" ENABLE
