-- TRIGGER: MAXIMO.COMMLOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMMLOG_T" BEFORE INSERT OR UPDATE ON COMMLOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMMLOG_T" ENABLE
