-- TRIGGER: MAXIMO.COMPMASTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMPMASTER_T" BEFORE INSERT OR UPDATE ON COMPMASTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMPMASTER_T" ENABLE
