-- TRIGGER: MAXIMO.COMPCONTACTMSTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMPCONTACTMSTR_T" BEFORE INSERT OR UPDATE ON COMPCONTACTMSTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMPCONTACTMSTR_T" ENABLE
