-- TRIGGER: MAXIMO.COMPANIES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMPANIES_T" BEFORE INSERT OR UPDATE ON COMPANIES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMPANIES_T" ENABLE
