-- TRIGGER: MAXIMO.COMPCONTACT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COMPCONTACT_T" BEFORE INSERT OR UPDATE ON COMPCONTACT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COMPCONTACT_T" ENABLE
