-- TRIGGER: MAXIMO.CONDITION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONDITION_T" BEFORE INSERT OR UPDATE ON CONDITION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONDITION_T" ENABLE
