-- TRIGGER: MAXIMO.CONTRACTTERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTTERM_T" BEFORE INSERT OR UPDATE ON CONTRACTTERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTTERM_T" ENABLE
