-- TRIGGER: MAXIMO.CONTRACTLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTLINE_T" BEFORE INSERT OR UPDATE ON CONTRACTLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTLINE_T" ENABLE
