-- TRIGGER: MAXIMO.CONTRACTASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTASSET_T" BEFORE INSERT OR UPDATE ON CONTRACTASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTASSET_T" ENABLE
