-- TRIGGER: MAXIMO.CONTASSETMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTASSETMETER_T" BEFORE INSERT OR UPDATE ON CONTASSETMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTASSETMETER_T" ENABLE
