-- TRIGGER: MAXIMO.CONTRACTMASTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTMASTER_T" BEFORE INSERT OR UPDATE ON CONTRACTMASTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTMASTER_T" ENABLE
