-- TRIGGER: MAXIMO.CONTRACTLEASE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTLEASE_T" BEFORE INSERT OR UPDATE ON CONTRACTLEASE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTLEASE_T" ENABLE
