-- TRIGGER: MAXIMO.CONTRACTTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTTYPE_T" BEFORE INSERT OR UPDATE ON CONTRACTTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTTYPE_T" ENABLE
