-- TRIGGER: MAXIMO.CONTRACTSFW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTSFW_T" BEFORE INSERT OR UPDATE ON CONTRACTSFW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTSFW_T" ENABLE
