-- TRIGGER: MAXIMO.CONTRACT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACT_T" BEFORE INSERT OR UPDATE ON CONTRACT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACT_T" ENABLE
