-- TRIGGER: MAXIMO.CONTLINEASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTLINEASSET_T" BEFORE INSERT OR UPDATE ON CONTLINEASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTLINEASSET_T" ENABLE
