-- TRIGGER: MAXIMO.CONTRACTPROPERTY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTPROPERTY_T" BEFORE INSERT OR UPDATE ON CONTRACTPROPERTY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTPROPERTY_T" ENABLE
