-- TRIGGER: MAXIMO.CONTRACTDEFAULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTDEFAULT_T" BEFORE INSERT OR UPDATE ON CONTRACTDEFAULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTDEFAULT_T" ENABLE
