-- TRIGGER: MAXIMO.CONTRACTTYPETERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTTYPETERM_T" BEFORE INSERT OR UPDATE ON CONTRACTTYPETERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTTYPETERM_T" ENABLE
