-- TRIGGER: MAXIMO.CONTRACTSWLIC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTSWLIC_T" BEFORE INSERT OR UPDATE ON CONTRACTSWLIC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTSWLIC_T" ENABLE
