-- TRIGGER: MAXIMO.CONTSFWLIC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTSFWLIC_T" BEFORE INSERT OR UPDATE ON CONTSFWLIC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTSFWLIC_T" ENABLE
