-- TRIGGER: MAXIMO.CONTCOMMODITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTCOMMODITY_T" BEFORE INSERT OR UPDATE ON CONTCOMMODITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTCOMMODITY_T" ENABLE
