-- TRIGGER: MAXIMO.CONTRACTPURCH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONTRACTPURCH_T" BEFORE INSERT OR UPDATE ON CONTRACTPURCH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONTRACTPURCH_T" ENABLE
