-- TRIGGER: MAXIMO.CONVERSION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CONVERSION_T" BEFORE INSERT OR UPDATE ON CONVERSION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CONVERSION_T" ENABLE
