-- TRIGGER: MAXIMO.COSTTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COSTTYPE_T" BEFORE INSERT OR UPDATE ON COSTTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."COSTTYPE_T" ENABLE
