-- TRIGGER: MAXIMO.COUNTBOOK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COUNTBOOK_T" BEFORE INSERT OR UPDATE ON COUNTBOOK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."COUNTBOOK_T" ENABLE
