-- TRIGGER: MAXIMO.COUNTBOOKCHNGSTAT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COUNTBOOKCHNGSTAT_T" BEFORE INSERT OR UPDATE ON COUNTBOOKCHNGSTAT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."COUNTBOOKCHNGSTAT_T" ENABLE
