-- TRIGGER: MAXIMO.COUNTBOOKSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COUNTBOOKSTATUS_T" BEFORE INSERT OR UPDATE ON COUNTBOOKSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."COUNTBOOKSTATUS_T" ENABLE
