-- TRIGGER: MAXIMO.COUNTBOOKSEL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COUNTBOOKSEL_T" BEFORE INSERT OR UPDATE ON COUNTBOOKSEL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."COUNTBOOKSEL_T" ENABLE
