-- TRIGGER: MAXIMO.COUNTBOOKLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."COUNTBOOKLINE_T" BEFORE INSERT OR UPDATE ON COUNTBOOKLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."COUNTBOOKLINE_T" ENABLE
