-- TRIGGER: MAXIMO.CRAFTSKILL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CRAFTSKILL_T" BEFORE INSERT OR UPDATE ON CRAFTSKILL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CRAFTSKILL_T" ENABLE
