-- TRIGGER: MAXIMO.CRONTASKHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CRONTASKHISTORY_T" BEFORE INSERT OR UPDATE ON CRONTASKHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CRONTASKHISTORY_T" ENABLE
