-- TRIGGER: MAXIMO.CRONTASKDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CRONTASKDEF_T" BEFORE INSERT OR UPDATE ON CRONTASKDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CRONTASKDEF_T" ENABLE
