-- TRIGGER: MAXIMO.CRONTASKPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CRONTASKPARAM_T" BEFORE INSERT OR UPDATE ON CRONTASKPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CRONTASKPARAM_T" ENABLE
