-- TRIGGER: MAXIMO.CRONTASKINSTANCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CRONTASKINSTANCE_T" BEFORE INSERT OR UPDATE ON CRONTASKINSTANCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CRONTASKINSTANCE_T" ENABLE
