-- TRIGGER: MAXIMO.CTRLCONDPROP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CTRLCONDPROP_T" BEFORE INSERT OR UPDATE ON CTRLCONDPROP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CTRLCONDPROP_T" ENABLE
