-- TRIGGER: MAXIMO.CTRLGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CTRLGROUP_T" BEFORE INSERT OR UPDATE ON CTRLGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CTRLGROUP_T" ENABLE
