-- TRIGGER: MAXIMO.CTRLCONDITION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CTRLCONDITION_T" BEFORE INSERT OR UPDATE ON CTRLCONDITION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CTRLCONDITION_T" ENABLE
