-- TRIGGER: MAXIMO.CURRENCY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."CURRENCY_T" BEFORE INSERT OR UPDATE ON CURRENCY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."CURRENCY_T" ENABLE
