-- TRIGGER: MAXIMO.DATAPROFILEATTRIB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DATAPROFILEATTRIB_T" BEFORE INSERT OR UPDATE ON DATAPROFILEATTRIBUTE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."DATAPROFILEATTRIB_T" ENABLE
