-- TRIGGER: MAXIMO.DATAPROFILE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DATAPROFILE_T" BEFORE INSERT OR UPDATE ON DATAPROFILE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."DATAPROFILE_T" ENABLE
