-- TRIGGER: MAXIMO.DDUSERAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DDUSERAUTH_T" BEFORE INSERT OR UPDATE ON DDUSERAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."DDUSERAUTH_T" ENABLE
