-- TRIGGER: MAXIMO.DEFAULTQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEFAULTQUERY_T" BEFORE INSERT OR UPDATE ON DEFAULTQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEFAULTQUERY_T" ENABLE
