-- TRIGGER: MAXIMO.DEFAULTOSQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEFAULTOSQUERY_T" BEFORE INSERT OR UPDATE ON DEFAULTOSQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEFAULTOSQUERY_T" ENABLE
