-- TRIGGER: MAXIMO.DEPLOYEDASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEPLOYEDASSET_T" BEFORE INSERT OR UPDATE ON DEPLOYEDASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEPLOYEDASSET_T" ENABLE
