-- TRIGGER: MAXIMO.DEPSCHED_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEPSCHED_T" BEFORE INSERT OR UPDATE ON DEPSCHED FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEPSCHED_T" ENABLE
