-- TRIGGER: MAXIMO.DEPSCHEDPERIODS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEPSCHEDPERIODS_T" BEFORE INSERT OR UPDATE ON DEPSCHEDPERIODS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEPSCHEDPERIODS_T" ENABLE
