-- TRIGGER: MAXIMO.DEPSCHEDHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEPSCHEDHISTORY_T" BEFORE INSERT OR UPDATE ON DEPSCHEDHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEPSCHEDHISTORY_T" ENABLE
