-- TRIGGER: MAXIMO.DEPTRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DEPTRANS_T" BEFORE INSERT OR UPDATE ON DEPTRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DEPTRANS_T" ENABLE
