-- TRIGGER: MAXIMO.DMCFGGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCFGGROUP_T" BEFORE INSERT OR UPDATE ON DMCFGGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCFGGROUP_T" ENABLE
