-- TRIGGER: MAXIMO.DMCFGOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCFGOBJECT_T" BEFORE INSERT OR UPDATE ON DMCFGOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCFGOBJECT_T" ENABLE
