-- TRIGGER: MAXIMO.DMCOLLECTIONRELOB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLECTIONRELOB_T" BEFORE INSERT OR UPDATE ON DMCOLLECTIONRELOBJ FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLECTIONRELOB_T" ENABLE
