-- TRIGGER: MAXIMO.DMCOLLECTIONEXPOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLECTIONEXPOR_T" BEFORE INSERT OR UPDATE ON DMCOLLECTIONEXPORT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLECTIONEXPOR_T" ENABLE
