-- TRIGGER: MAXIMO.DMCOLLRELRULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLRELRULE_T" BEFORE INSERT OR UPDATE ON DMCOLLRELRULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLRELRULE_T" ENABLE
