-- TRIGGER: MAXIMO.DMCOMPRESULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOMPRESULT_T" BEFORE INSERT OR UPDATE ON DMCOMPRESULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOMPRESULT_T" ENABLE
