-- TRIGGER: MAXIMO.DMCOLLPACKAGEMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLPACKAGEMAP_T" BEFORE INSERT OR UPDATE ON DMCOLLPACKAGEMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLPACKAGEMAP_T" ENABLE
