-- TRIGGER: MAXIMO.DMCOLLRELRULECOLS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLRELRULECOLS_T" BEFORE INSERT OR UPDATE ON DMCOLLRELRULECOLS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLRELRULECOLS_T" ENABLE
