-- TRIGGER: MAXIMO.DMCOMPRESRECORD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOMPRESRECORD_T" BEFORE INSERT OR UPDATE ON DMCOMPRESRECORD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOMPRESRECORD_T" ENABLE
