-- TRIGGER: MAXIMO.DMCOLLECTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLECTION_T" BEFORE INSERT OR UPDATE ON DMCOLLECTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLECTION_T" ENABLE
