-- TRIGGER: MAXIMO.DMCOLLPKGEXCEPTIO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLPKGEXCEPTIO_T" BEFORE INSERT OR UPDATE ON DMCOLLPKGEXCEPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLPKGEXCEPTIO_T" ENABLE
