-- TRIGGER: MAXIMO.DMCOMPJOB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOMPJOB_T" BEFORE INSERT OR UPDATE ON DMCOMPJOB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOMPJOB_T" ENABLE
