-- TRIGGER: MAXIMO.DMCOLLLOOKUPRULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLLOOKUPRULE_T" BEFORE INSERT OR UPDATE ON DMCOLLLOOKUPRULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLLOOKUPRULE_T" ENABLE
