-- TRIGGER: MAXIMO.DMCOLLEVENTTRK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLEVENTTRK_T" BEFORE INSERT OR UPDATE ON DMCOLLEVENTTRK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLEVENTTRK_T" ENABLE
