-- TRIGGER: MAXIMO.DMCOLLAPPTOOLBAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMCOLLAPPTOOLBAR_T" BEFORE INSERT OR UPDATE ON DMCOLLAPPTOOLBAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMCOLLAPPTOOLBAR_T" ENABLE
