-- TRIGGER: MAXIMO.DMERROR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMERROR_T" BEFORE INSERT OR UPDATE ON DMERROR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMERROR_T" ENABLE
