-- TRIGGER: MAXIMO.DMMAPDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMMAPDEF_T" BEFORE INSERT OR UPDATE ON DMMAPDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMMAPDEF_T" ENABLE
