-- TRIGGER: MAXIMO.DMMESSAGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMMESSAGE_T" BEFORE INSERT OR UPDATE ON DMMESSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMMESSAGE_T" ENABLE
