-- TRIGGER: MAXIMO.DMPACKAGEDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPACKAGEDEF_T" BEFORE INSERT OR UPDATE ON DMPACKAGEDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPACKAGEDEF_T" ENABLE
