-- TRIGGER: MAXIMO.DMPKGEVENTTRK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGEVENTTRK_T" BEFORE INSERT OR UPDATE ON DMPKGEVENTTRK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGEVENTTRK_T" ENABLE
