-- TRIGGER: MAXIMO.DMPKGDEFSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGDEFSTATUS_T" BEFORE INSERT OR UPDATE ON DMPKGDEFSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGDEFSTATUS_T" ENABLE
