-- TRIGGER: MAXIMO.DMPKGSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGSTATUS_T" BEFORE INSERT OR UPDATE ON DMPKGSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGSTATUS_T" ENABLE
