-- TRIGGER: MAXIMO.DMPKGDSTTRGT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGDSTTRGT_T" BEFORE INSERT OR UPDATE ON DMPKGDSTTRGT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGDSTTRGT_T" ENABLE
