-- TRIGGER: MAXIMO.DMPKGCMPSRC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGCMPSRC_T" BEFORE INSERT OR UPDATE ON DMPKGCMPSRC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGCMPSRC_T" ENABLE
