-- TRIGGER: MAXIMO.DMPKGSTAGING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGSTAGING_T" BEFORE INSERT OR UPDATE ON DMPKGSTAGING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGSTAGING_T" ENABLE
