-- TRIGGER: MAXIMO.DMPKGTRACKHIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGTRACKHIST_T" BEFORE INSERT OR UPDATE ON DMPKGTRACKHIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGTRACKHIST_T" ENABLE
