-- TRIGGER: MAXIMO.DMPKGDIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGDIST_T" BEFORE INSERT OR UPDATE ON DMPKGDIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGDIST_T" ENABLE
