-- TRIGGER: MAXIMO.DMPKGCFGGRPDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGCFGGRPDEF_T" BEFORE INSERT OR UPDATE ON DMPKGCFGGRPDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGCFGGRPDEF_T" ENABLE
