-- TRIGGER: MAXIMO.DMPKGCMPSRCDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGCMPSRCDEF_T" BEFORE INSERT OR UPDATE ON DMPKGCMPSRCDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGCMPSRCDEF_T" ENABLE
