-- TRIGGER: MAXIMO.DMPKGCFGOBJDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMPKGCFGOBJDEF_T" BEFORE INSERT OR UPDATE ON DMPKGCFGOBJDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMPKGCFGOBJDEF_T" ENABLE
