-- TRIGGER: MAXIMO.DMRESTRICTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMRESTRICTION_T" BEFORE INSERT OR UPDATE ON DMRESTRICTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMRESTRICTION_T" ENABLE
