-- TRIGGER: MAXIMO.DMSAPISETTING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DMSAPISETTING_T" BEFORE INSERT OR UPDATE ON DMSAPISETTING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DMSAPISETTING_T" ENABLE
