-- TRIGGER: MAXIMO.DOCLINKS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DOCLINKS_T" BEFORE INSERT OR UPDATE ON DOCLINKS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DOCLINKS_T" ENABLE
