-- TRIGGER: MAXIMO.DOCTYPES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DOCTYPES_T" BEFORE INSERT OR UPDATE ON DOCTYPES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DOCTYPES_T" ENABLE
