-- TRIGGER: MAXIMO.DOMAINMETA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DOMAINMETA_T" BEFORE INSERT OR UPDATE ON DOMAINMETA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."DOMAINMETA_T" ENABLE
