-- TRIGGER: MAXIMO.DPACPU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPACPU_T" BEFORE INSERT OR UPDATE ON DPACPU FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPACPU_T" ENABLE
