-- TRIGGER: MAXIMO.DPACOMPUTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPACOMPUTER_T" BEFORE INSERT OR UPDATE ON DPACOMPUTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPACOMPUTER_T" ENABLE
