-- TRIGGER: MAXIMO.DPADISK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPADISK_T" BEFORE INSERT OR UPDATE ON DPADISK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPADISK_T" ENABLE
