-- TRIGGER: MAXIMO.DPADISPLAY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPADISPLAY_T" BEFORE INSERT OR UPDATE ON DPADISPLAY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPADISPLAY_T" ENABLE
