-- TRIGGER: MAXIMO.DPAFILE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAFILE_T" BEFORE INSERT OR UPDATE ON DPAFILE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAFILE_T" ENABLE
