-- TRIGGER: MAXIMO.DPAIPX_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAIPX_T" BEFORE INSERT OR UPDATE ON DPAIPX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAIPX_T" ENABLE
