-- TRIGGER: MAXIMO.DPAIMAGEDEVICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAIMAGEDEVICE_T" BEFORE INSERT OR UPDATE ON DPAIMAGEDEVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAIMAGEDEVICE_T" ENABLE
