-- TRIGGER: MAXIMO.DPALOGICALDRIVE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPALOGICALDRIVE_T" BEFORE INSERT OR UPDATE ON DPALOGICALDRIVE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPALOGICALDRIVE_T" ENABLE
