-- TRIGGER: MAXIMO.DPAMMANUVARIANT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMMANUVARIANT_T" BEFORE INSERT OR UPDATE ON DPAMMANUVARIANT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMMANUVARIANT_T" ENABLE
