-- TRIGGER: MAXIMO.DPAMADAPTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMADAPTER_T" BEFORE INSERT OR UPDATE ON DPAMADAPTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMADAPTER_T" ENABLE
