-- TRIGGER: MAXIMO.DPAMOSVARIANT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMOSVARIANT_T" BEFORE INSERT OR UPDATE ON DPAMOSVARIANT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMOSVARIANT_T" ENABLE
