-- TRIGGER: MAXIMO.DPAMOS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMOS_T" BEFORE INSERT OR UPDATE ON DPAMOS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMOS_T" ENABLE
