-- TRIGGER: MAXIMO.DPAMSOFTWARE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMSOFTWARE_T" BEFORE INSERT OR UPDATE ON DPAMSOFTWARE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMSOFTWARE_T" ENABLE
