-- TRIGGER: MAXIMO.DPAMPROCESSOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMPROCESSOR_T" BEFORE INSERT OR UPDATE ON DPAMPROCESSOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMPROCESSOR_T" ENABLE
