-- TRIGGER: MAXIMO.DPAMSWUSAGERANGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMSWUSAGERANGE_T" BEFORE INSERT OR UPDATE ON DPAMSWUSAGERANGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMSWUSAGERANGE_T" ENABLE
