-- TRIGGER: MAXIMO.DPAMSWVARIANT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMSWVARIANT_T" BEFORE INSERT OR UPDATE ON DPAMSWVARIANT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMSWVARIANT_T" ENABLE
