-- TRIGGER: MAXIMO.DPAMSWSUITECOMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMSWSUITECOMP_T" BEFORE INSERT OR UPDATE ON DPAMSWSUITECOMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMSWSUITECOMP_T" ENABLE
