-- TRIGGER: MAXIMO.DPAMMANUFACTURER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMMANUFACTURER_T" BEFORE INSERT OR UPDATE ON DPAMMANUFACTURER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMMANUFACTURER_T" ENABLE
