-- TRIGGER: MAXIMO.DPAMEDIAADAPTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMEDIAADAPTER_T" BEFORE INSERT OR UPDATE ON DPAMEDIAADAPTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMEDIAADAPTER_T" ENABLE
