-- TRIGGER: MAXIMO.DPAMPROCVARIANT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMPROCVARIANT_T" BEFORE INSERT OR UPDATE ON DPAMPROCVARIANT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMPROCVARIANT_T" ENABLE
