-- TRIGGER: MAXIMO.DPAMSWSUITE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAMSWSUITE_T" BEFORE INSERT OR UPDATE ON DPAMSWSUITE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAMSWSUITE_T" ENABLE
