-- TRIGGER: MAXIMO.DPANETADAPTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPANETADAPTER_T" BEFORE INSERT OR UPDATE ON DPANETADAPTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPANETADAPTER_T" ENABLE
