-- TRIGGER: MAXIMO.DPANETDEVCARD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPANETDEVCARD_T" BEFORE INSERT OR UPDATE ON DPANETDEVCARD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPANETDEVCARD_T" ENABLE
