-- TRIGGER: MAXIMO.DPANETDEVICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPANETDEVICE_T" BEFORE INSERT OR UPDATE ON DPANETDEVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPANETDEVICE_T" ENABLE
