-- TRIGGER: MAXIMO.DPAOS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAOS_T" BEFORE INSERT OR UPDATE ON DPAOS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAOS_T" ENABLE
