-- TRIGGER: MAXIMO.DPASOFTWARE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPASOFTWARE_T" BEFORE INSERT OR UPDATE ON DPASOFTWARE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPASOFTWARE_T" ENABLE
