-- TRIGGER: MAXIMO.DPASWSUITE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPASWSUITE_T" BEFORE INSERT OR UPDATE ON DPASWSUITE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPASWSUITE_T" ENABLE
