-- TRIGGER: MAXIMO.DPAUSERINFO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."DPAUSERINFO_T" BEFORE INSERT OR UPDATE ON DPAUSERINFO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."DPAUSERINFO_T" ENABLE
