-- TRIGGER: MAXIMO.EMAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EMAIL_T" BEFORE INSERT OR UPDATE ON EMAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."EMAIL_T" ENABLE
