-- TRIGGER: MAXIMO.ESCALATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ESCALATION_T" BEFORE INSERT OR UPDATE ON ESCALATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ESCALATION_T" ENABLE
