-- TRIGGER: MAXIMO.ESCNOTIFICATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ESCNOTIFICATION_T" BEFORE INSERT OR UPDATE ON ESCNOTIFICATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ESCNOTIFICATION_T" ENABLE
