-- TRIGGER: MAXIMO.ESCREFPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ESCREFPOINT_T" BEFORE INSERT OR UPDATE ON ESCREFPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ESCREFPOINT_T" ENABLE
