-- TRIGGER: MAXIMO.ESCREPEATTRACK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ESCREPEATTRACK_T" BEFORE INSERT OR UPDATE ON ESCREPEATTRACK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ESCREPEATTRACK_T" ENABLE
