-- TRIGGER: MAXIMO.ESCSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ESCSTATUS_T" BEFORE INSERT OR UPDATE ON ESCSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ESCSTATUS_T" ENABLE
