-- TRIGGER: MAXIMO.EVENTRESPONSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EVENTRESPONSE_T" BEFORE INSERT OR UPDATE ON EVENTRESPONSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."EVENTRESPONSE_T" ENABLE
