-- TRIGGER: MAXIMO.EXCHANGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXCHANGE_T" BEFORE INSERT OR UPDATE ON EXCHANGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."EXCHANGE_T" ENABLE
