-- TRIGGER: MAXIMO.EXCLUDEPASSWORD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXCLUDEPASSWORD_T" BEFORE INSERT OR UPDATE ON EXCLUDEPASSWORD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."EXCLUDEPASSWORD_T" ENABLE
