-- TRIGGER: MAXIMO.EXCLUDEDACTIONS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXCLUDEDACTIONS_T" BEFORE INSERT OR UPDATE ON EXCLUDEDACTIONS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."EXCLUDEDACTIONS_T" ENABLE
