-- TRIGGER: MAXIMO.EXCLUDEDMAPAPPS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXCLUDEDMAPAPPS_T" BEFORE INSERT OR UPDATE ON EXCLUDEDMAPAPPS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."EXCLUDEDMAPAPPS_T" ENABLE
