-- TRIGGER: MAXIMO.EXPCONDITION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXPCONDITION_T" BEFORE INSERT OR UPDATE ON EXPCONDITION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."EXPCONDITION_T" ENABLE
