-- TRIGGER: MAXIMO.EXPEXCEPTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXPEXCEPTION_T" BEFORE INSERT OR UPDATE ON EXPEXCEPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."EXPEXCEPTION_T" ENABLE
