-- TRIGGER: MAXIMO.EXPFUNCTIONS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXPFUNCTIONS_T" BEFORE INSERT OR UPDATE ON EXPFUNCTIONS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."EXPFUNCTIONS_T" ENABLE
