-- TRIGGER: MAXIMO.EXPGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXPGROUP_T" BEFORE INSERT OR UPDATE ON EXPGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."EXPGROUP_T" ENABLE
