-- TRIGGER: MAXIMO.EXPORTDATATS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."EXPORTDATATS_T" BEFORE INSERT OR UPDATE ON EXPORTDATATS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."EXPORTDATATS_T" ENABLE
