-- TRIGGER: MAXIMO.FACONFIG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FACONFIG_T" BEFORE INSERT OR UPDATE ON FACONFIG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FACONFIG_T" ENABLE
