-- TRIGGER: MAXIMO.FAILUREREMARK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FAILUREREMARK_T" BEFORE INSERT OR UPDATE ON FAILUREREMARK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FAILUREREMARK_T" ENABLE
