-- TRIGGER: MAXIMO.FAILUREREPORT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FAILUREREPORT_T" BEFORE INSERT OR UPDATE ON FAILUREREPORT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FAILUREREPORT_T" ENABLE
