-- TRIGGER: MAXIMO.FAILURECODE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FAILURECODE_T" BEFORE INSERT OR UPDATE ON FAILURECODE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FAILURECODE_T" ENABLE
