-- TRIGGER: MAXIMO.FAVITEM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FAVITEM_T" BEFORE INSERT OR UPDATE ON FAVITEM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FAVITEM_T" ENABLE
