-- TRIGGER: MAXIMO.FEATURES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FEATURES_T" BEFORE INSERT OR UPDATE ON FEATURES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FEATURES_T" ENABLE
