-- TRIGGER: MAXIMO.FEATURESTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FEATURESTATUS_T" BEFORE INSERT OR UPDATE ON FEATURESTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FEATURESTATUS_T" ENABLE
