-- TRIGGER: MAXIMO.FEATURESPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FEATURESPEC_T" BEFORE INSERT OR UPDATE ON FEATURESPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FEATURESPEC_T" ENABLE
