-- TRIGGER: MAXIMO.FILEEXPORTREQQUEU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FILEEXPORTREQQUEU_T" BEFORE INSERT OR UPDATE ON FILEEXPORTREQQUEUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."FILEEXPORTREQQUEU_T" ENABLE
