-- TRIGGER: MAXIMO.FINANCIALPERIODS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FINANCIALPERIODS_T" BEFORE INSERT OR UPDATE ON FINANCIALPERIODS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FINANCIALPERIODS_T" ENABLE
