-- TRIGGER: MAXIMO.FINCNTRL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FINCNTRL_T" BEFORE INSERT OR UPDATE ON FINCNTRL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FINCNTRL_T" ENABLE
