-- TRIGGER: MAXIMO.FSNCLASSQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNCLASSQUAL_T" BEFORE INSERT OR UPDATE ON FSNCLASSQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNCLASSQUAL_T" ENABLE
