-- TRIGGER: MAXIMO.FSNCLASS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNCLASS_T" BEFORE INSERT OR UPDATE ON FSNCLASS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNCLASS_T" ENABLE
