-- TRIGGER: MAXIMO.FSNCLASSRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNCLASSRELATION_T" BEFORE INSERT OR UPDATE ON FSNCLASSRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNCLASSRELATION_T" ENABLE
