-- TRIGGER: MAXIMO.FSNMTHDPARAMQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNMTHDPARAMQUAL_T" BEFORE INSERT OR UPDATE ON FSNMTHDPARAMQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNMTHDPARAMQUAL_T" ENABLE
