-- TRIGGER: MAXIMO.FSNMETHODPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNMETHODPARAM_T" BEFORE INSERT OR UPDATE ON FSNMETHODPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNMETHODPARAM_T" ENABLE
