-- TRIGGER: MAXIMO.FSNMETHOD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNMETHOD_T" BEFORE INSERT OR UPDATE ON FSNMETHOD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNMETHOD_T" ENABLE
