-- TRIGGER: MAXIMO.FSNMTHDQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNMTHDQUAL_T" BEFORE INSERT OR UPDATE ON FSNMTHDQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNMTHDQUAL_T" ENABLE
