-- TRIGGER: MAXIMO.FSNOBJPROPERTY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNOBJPROPERTY_T" BEFORE INSERT OR UPDATE ON FSNOBJPROPERTY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNOBJPROPERTY_T" ENABLE
