-- TRIGGER: MAXIMO.FSNOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNOBJECT_T" BEFORE INSERT OR UPDATE ON FSNOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNOBJECT_T" ENABLE
