-- TRIGGER: MAXIMO.FSNOBJRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNOBJRELATION_T" BEFORE INSERT OR UPDATE ON FSNOBJRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNOBJRELATION_T" ENABLE
