-- TRIGGER: MAXIMO.FSNPROVIDER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNPROVIDER_T" BEFORE INSERT OR UPDATE ON FSNPROVIDER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNPROVIDER_T" ENABLE
