-- TRIGGER: MAXIMO.FSNPROPERTY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNPROPERTY_T" BEFORE INSERT OR UPDATE ON FSNPROPERTY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNPROPERTY_T" ENABLE
