-- TRIGGER: MAXIMO.FSNQUALIFIER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNQUALIFIER_T" BEFORE INSERT OR UPDATE ON FSNQUALIFIER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNQUALIFIER_T" ENABLE
