-- TRIGGER: MAXIMO.FSNREFPROPERTY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNREFPROPERTY_T" BEFORE INSERT OR UPDATE ON FSNREFPROPERTY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNREFPROPERTY_T" ENABLE
