-- TRIGGER: MAXIMO.FSNSQLTABLE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNSQLTABLE_T" BEFORE INSERT OR UPDATE ON FSNSQLTABLE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNSQLTABLE_T" ENABLE
