-- TRIGGER: MAXIMO.FSNSQLCOLUMN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNSQLCOLUMN_T" BEFORE INSERT OR UPDATE ON FSNSQLCOLUMN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNSQLCOLUMN_T" ENABLE
