-- TRIGGER: MAXIMO.FSNSCHEMA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNSCHEMA_T" BEFORE INSERT OR UPDATE ON FSNSCHEMA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNSCHEMA_T" ENABLE
