-- TRIGGER: MAXIMO.FSNTABLEQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."FSNTABLEQUAL_T" BEFORE INSERT OR UPDATE ON FSNTABLEQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."FSNTABLEQUAL_T" ENABLE
