-- TRIGGER: MAXIMO.GBTEMPLATECFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GBTEMPLATECFG_T" BEFORE INSERT OR UPDATE ON GBTEMPLATECFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."GBTEMPLATECFG_T" ENABLE
