-- TRIGGER: MAXIMO.GBTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GBTEMPLATE_T" BEFORE INSERT OR UPDATE ON GBTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."GBTEMPLATE_T" ENABLE
