-- TRIGGER: MAXIMO.GLAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GLAUTH_T" BEFORE INSERT OR UPDATE ON GLAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."GLAUTH_T" ENABLE
