-- TRIGGER: MAXIMO.GLCONFIGURE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GLCONFIGURE_T" BEFORE INSERT OR UPDATE ON GLCONFIGURE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."GLCONFIGURE_T" ENABLE
