-- TRIGGER: MAXIMO.GLCOMPONENTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GLCOMPONENTS_T" BEFORE INSERT OR UPDATE ON GLCOMPONENTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."GLCOMPONENTS_T" ENABLE
