-- TRIGGER: MAXIMO.GROUPUSER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GROUPUSER_T" BEFORE INSERT OR UPDATE ON GROUPUSER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."GROUPUSER_T" ENABLE
