-- TRIGGER: MAXIMO.GRPREASSIGNAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GRPREASSIGNAUTH_T" BEFORE INSERT OR UPDATE ON GRPREASSIGNAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."GRPREASSIGNAUTH_T" ENABLE
