-- TRIGGER: MAXIMO.GUESTTRUSTEMAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GUESTTRUSTEMAIL_T" BEFORE INSERT OR UPDATE ON GUESTTRUSTEMAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."GUESTTRUSTEMAIL_T" ENABLE
