-- TRIGGER: MAXIMO.GUESTTRUSTDOMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."GUESTTRUSTDOMAIN_T" BEFORE INSERT OR UPDATE ON GUESTTRUSTDOMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."GUESTTRUSTDOMAIN_T" ENABLE
