-- TRIGGER: MAXIMO.HAZARDPREC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."HAZARDPREC_T" BEFORE INSERT OR UPDATE ON HAZARDPREC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."HAZARDPREC_T" ENABLE
