-- TRIGGER: MAXIMO.HAZARD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."HAZARD_T" BEFORE INSERT OR UPDATE ON HAZARD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."HAZARD_T" ENABLE
