-- TRIGGER: MAXIMO.IBMCONTENTRECEIP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IBMCONTENTRECEIP_T" BEFORE INSERT OR UPDATE ON IBMCONTENTRECEIPTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."IBMCONTENTRECEIP_T" ENABLE
