-- TRIGGER: MAXIMO.IBMCONTENTCATALOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IBMCONTENTCATALOG_T" BEFORE INSERT OR UPDATE ON IBMCONTENTCATALOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."IBMCONTENTCATALOG_T" ENABLE
