-- TRIGGER: MAXIMO.IMPROFILE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IMPROFILE_T" BEFORE INSERT OR UPDATE ON IMPROFILE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."IMPROFILE_T" ENABLE
