-- TRIGGER: MAXIMO.INBCOMMSECURITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INBCOMMSECURITY_T" BEFORE INSERT OR UPDATE ON INBCOMMSECURITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INBCOMMSECURITY_T" ENABLE
