-- TRIGGER: MAXIMO.INBOUNDCOMM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INBOUNDCOMM_T" BEFORE INSERT OR UPDATE ON INBOUNDCOMM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INBOUNDCOMM_T" ENABLE
