-- TRIGGER: MAXIMO.INSIGHTFACTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSIGHTFACTOR_T" BEFORE INSERT OR UPDATE ON INSIGHTFACTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSIGHTFACTOR_T" ENABLE
