-- TRIGGER: MAXIMO.INSIGHT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSIGHT_T" BEFORE INSERT OR UPDATE ON INSIGHT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSIGHT_T" ENABLE
