-- TRIGGER: MAXIMO.INSPECTIONRESULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPECTIONRESULT_T" BEFORE INSERT OR UPDATE ON INSPECTIONRESULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPECTIONRESULT_T" ENABLE
