-- TRIGGER: MAXIMO.INSPFIELD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPFIELD_T" BEFORE INSERT OR UPDATE ON INSPFIELD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPFIELD_T" ENABLE
