-- TRIGGER: MAXIMO.INSPFIELDRESULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPFIELDRESULT_T" BEFORE INSERT OR UPDATE ON INSPFIELDRESULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPFIELDRESULT_T" ENABLE
