-- TRIGGER: MAXIMO.INSPFORMUSEWITH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPFORMUSEWITH_T" BEFORE INSERT OR UPDATE ON INSPFORMUSEWITH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPFORMUSEWITH_T" ENABLE
