-- TRIGGER: MAXIMO.INSPQUESTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPQUESTION_T" BEFORE INSERT OR UPDATE ON INSPQUESTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPQUESTION_T" ENABLE
