-- TRIGGER: MAXIMO.INSPCASCADEOPTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPCASCADEOPTION_T" BEFORE INSERT OR UPDATE ON INSPCASCADEOPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPCASCADEOPTION_T" ENABLE
