-- TRIGGER: MAXIMO.INSPFIELDOPTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPFIELDOPTION_T" BEFORE INSERT OR UPDATE ON INSPFIELDOPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPFIELDOPTION_T" ENABLE
