-- TRIGGER: MAXIMO.INSPFORMSCRIPT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPFORMSCRIPT_T" BEFORE INSERT OR UPDATE ON INSPFORMSCRIPT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPFORMSCRIPT_T" ENABLE
