-- TRIGGER: MAXIMO.INSPECTIONFORMSTA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPECTIONFORMSTA_T" BEFORE INSERT OR UPDATE ON INSPECTIONFORMSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPECTIONFORMSTA_T" ENABLE
