-- TRIGGER: MAXIMO.INSPFIELDRESULTSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPFIELDRESULTSE_T" BEFORE INSERT OR UPDATE ON INSPFIELDRESULTSELECTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPFIELDRESULTSE_T" ENABLE
