-- TRIGGER: MAXIMO.INSPRESULTSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INSPRESULTSTATUS_T" BEFORE INSERT OR UPDATE ON INSPRESULTSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INSPRESULTSTATUS_T" ENABLE
