-- TRIGGER: MAXIMO.INVBALANCES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVBALANCES_T" BEFORE INSERT OR UPDATE ON INVBALANCES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVBALANCES_T" ENABLE
