-- TRIGGER: MAXIMO.INVCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVCOST_T" BEFORE INSERT OR UPDATE ON INVCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVCOST_T" ENABLE
