-- TRIGGER: MAXIMO.INVENTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVENTORY_T" BEFORE INSERT OR UPDATE ON INVENTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVENTORY_T" ENABLE
