-- TRIGGER: MAXIMO.INVLIFOFIFOCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVLIFOFIFOCOST_T" BEFORE INSERT OR UPDATE ON INVLIFOFIFOCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVLIFOFIFOCOST_T" ENABLE
