-- TRIGGER: MAXIMO.INVLOT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVLOT_T" BEFORE INSERT OR UPDATE ON INVLOT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVLOT_T" ENABLE
