-- TRIGGER: MAXIMO.INVOICEMATCH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVOICEMATCH_T" BEFORE INSERT OR UPDATE ON INVOICEMATCH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVOICEMATCH_T" ENABLE
