-- TRIGGER: MAXIMO.INVOICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVOICE_T" BEFORE INSERT OR UPDATE ON INVOICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVOICE_T" ENABLE
