-- TRIGGER: MAXIMO.INVOICECOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVOICECOST_T" BEFORE INSERT OR UPDATE ON INVOICECOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVOICECOST_T" ENABLE
