-- TRIGGER: MAXIMO.INVOICETERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVOICETERM_T" BEFORE INSERT OR UPDATE ON INVOICETERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVOICETERM_T" ENABLE
