-- TRIGGER: MAXIMO.INVOICETRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVOICETRANS_T" BEFORE INSERT OR UPDATE ON INVOICETRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVOICETRANS_T" ENABLE
