-- TRIGGER: MAXIMO.INVPICKLIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVPICKLIST_T" BEFORE INSERT OR UPDATE ON INVPICKLIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."INVPICKLIST_T" ENABLE
