-- TRIGGER: MAXIMO.INVRESERVE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVRESERVE_T" BEFORE INSERT OR UPDATE ON INVRESERVE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVRESERVE_T" ENABLE
