-- TRIGGER: MAXIMO.INVSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVSTATUS_T" BEFORE INSERT OR UPDATE ON INVSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVSTATUS_T" ENABLE
