-- TRIGGER: MAXIMO.INVTRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVTRANS_T" BEFORE INSERT OR UPDATE ON INVTRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVTRANS_T" ENABLE
