-- TRIGGER: MAXIMO.INVUSESTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVUSESTATUS_T" BEFORE INSERT OR UPDATE ON INVUSESTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVUSESTATUS_T" ENABLE
