-- TRIGGER: MAXIMO.INVUSELINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVUSELINE_T" BEFORE INSERT OR UPDATE ON INVUSELINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVUSELINE_T" ENABLE
