-- TRIGGER: MAXIMO.INVUSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVUSE_T" BEFORE INSERT OR UPDATE ON INVUSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVUSE_T" ENABLE
