-- TRIGGER: MAXIMO.INVVENDOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."INVVENDOR_T" BEFORE INSERT OR UPDATE ON INVVENDOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."INVVENDOR_T" ENABLE
