-- TRIGGER: MAXIMO.IOTENDPTDTLS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTENDPTDTLS_T" BEFORE INSERT OR UPDATE ON IOTENDPTDTLS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTENDPTDTLS_T" ENABLE
