-- TRIGGER: MAXIMO.IOTFDEVICEMAPPING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTFDEVICEMAPPING_T" BEFORE INSERT OR UPDATE ON IOTFDEVICEMAPPING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTFDEVICEMAPPING_T" ENABLE
