-- TRIGGER: MAXIMO.IOTFCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTFCFG_T" BEFORE INSERT OR UPDATE ON IOTFCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTFCFG_T" ENABLE
