-- TRIGGER: MAXIMO.IOTFDEVICETYPECFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTFDEVICETYPECFG_T" BEFORE INSERT OR UPDATE ON IOTFDEVICETYPECFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTFDEVICETYPECFG_T" ENABLE
