-- TRIGGER: MAXIMO.IOTFHISTORIAN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTFHISTORIAN_T" BEFORE INSERT OR UPDATE ON IOTFHISTORIAN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTFHISTORIAN_T" ENABLE
