-- TRIGGER: MAXIMO.IOTPAYLOADPROPS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTPAYLOADPROPS_T" BEFORE INSERT OR UPDATE ON IOTPAYLOADPROPS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTPAYLOADPROPS_T" ENABLE
