-- TRIGGER: MAXIMO.IOTRESTENDPOINTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTRESTENDPOINTS_T" BEFORE INSERT OR UPDATE ON IOTRESTENDPOINTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTRESTENDPOINTS_T" ENABLE
