-- TRIGGER: MAXIMO.IOTRESTDTLS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTRESTDTLS_T" BEFORE INSERT OR UPDATE ON IOTRESTDTLS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTRESTDTLS_T" ENABLE
