-- TRIGGER: MAXIMO.IOTSERVICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."IOTSERVICE_T" BEFORE INSERT OR UPDATE ON IOTSERVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."IOTSERVICE_T" ENABLE
