-- TRIGGER: MAXIMO.ITEMORGINFO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ITEMORGINFO_T" BEFORE INSERT OR UPDATE ON ITEMORGINFO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ITEMORGINFO_T" ENABLE
