-- TRIGGER: MAXIMO.ITEM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ITEM_T" BEFORE INSERT OR UPDATE ON ITEM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ITEM_T" ENABLE
