-- TRIGGER: MAXIMO.ITEMSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ITEMSTATUS_T" BEFORE INSERT OR UPDATE ON ITEMSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ITEMSTATUS_T" ENABLE
