-- TRIGGER: MAXIMO.ITEMSTRUCT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ITEMSTRUCT_T" BEFORE INSERT OR UPDATE ON ITEMSTRUCT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ITEMSTRUCT_T" ENABLE
