-- TRIGGER: MAXIMO.ITEMSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ITEMSPEC_T" BEFORE INSERT OR UPDATE ON ITEMSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ITEMSPEC_T" ENABLE
