-- TRIGGER: MAXIMO.ITEMCONDITION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ITEMCONDITION_T" BEFORE INSERT OR UPDATE ON ITEMCONDITION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ITEMCONDITION_T" ENABLE
