-- TRIGGER: MAXIMO.JOBITEM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBITEM_T" BEFORE INSERT OR UPDATE ON JOBITEM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBITEM_T" ENABLE
