-- TRIGGER: MAXIMO.JOBLABOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBLABOR_T" BEFORE INSERT OR UPDATE ON JOBLABOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBLABOR_T" ENABLE
