-- TRIGGER: MAXIMO.JOBPLANSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBPLANSPEC_T" BEFORE INSERT OR UPDATE ON JOBPLANSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBPLANSPEC_T" ENABLE
