-- TRIGGER: MAXIMO.JOBPLAN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBPLAN_T" BEFORE INSERT OR UPDATE ON JOBPLAN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBPLAN_T" ENABLE
