-- TRIGGER: MAXIMO.JOBPLANCLASS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBPLANCLASS_T" BEFORE INSERT OR UPDATE ON JOBPLANCLASS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBPLANCLASS_T" ENABLE
