-- TRIGGER: MAXIMO.JOBTASK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBTASK_T" BEFORE INSERT OR UPDATE ON JOBTASK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBTASK_T" ENABLE
