-- TRIGGER: MAXIMO.JOBTASKSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JOBTASKSPEC_T" BEFORE INSERT OR UPDATE ON JOBTASKSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JOBTASKSPEC_T" ENABLE
