-- TRIGGER: MAXIMO.JPASSETSPLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JPASSETSPLINK_T" BEFORE INSERT OR UPDATE ON JPASSETSPLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JPASSETSPLINK_T" ENABLE
