-- TRIGGER: MAXIMO.JPTASKRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JPTASKRELATION_T" BEFORE INSERT OR UPDATE ON JPTASKRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JPTASKRELATION_T" ENABLE
