-- TRIGGER: MAXIMO.JSONRESOURCETYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONRESOURCETYPE_T" BEFORE INSERT OR UPDATE ON JSONRESOURCETYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JSONRESOURCETYPE_T" ENABLE
