-- TRIGGER: MAXIMO.JSONMERGEOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONMERGEOBJECT_T" BEFORE INSERT OR UPDATE ON JSONMERGEOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JSONMERGEOBJECT_T" ENABLE
