-- TRIGGER: MAXIMO.JSONRESOURCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONRESOURCE_T" BEFORE INSERT OR UPDATE ON JSONRESOURCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JSONRESOURCE_T" ENABLE
