-- TRIGGER: MAXIMO.JSONOBJECTMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONOBJECTMAP_T" BEFORE INSERT OR UPDATE ON JSONOBJECTMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JSONOBJECTMAP_T" ENABLE
