-- TRIGGER: MAXIMO.JSONMAPDETAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONMAPDETAIL_T" BEFORE INSERT OR UPDATE ON JSONMAPDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."JSONMAPDETAIL_T" ENABLE
