-- TRIGGER: MAXIMO.JSONMAPPROPVALUES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONMAPPROPVALUES_T" BEFORE INSERT OR UPDATE ON JSONMAPPROPVALUES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."JSONMAPPROPVALUES_T" ENABLE
