-- TRIGGER: MAXIMO.JSONMERGEATTRIBUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONMERGEATTRIBUT_T" BEFORE INSERT OR UPDATE ON JSONMERGEATTRIBUTE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."JSONMERGEATTRIBUT_T" ENABLE
