-- TRIGGER: MAXIMO.JSONMAPPING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."JSONMAPPING_T" BEFORE INSERT OR UPDATE ON JSONMAPPING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."JSONMAPPING_T" ENABLE
