-- TRIGGER: MAXIMO.KPIAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPIAUTH_T" BEFORE INSERT OR UPDATE ON KPIAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPIAUTH_T" ENABLE
