-- TRIGGER: MAXIMO.KPIGCONFIG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPIGCONFIG_T" BEFORE INSERT OR UPDATE ON KPIGCONFIG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPIGCONFIG_T" ENABLE
