-- TRIGGER: MAXIMO.KPIHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPIHISTORY_T" BEFORE INSERT OR UPDATE ON KPIHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPIHISTORY_T" ENABLE
