-- TRIGGER: MAXIMO.KPILCONFIG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPILCONFIG_T" BEFORE INSERT OR UPDATE ON KPILCONFIG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPILCONFIG_T" ENABLE
