-- TRIGGER: MAXIMO.KPIMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPIMAIN_T" BEFORE INSERT OR UPDATE ON KPIMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPIMAIN_T" ENABLE
