-- TRIGGER: MAXIMO.KPIOEE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPIOEE_T" BEFORE INSERT OR UPDATE ON KPIOEE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPIOEE_T" ENABLE
