-- TRIGGER: MAXIMO.KPISCHEDULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPISCHEDULE_T" BEFORE INSERT OR UPDATE ON KPISCHEDULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPISCHEDULE_T" ENABLE
