-- TRIGGER: MAXIMO.KPITRENDCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPITRENDCFG_T" BEFORE INSERT OR UPDATE ON KPITRENDCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPITRENDCFG_T" ENABLE
