-- TRIGGER: MAXIMO.KPITEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPITEMPLATE_T" BEFORE INSERT OR UPDATE ON KPITEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPITEMPLATE_T" ENABLE
