-- TRIGGER: MAXIMO.KPITEMPLATEVAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPITEMPLATEVAR_T" BEFORE INSERT OR UPDATE ON KPITEMPLATEVAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPITEMPLATEVAR_T" ENABLE
