-- TRIGGER: MAXIMO.KPITEMPLATEMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPITEMPLATEMAIN_T" BEFORE INSERT OR UPDATE ON KPITEMPLATEMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPITEMPLATEMAIN_T" ENABLE
