-- TRIGGER: MAXIMO.KPITEMPLATEVARVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."KPITEMPLATEVARVAL_T" BEFORE INSERT OR UPDATE ON KPITEMPLATEVARVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."KPITEMPLATEVARVAL_T" ENABLE
