-- TRIGGER: MAXIMO.L_COMPANIES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_COMPANIES_T" BEFORE INSERT OR UPDATE ON L_COMPANIES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_COMPANIES_T" ENABLE
