-- TRIGGER: MAXIMO.L_MAXMODULES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_MAXMODULES_T" BEFORE INSERT OR UPDATE ON L_MAXMODULES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_MAXMODULES_T" ENABLE
