-- TRIGGER: MAXIMO.L_MAXINTOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_MAXINTOBJECT_T" BEFORE INSERT OR UPDATE ON L_MAXINTOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_MAXINTOBJECT_T" ENABLE
