-- TRIGGER: MAXIMO.L_MAXATTRCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_MAXATTRCFG_T" BEFORE INSERT OR UPDATE ON L_MAXATTRCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_MAXATTRCFG_T" ENABLE
