-- TRIGGER: MAXIMO.L_MAXINTOBJDETAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_MAXINTOBJDETAIL_T" BEFORE INSERT OR UPDATE ON L_MAXINTOBJDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_MAXINTOBJDETAIL_T" ENABLE
