-- TRIGGER: MAXIMO.L_OSLCQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_OSLCQUERY_T" BEFORE INSERT OR UPDATE ON L_OSLCQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."L_OSLCQUERY_T" ENABLE
