-- TRIGGER: MAXIMO.L_QUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_QUERY_T" BEFORE INSERT OR UPDATE ON L_QUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_QUERY_T" ENABLE
