-- TRIGGER: MAXIMO.L_REPORTLOOKUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_REPORTLOOKUP_T" BEFORE INSERT OR UPDATE ON L_REPORTLOOKUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_REPORTLOOKUP_T" ENABLE
