-- TRIGGER: MAXIMO.L_SIGOPTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_SIGOPTION_T" BEFORE INSERT OR UPDATE ON L_SIGOPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_SIGOPTION_T" ENABLE
