-- TRIGGER: MAXIMO.L_SKDRESOURCEVIEW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_SKDRESOURCEVIEW_T" BEFORE INSERT OR UPDATE ON L_SKDRESOURCEVIEW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."L_SKDRESOURCEVIEW_T" ENABLE
