-- TRIGGER: MAXIMO.L_VIEWMANAGER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."L_VIEWMANAGER_T" BEFORE INSERT OR UPDATE ON L_VIEWMANAGER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."L_VIEWMANAGER_T" ENABLE
