-- TRIGGER: MAXIMO.LABORCRAFTRATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABORCRAFTRATE_T" BEFORE INSERT OR UPDATE ON LABORCRAFTRATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABORCRAFTRATE_T" ENABLE
