-- TRIGGER: MAXIMO.LABOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABOR_T" BEFORE INSERT OR UPDATE ON LABOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABOR_T" ENABLE
