-- TRIGGER: MAXIMO.LABORSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABORSTATUS_T" BEFORE INSERT OR UPDATE ON LABORSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABORSTATUS_T" ENABLE
