-- TRIGGER: MAXIMO.LABORAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABORAUTH_T" BEFORE INSERT OR UPDATE ON LABORAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABORAUTH_T" ENABLE
