-- TRIGGER: MAXIMO.LABORQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABORQUAL_T" BEFORE INSERT OR UPDATE ON LABORQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABORQUAL_T" ENABLE
