-- TRIGGER: MAXIMO.LABORCERTHIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABORCERTHIST_T" BEFORE INSERT OR UPDATE ON LABORCERTHIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABORCERTHIST_T" ENABLE
