-- TRIGGER: MAXIMO.LABORWORKZONE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABORWORKZONE_T" BEFORE INSERT OR UPDATE ON LABORWORKZONE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABORWORKZONE_T" ENABLE
