-- TRIGGER: MAXIMO.LABTRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LABTRANS_T" BEFORE INSERT OR UPDATE ON LABTRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LABTRANS_T" ENABLE
