-- TRIGGER: MAXIMO.LANGUAGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LANGUAGE_T" BEFORE INSERT OR UPDATE ON LANGUAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LANGUAGE_T" ENABLE
