-- TRIGGER: MAXIMO.LAUNCHPOINTVARS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LAUNCHPOINTVARS_T" BEFORE INSERT OR UPDATE ON LAUNCHPOINTVARS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LAUNCHPOINTVARS_T" ENABLE
