-- TRIGGER: MAXIMO.LAYOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LAYOUT_T" BEFORE INSERT OR UPDATE ON LAYOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LAYOUT_T" ENABLE
