-- TRIGGER: MAXIMO.LBSLOCATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LBSLOCATION_T" BEFORE INSERT OR UPDATE ON LBSLOCATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LBSLOCATION_T" ENABLE
