-- TRIGGER: MAXIMO.LDAPSYNCPARAMS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LDAPSYNCPARAMS_T" BEFORE INSERT OR UPDATE ON LDAPSYNCPARAMS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LDAPSYNCPARAMS_T" ENABLE
