-- TRIGGER: MAXIMO.LIMITTOLERANCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LIMITTOLERANCE_T" BEFORE INSERT OR UPDATE ON LIMITTOLERANCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LIMITTOLERANCE_T" ENABLE
