-- TRIGGER: MAXIMO.LINEARREFMETHOD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LINEARREFMETHOD_T" BEFORE INSERT OR UPDATE ON LINEARREFMETHOD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LINEARREFMETHOD_T" ENABLE
