-- TRIGGER: MAXIMO.LINEARLAYER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LINEARLAYER_T" BEFORE INSERT OR UPDATE ON LINEARLAYER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LINEARLAYER_T" ENABLE
