-- TRIGGER: MAXIMO.LINEARAPPLAYER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LINEARAPPLAYER_T" BEFORE INSERT OR UPDATE ON LINEARAPPLAYER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LINEARAPPLAYER_T" ENABLE
