-- TRIGGER: MAXIMO.LINEARATTRIBUTEDE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LINEARATTRIBUTEDE_T" BEFORE INSERT OR UPDATE ON LINEARATTRIBUTEDEFAULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LINEARATTRIBUTEDE_T" ENABLE
