-- TRIGGER: MAXIMO.LMO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LMO_T" BEFORE INSERT OR UPDATE ON LMO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LMO_T" ENABLE
