-- TRIGGER: MAXIMO.LMOATT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LMOATT_T" BEFORE INSERT OR UPDATE ON LMOATT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LMOATT_T" ENABLE
