-- TRIGGER: MAXIMO.LMOIMRLN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LMOIMRLN_T" BEFORE INSERT OR UPDATE ON LMOIMRLN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LMOIMRLN_T" ENABLE
