-- TRIGGER: MAXIMO.LNRRECALIB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LNRRECALIB_T" BEFORE INSERT OR UPDATE ON LNRRECALIB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LNRRECALIB_T" ENABLE
