-- TRIGGER: MAXIMO.LNRRECALIBNONAF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LNRRECALIBNONAF_T" BEFORE INSERT OR UPDATE ON LNRRECALIBNONAF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LNRRECALIBNONAF_T" ENABLE
