-- TRIGGER: MAXIMO.LOCATIONSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONSPEC_T" BEFORE INSERT OR UPDATE ON LOCATIONSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCATIONSPEC_T" ENABLE
