-- TRIGGER: MAXIMO.LOCATIONS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONS_T" BEFORE INSERT OR UPDATE ON LOCATIONS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCATIONS_T" ENABLE
