-- TRIGGER: MAXIMO.LOCAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCAUTH_T" BEFORE INSERT OR UPDATE ON LOCAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCAUTH_T" ENABLE
