-- TRIGGER: MAXIMO.LOCATIONMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONMETER_T" BEFORE INSERT OR UPDATE ON LOCATIONMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCATIONMETER_T" ENABLE
