-- TRIGGER: MAXIMO.LOCATIONOPSKD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONOPSKD_T" BEFORE INSERT OR UPDATE ON LOCATIONOPSKD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCATIONOPSKD_T" ENABLE
