-- TRIGGER: MAXIMO.LOCANCESTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCANCESTOR_T" BEFORE INSERT OR UPDATE ON LOCANCESTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCANCESTOR_T" ENABLE
