-- TRIGGER: MAXIMO.LOCATIONWORKZONE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONWORKZONE_T" BEFORE INSERT OR UPDATE ON LOCATIONWORKZONE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCATIONWORKZONE_T" ENABLE
