-- TRIGGER: MAXIMO.LOCATIONSGEOHASH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONSGEOHASH_T" BEFORE INSERT OR UPDATE ON LOCATIONSGEOHASH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LOCATIONSGEOHASH_T" ENABLE
