-- TRIGGER: MAXIMO.LOCATIONMNTSKD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCATIONMNTSKD_T" BEFORE INSERT OR UPDATE ON LOCATIONMNTSKD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCATIONMNTSKD_T" ENABLE
