-- TRIGGER: MAXIMO.LOCKOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCKOUT_T" BEFORE INSERT OR UPDATE ON LOCKOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCKOUT_T" ENABLE
