-- TRIGGER: MAXIMO.LOCLEADTIME_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCLEADTIME_T" BEFORE INSERT OR UPDATE ON LOCLEADTIME FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCLEADTIME_T" ENABLE
