-- TRIGGER: MAXIMO.LOCMETERREADING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCMETERREADING_T" BEFORE INSERT OR UPDATE ON LOCMETERREADING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCMETERREADING_T" ENABLE
