-- TRIGGER: MAXIMO.LOCOPER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCOPER_T" BEFORE INSERT OR UPDATE ON LOCOPER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCOPER_T" ENABLE
