-- TRIGGER: MAXIMO.LOCSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOCSTATUS_T" BEFORE INSERT OR UPDATE ON LOCSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOCSTATUS_T" ENABLE
