-- TRIGGER: MAXIMO.LOGINBLOCK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOGINBLOCK_T" BEFORE INSERT OR UPDATE ON LOGINBLOCK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOGINBLOCK_T" ENABLE
