-- TRIGGER: MAXIMO.LOGICALRELATIONSH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOGICALRELATIONSH_T" BEFORE INSERT OR UPDATE ON LOGICALRELATIONSHIP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOGICALRELATIONSH_T" ENABLE
