-- TRIGGER: MAXIMO.LOGINTRACKING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOGINTRACKING_T" BEFORE INSERT OR UPDATE ON LOGINTRACKING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LOGINTRACKING_T" ENABLE
