-- TRIGGER: MAXIMO.LOGREQUEST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOGREQUEST_T" BEFORE INSERT OR UPDATE ON LOGREQUEST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LOGREQUEST_T" ENABLE
