-- TRIGGER: MAXIMO.LOGREQUESTDET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LOGREQUESTDET_T" BEFORE INSERT OR UPDATE ON LOGREQUESTDET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LOGREQUESTDET_T" ENABLE
