-- TRIGGER: MAXIMO.LRKEYS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LRKEYS_T" BEFORE INSERT OR UPDATE ON LRKEYS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."LRKEYS_T" ENABLE
