-- TRIGGER: MAXIMO.LTPATOKEN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LTPATOKEN_T" BEFORE INSERT OR UPDATE ON LTPATOKEN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LTPATOKEN_T" ENABLE
