-- TRIGGER: MAXIMO.LVCMSGINFODFLT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LVCMSGINFODFLT_T" BEFORE INSERT OR UPDATE ON LVCMSGINFODFLT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LVCMSGINFODFLT_T" ENABLE
