-- TRIGGER: MAXIMO.LVCSYMBOLOGY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LVCSYMBOLOGY_T" BEFORE INSERT OR UPDATE ON LVCSYMBOLOGY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LVCSYMBOLOGY_T" ENABLE
