-- TRIGGER: MAXIMO.LVCSYMBOLOGYDFLT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."LVCSYMBOLOGYDFLT_T" BEFORE INSERT OR UPDATE ON LVCSYMBOLOGYDFLT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."LVCSYMBOLOGYDFLT_T" ENABLE
