-- TRIGGER: MAXIMO.MAFAPPDATA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAFAPPDATA_T" BEFORE INSERT OR UPDATE ON MAFAPPDATA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAFAPPDATA_T" ENABLE
