-- TRIGGER: MAXIMO.MAFMAPPRELOADCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAFMAPPRELOADCFG_T" BEFORE INSERT OR UPDATE ON MAFMAPPRELOADCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAFMAPPRELOADCFG_T" ENABLE
