-- TRIGGER: MAXIMO.MAPMANAGER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPMANAGER_T" BEFORE INSERT OR UPDATE ON MAPMANAGER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAPMANAGER_T" ENABLE
