-- TRIGGER: MAXIMO.MAPSITES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPSITES_T" BEFORE INSERT OR UPDATE ON MAPSITES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAPSITES_T" ENABLE
