-- TRIGGER: MAXIMO.MAPSKETCH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPSKETCH_T" BEFORE INSERT OR UPDATE ON MAPSKETCH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAPSKETCH_T" ENABLE
