-- TRIGGER: MAXIMO.MAPSYMBOLOGYDEFAU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPSYMBOLOGYDEFAU_T" BEFORE INSERT OR UPDATE ON MAPSYMBOLOGYDEFAULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAPSYMBOLOGYDEFAU_T" ENABLE
