-- TRIGGER: MAXIMO.MAPTIPMENU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPTIPMENU_T" BEFORE INSERT OR UPDATE ON MAPTIPMENU FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAPTIPMENU_T" ENABLE
