-- TRIGGER: MAXIMO.MAPTIPDEFAULTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPTIPDEFAULTS_T" BEFORE INSERT OR UPDATE ON MAPTIPDEFAULTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAPTIPDEFAULTS_T" ENABLE
