-- TRIGGER: MAXIMO.MAPTIP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAPTIP_T" BEFORE INSERT OR UPDATE ON MAPTIP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAPTIP_T" ENABLE
