-- TRIGGER: MAXIMO.MASLICAPPACCESS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASLICAPPACCESS_T" BEFORE INSERT OR UPDATE ON MASLICAPPACCESS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MASLICAPPACCESS_T" ENABLE
