-- TRIGGER: MAXIMO.MASLICAPPOPTACCES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASLICAPPOPTACCES_T" BEFORE INSERT OR UPDATE ON MASLICAPPOPTACCESS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MASLICAPPOPTACCES_T" ENABLE
