-- TRIGGER: MAXIMO.MASLICUSAGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASLICUSAGE_T" BEFORE INSERT OR UPDATE ON MASLICUSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MASLICUSAGE_T" ENABLE
