-- TRIGGER: MAXIMO.MASLICAPPOPTPROD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASLICAPPOPTPROD_T" BEFORE INSERT OR UPDATE ON MASLICAPPOPTPROD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MASLICAPPOPTPROD_T" ENABLE
