-- TRIGGER: MAXIMO.MASTERPMSEASONS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASTERPMSEASONS_T" BEFORE INSERT OR UPDATE ON MASTERPMSEASONS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MASTERPMSEASONS_T" ENABLE
