-- TRIGGER: MAXIMO.MASTERPMMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASTERPMMETER_T" BEFORE INSERT OR UPDATE ON MASTERPMMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MASTERPMMETER_T" ENABLE
