-- TRIGGER: MAXIMO.MASTERPMSEQ_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MASTERPMSEQ_T" BEFORE INSERT OR UPDATE ON MASTERPMSEQ FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MASTERPMSEQ_T" ENABLE
