-- TRIGGER: MAXIMO.MATRECTRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MATRECTRANS_T" BEFORE INSERT OR UPDATE ON MATRECTRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MATRECTRANS_T" ENABLE
