-- TRIGGER: MAXIMO.MATUSETRANS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MATUSETRANS_T" BEFORE INSERT OR UPDATE ON MATUSETRANS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MATUSETRANS_T" ENABLE
