-- TRIGGER: MAXIMO.MAXAPPRODTYPES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXAPPRODTYPES_T" BEFORE INSERT OR UPDATE ON MAXAPPRODTYPES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXAPPRODTYPES_T" ENABLE
