-- TRIGGER: MAXIMO.MAXAPINSTVALUES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXAPINSTVALUES_T" BEFORE INSERT OR UPDATE ON MAXAPINSTVALUES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXAPINSTVALUES_T" ENABLE
