-- TRIGGER: MAXIMO.MAXAPPEAKUSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXAPPEAKUSE_T" BEFORE INSERT OR UPDATE ON MAXAPPEAKUSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXAPPEAKUSE_T" ENABLE
