-- TRIGGER: MAXIMO.MAXATTRIBUTESKIPC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXATTRIBUTESKIPC_T" BEFORE INSERT OR UPDATE ON MAXATTRIBUTESKIPCOPY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXATTRIBUTESKIPC_T" ENABLE
