-- TRIGGER: MAXIMO.MAXAPNOTES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXAPNOTES_T" BEFORE INSERT OR UPDATE ON MAXAPNOTES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXAPNOTES_T" ENABLE
