-- TRIGGER: MAXIMO.MAXAPPEAK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXAPPEAK_T" BEFORE INSERT OR UPDATE ON MAXAPPEAK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXAPPEAK_T" ENABLE
