-- TRIGGER: MAXIMO.MAXASYNCJOBMSG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXASYNCJOBMSG_T" BEFORE INSERT OR UPDATE ON MAXASYNCJOBMSG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXASYNCJOBMSG_T" ENABLE
