-- TRIGGER: MAXIMO.MAXASYNCJOBPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXASYNCJOBPARAM_T" BEFORE INSERT OR UPDATE ON MAXASYNCJOBPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXASYNCJOBPARAM_T" ENABLE
