-- TRIGGER: MAXIMO.MAXAPVALUES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXAPVALUES_T" BEFORE INSERT OR UPDATE ON MAXAPVALUES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXAPVALUES_T" ENABLE
