-- TRIGGER: MAXIMO.MAXASYNCJOB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXASYNCJOB_T" BEFORE INSERT OR UPDATE ON MAXASYNCJOB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXASYNCJOB_T" ENABLE
