-- TRIGGER: MAXIMO.MAXCONDDETAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXCONDDETAIL_T" BEFORE INSERT OR UPDATE ON MAXCONDDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXCONDDETAIL_T" ENABLE
