-- TRIGGER: MAXIMO.MAXCONTROLVALUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXCONTROLVALUE_T" BEFORE INSERT OR UPDATE ON MAXCONTROLVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXCONTROLVALUE_T" ENABLE
