-- TRIGGER: MAXIMO.MAXCOMPONENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXCOMPONENT_T" BEFORE INSERT OR UPDATE ON MAXCOMPONENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXCOMPONENT_T" ENABLE
