-- TRIGGER: MAXIMO.MAXDOMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXDOMAIN_T" BEFORE INSERT OR UPDATE ON MAXDOMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXDOMAIN_T" ENABLE
