-- TRIGGER: MAXIMO.MAXDOMAINLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXDOMAINLINK_T" BEFORE INSERT OR UPDATE ON MAXDOMAINLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXDOMAINLINK_T" ENABLE
