-- TRIGGER: MAXIMO.MAXDATAPREFIX_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXDATAPREFIX_T" BEFORE INSERT OR UPDATE ON MAXDATAPREFIX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXDATAPREFIX_T" ENABLE
