-- TRIGGER: MAXIMO.MAXDOMVALCOND_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXDOMVALCOND_T" BEFORE INSERT OR UPDATE ON MAXDOMVALCOND FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXDOMVALCOND_T" ENABLE
