-- TRIGGER: MAXIMO.MAXDYNAMICDOMLIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXDYNAMICDOMLIN_T" BEFORE INSERT OR UPDATE ON MAXDYNAMICDOMLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXDYNAMICDOMLIN_T" ENABLE
