-- TRIGGER: MAXIMO.MAXEXTIFACEIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTIFACEIN_T" BEFORE INSERT OR UPDATE ON MAXEXTIFACEIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTIFACEIN_T" ENABLE
