-- TRIGGER: MAXIMO.MAXEXTCTLVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTCTLVAL_T" BEFORE INSERT OR UPDATE ON MAXEXTCTLVAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTCTLVAL_T" ENABLE
