-- TRIGGER: MAXIMO.MAXEXTXREFVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTXREFVAL_T" BEFORE INSERT OR UPDATE ON MAXEXTXREFVAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTXREFVAL_T" ENABLE
