-- TRIGGER: MAXIMO.MAXEXTOVER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTOVER_T" BEFORE INSERT OR UPDATE ON MAXEXTOVER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTOVER_T" ENABLE
