-- TRIGGER: MAXIMO.MAXENDPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXENDPOINT_T" BEFORE INSERT OR UPDATE ON MAXENDPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXENDPOINT_T" ENABLE
