-- TRIGGER: MAXIMO.MAXEXTBOOLVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTBOOLVAL_T" BEFORE INSERT OR UPDATE ON MAXEXTBOOLVAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTBOOLVAL_T" ENABLE
