-- TRIGGER: MAXIMO.MAXEXTLISTVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTLISTVAL_T" BEFORE INSERT OR UPDATE ON MAXEXTLISTVAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTLISTVAL_T" ENABLE
