-- TRIGGER: MAXIMO.MAXEXTSYSTEM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTSYSTEM_T" BEFORE INSERT OR UPDATE ON MAXEXTSYSTEM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTSYSTEM_T" ENABLE
