-- TRIGGER: MAXIMO.MAXEXTIFACEOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXEXTIFACEOUT_T" BEFORE INSERT OR UPDATE ON MAXEXTIFACEOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXEXTIFACEOUT_T" ENABLE
