-- TRIGGER: MAXIMO.MAXENDPOINTDTL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXENDPOINTDTL_T" BEFORE INSERT OR UPDATE ON MAXENDPOINTDTL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXENDPOINTDTL_T" ENABLE
