-- TRIGGER: MAXIMO.MAXGRAPHRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXGRAPHRELATION_T" BEFORE INSERT OR UPDATE ON MAXGRAPHRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXGRAPHRELATION_T" ENABLE
