-- TRIGGER: MAXIMO.MAXGRAPHRELATTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXGRAPHRELATTR_T" BEFORE INSERT OR UPDATE ON MAXGRAPHRELATTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXGRAPHRELATTR_T" ENABLE
