-- TRIGGER: MAXIMO.MAXGRAPHQUERYATTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXGRAPHQUERYATTR_T" BEFORE INSERT OR UPDATE ON MAXGRAPHQUERYATTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXGRAPHQUERYATTR_T" ENABLE
