-- TRIGGER: MAXIMO.MAXHANDLER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXHANDLER_T" BEFORE INSERT OR UPDATE ON MAXHANDLER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXHANDLER_T" ENABLE
