-- TRIGGER: MAXIMO.MAXINTPOLICY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTPOLICY_T" BEFORE INSERT OR UPDATE ON MAXINTPOLICY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTPOLICY_T" ENABLE
