-- TRIGGER: MAXIMO.MAXIMPROP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIMPROP_T" BEFORE INSERT OR UPDATE ON MAXIMPROP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIMPROP_T" ENABLE
