-- TRIGGER: MAXIMO.MAXINTOBJCOLS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTOBJCOLS_T" BEFORE INSERT OR UPDATE ON MAXINTOBJCOLS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTOBJCOLS_T" ENABLE
