-- TRIGGER: MAXIMO.MAXINTERROREXTRAC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTERROREXTRAC_T" BEFORE INSERT OR UPDATE ON MAXINTERROREXTRACT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTERROREXTRAC_T" ENABLE
