-- TRIGGER: MAXIMO.MAXINTERROR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTERROR_T" BEFORE INSERT OR UPDATE ON MAXINTERROR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTERROR_T" ENABLE
