-- TRIGGER: MAXIMO.MAXIFACEIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEIN_T" BEFORE INSERT OR UPDATE ON MAXIFACEIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACEIN_T" ENABLE
