-- TRIGGER: MAXIMO.MAXINTMAPPING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTMAPPING_T" BEFORE INSERT OR UPDATE ON MAXINTMAPPING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTMAPPING_T" ENABLE
