-- TRIGGER: MAXIMO.MAXINTOBJDETAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTOBJDETAIL_T" BEFORE INSERT OR UPDATE ON MAXINTOBJDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTOBJDETAIL_T" ENABLE
