-- TRIGGER: MAXIMO.MAXINTOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTOBJECT_T" BEFORE INSERT OR UPDATE ON MAXINTOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTOBJECT_T" ENABLE
