-- TRIGGER: MAXIMO.MAXINTLISTENER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTLISTENER_T" BEFORE INSERT OR UPDATE ON MAXINTLISTENER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTLISTENER_T" ENABLE
