-- TRIGGER: MAXIMO.MAXINTMAPPINGDETA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTMAPPINGDETA_T" BEFORE INSERT OR UPDATE ON MAXINTMAPPINGDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTMAPPINGDETA_T" ENABLE
