-- TRIGGER: MAXIMO.MAXIFACEINDETAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEINDETAIL_T" BEFORE INSERT OR UPDATE ON MAXIFACEINDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACEINDETAIL_T" ENABLE
