-- TRIGGER: MAXIMO.MAXINTMSGTRKDTL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTMSGTRKDTL_T" BEFORE INSERT OR UPDATE ON MAXINTMSGTRKDTL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTMSGTRKDTL_T" ENABLE
