-- TRIGGER: MAXIMO.MAXINTPOLICYPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTPOLICYPARAM_T" BEFORE INSERT OR UPDATE ON MAXINTPOLICYPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTPOLICYPARAM_T" ENABLE
