-- TRIGGER: MAXIMO.MAXINTOBJALIAS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTOBJALIAS_T" BEFORE INSERT OR UPDATE ON MAXINTOBJALIAS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTOBJALIAS_T" ENABLE
