-- TRIGGER: MAXIMO.MAXIFACEINCNTL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEINCNTL_T" BEFORE INSERT OR UPDATE ON MAXIFACEINCNTL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACEINCNTL_T" ENABLE
