-- TRIGGER: MAXIMO.MAXIFACEEXPORT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEEXPORT_T" BEFORE INSERT OR UPDATE ON MAXIFACEEXPORT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXIFACEEXPORT_T" ENABLE
