-- TRIGGER: MAXIMO.MAXIFACEOUTCNTL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEOUTCNTL_T" BEFORE INSERT OR UPDATE ON MAXIFACEOUTCNTL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACEOUTCNTL_T" ENABLE
