-- TRIGGER: MAXIMO.MAXIFACECOND_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACECOND_T" BEFORE INSERT OR UPDATE ON MAXIFACECOND FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACECOND_T" ENABLE
