-- TRIGGER: MAXIMO.MAXIFACEOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEOUT_T" BEFORE INSERT OR UPDATE ON MAXIFACEOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACEOUT_T" ENABLE
