-- TRIGGER: MAXIMO.MAXIFACEPROC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACEPROC_T" BEFORE INSERT OR UPDATE ON MAXIFACEPROC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACEPROC_T" ENABLE
