-- TRIGGER: MAXIMO.MAXIFACECONTROL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACECONTROL_T" BEFORE INSERT OR UPDATE ON MAXIFACECONTROL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACECONTROL_T" ENABLE
