-- TRIGGER: MAXIMO.MAXIFACETYPEPROP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIFACETYPEPROP_T" BEFORE INSERT OR UPDATE ON MAXIFACETYPEPROP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIFACETYPEPROP_T" ENABLE
