-- TRIGGER: MAXIMO.MAXINTOBJAPP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTOBJAPP_T" BEFORE INSERT OR UPDATE ON MAXINTOBJAPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTOBJAPP_T" ENABLE
