-- TRIGGER: MAXIMO.MAXIM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXIM_T" BEFORE INSERT OR UPDATE ON MAXIM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXIM_T" ENABLE
