-- TRIGGER: MAXIMO.MAXINTERACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTERACTION_T" BEFORE INSERT OR UPDATE ON MAXINTERACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTERACTION_T" ENABLE
