-- TRIGGER: MAXIMO.MAXINTMSGTRK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTMSGTRK_T" BEFORE INSERT OR UPDATE ON MAXINTMSGTRK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTMSGTRK_T" ENABLE
