-- TRIGGER: MAXIMO.MAXINTERRORMSG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXINTERRORMSG_T" BEFORE INSERT OR UPDATE ON MAXINTERRORMSG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXINTERRORMSG_T" ENABLE
