-- TRIGGER: MAXIMO.MAXKAFKAOFFSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXKAFKAOFFSET_T" BEFORE INSERT OR UPDATE ON MAXKAFKAOFFSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXKAFKAOFFSET_T" ENABLE
