-- TRIGGER: MAXIMO.MAXLICENSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICENSE_T" BEFORE INSERT OR UPDATE ON MAXLICENSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICENSE_T" ENABLE
