-- TRIGGER: MAXIMO.MAXLICUSGCONCURT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICUSGCONCURT_T" BEFORE INSERT OR UPDATE ON MAXLICUSGCONCURT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICUSGCONCURT_T" ENABLE
