-- TRIGGER: MAXIMO.MAXLOGMSGTOOLBAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLOGMSGTOOLBAR_T" BEFORE INSERT OR UPDATE ON MAXLOGMSGTOOLBAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLOGMSGTOOLBAR_T" ENABLE
