-- TRIGGER: MAXIMO.MAXLECONTEXT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLECONTEXT_T" BEFORE INSERT OR UPDATE ON MAXLECONTEXT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLECONTEXT_T" ENABLE
