-- TRIGGER: MAXIMO.MAXLICUSGSMRY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICUSGSMRY_T" BEFORE INSERT OR UPDATE ON MAXLICUSGSMRY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICUSGSMRY_T" ENABLE
