-- TRIGGER: MAXIMO.MAXLICSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICSTATUS_T" BEFORE INSERT OR UPDATE ON MAXLICSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICSTATUS_T" ENABLE
