-- TRIGGER: MAXIMO.MAXLISTOVERVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLISTOVERVAL_T" BEFORE INSERT OR UPDATE ON MAXLISTOVERVAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLISTOVERVAL_T" ENABLE
