-- TRIGGER: MAXIMO.MAXLICTYPESTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICTYPESTATUS_T" BEFORE INSERT OR UPDATE ON MAXLICTYPESTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICTYPESTATUS_T" ENABLE
