-- TRIGGER: MAXIMO.MAXLICAVGROUPMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICAVGROUPMAP_T" BEFORE INSERT OR UPDATE ON MAXLICAVGROUPMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICAVGROUPMAP_T" ENABLE
