-- TRIGGER: MAXIMO.MAXLICPURCHDET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICPURCHDET_T" BEFORE INSERT OR UPDATE ON MAXLICPURCHDET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICPURCHDET_T" ENABLE
