-- TRIGGER: MAXIMO.MAXLICSIGFLAGLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICSIGFLAGLINK_T" BEFORE INSERT OR UPDATE ON MAXLICSIGFLAGLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICSIGFLAGLINK_T" ENABLE
