-- TRIGGER: MAXIMO.MAXLICINCLADDON_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICINCLADDON_T" BEFORE INSERT OR UPDATE ON MAXLICINCLADDON FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICINCLADDON_T" ENABLE
