-- TRIGGER: MAXIMO.MAXLICAPPMODEXT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICAPPMODEXT_T" BEFORE INSERT OR UPDATE ON MAXLICAPPMODEXT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICAPPMODEXT_T" ENABLE
