-- TRIGGER: MAXIMO.MAXLICUSERASC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICUSERASC_T" BEFORE INSERT OR UPDATE ON MAXLICUSERASC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICUSERASC_T" ENABLE
