-- TRIGGER: MAXIMO.MAXLICRVU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICRVU_T" BEFORE INSERT OR UPDATE ON MAXLICRVU FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICRVU_T" ENABLE
