-- TRIGGER: MAXIMO.MAXLICRVUUSAGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICRVUUSAGE_T" BEFORE INSERT OR UPDATE ON MAXLICRVUUSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICRVUUSAGE_T" ENABLE
