-- TRIGGER: MAXIMO.MAXLICSELFSRVAPPS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICSELFSRVAPPS_T" BEFORE INSERT OR UPDATE ON MAXLICSELFSRVAPPS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICSELFSRVAPPS_T" ENABLE
