-- TRIGGER: MAXIMO.MAXLICPRODLST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICPRODLST_T" BEFORE INSERT OR UPDATE ON MAXLICPRODLST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICPRODLST_T" ENABLE
