-- TRIGGER: MAXIMO.MAXLICAVTYPES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICAVTYPES_T" BEFORE INSERT OR UPDATE ON MAXLICAVTYPES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICAVTYPES_T" ENABLE
