-- TRIGGER: MAXIMO.MAXLAUNCHENTRY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLAUNCHENTRY_T" BEFORE INSERT OR UPDATE ON MAXLAUNCHENTRY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLAUNCHENTRY_T" ENABLE
