-- TRIGGER: MAXIMO.MAXLICAPPS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICAPPS_T" BEFORE INSERT OR UPDATE ON MAXLICAPPS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICAPPS_T" ENABLE
