-- TRIGGER: MAXIMO.MAXLICUSGVAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICUSGVAR_T" BEFORE INSERT OR UPDATE ON MAXLICUSGVAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICUSGVAR_T" ENABLE
