-- TRIGGER: MAXIMO.MAXLICAPPACCESS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICAPPACCESS_T" BEFORE INSERT OR UPDATE ON MAXLICAPPACCESS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICAPPACCESS_T" ENABLE
