-- TRIGGER: MAXIMO.MAXLICPRDKEYLIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICPRDKEYLIST_T" BEFORE INSERT OR UPDATE ON MAXLICPRDKEYLIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLICPRDKEYLIST_T" ENABLE
