-- TRIGGER: MAXIMO.MAXLICCONCITVLUSA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLICCONCITVLUSA_T" BEFORE INSERT OR UPDATE ON MAXLICCONCITVLUSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXLICCONCITVLUSA_T" ENABLE
