-- TRIGGER: MAXIMO.MAXLOOKUPMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXLOOKUPMAP_T" BEFORE INSERT OR UPDATE ON MAXLOOKUPMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXLOOKUPMAP_T" ENABLE
