-- TRIGGER: MAXIMO.MAXMODULES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXMODULES_T" BEFORE INSERT OR UPDATE ON MAXMODULES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXMODULES_T" ENABLE
