-- TRIGGER: MAXIMO.MAXMENU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXMENU_T" BEFORE INSERT OR UPDATE ON MAXMENU FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXMENU_T" ENABLE
