-- TRIGGER: MAXIMO.MAXMOBILESCHEMA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXMOBILESCHEMA_T" BEFORE INSERT OR UPDATE ON MAXMOBILESCHEMA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXMOBILESCHEMA_T" ENABLE
