-- TRIGGER: MAXIMO.MAXOBJECTCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXOBJECTCFG_T" BEFORE INSERT OR UPDATE ON MAXOBJECTCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXOBJECTCFG_T" ENABLE
