-- TRIGGER: MAXIMO.MAXOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXOBJECT_T" BEFORE INSERT OR UPDATE ON MAXOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXOBJECT_T" ENABLE
