-- TRIGGER: MAXIMO.MAXOAUTHCLIENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXOAUTHCLIENT_T" BEFORE INSERT OR UPDATE ON MAXOAUTHCLIENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXOAUTHCLIENT_T" ENABLE
