-- TRIGGER: MAXIMO.MAXPROPVALUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPROPVALUE_T" BEFORE INSERT OR UPDATE ON MAXPROPVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXPROPVALUE_T" ENABLE
