-- TRIGGER: MAXIMO.MAXPUSHPROVIDERDE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPUSHPROVIDERDE_T" BEFORE INSERT OR UPDATE ON MAXPUSHPROVIDERDEVTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXPUSHPROVIDERDE_T" ENABLE
