-- TRIGGER: MAXIMO.MAXPUSHPROVIDER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPUSHPROVIDER_T" BEFORE INSERT OR UPDATE ON MAXPUSHPROVIDER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXPUSHPROVIDER_T" ENABLE
