-- TRIGGER: MAXIMO.MAXPROCCOLS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPROCCOLS_T" BEFORE INSERT OR UPDATE ON MAXPROCCOLS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXPROCCOLS_T" ENABLE
