-- TRIGGER: MAXIMO.MAXPROP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPROP_T" BEFORE INSERT OR UPDATE ON MAXPROP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXPROP_T" ENABLE
