-- TRIGGER: MAXIMO.MAXPRESENTATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPRESENTATION_T" BEFORE INSERT OR UPDATE ON MAXPRESENTATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXPRESENTATION_T" ENABLE
