-- TRIGGER: MAXIMO.MAXPUSHDEVTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXPUSHDEVTYPE_T" BEFORE INSERT OR UPDATE ON MAXPUSHDEVTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXPUSHDEVTYPE_T" ENABLE
