-- TRIGGER: MAXIMO.MAXQUEUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXQUEUE_T" BEFORE INSERT OR UPDATE ON MAXQUEUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXQUEUE_T" ENABLE
