-- TRIGGER: MAXIMO.MAXROWSTAMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXROWSTAMP_T" BEFORE INSERT OR UPDATE ON MAXROWSTAMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXROWSTAMP_T" ENABLE
