-- TRIGGER: MAXIMO.MAXROLE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXROLE_T" BEFORE INSERT OR UPDATE ON MAXROLE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXROLE_T" ENABLE
