-- TRIGGER: MAXIMO.MAXREPLACEPROC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXREPLACEPROC_T" BEFORE INSERT OR UPDATE ON MAXREPLACEPROC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXREPLACEPROC_T" ENABLE
