-- TRIGGER: MAXIMO.MAXRECORDLOCK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXRECORDLOCK_T" BEFORE INSERT OR UPDATE ON MAXRECORDLOCK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXRECORDLOCK_T" ENABLE
