-- TRIGGER: MAXIMO.MAXSERVICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXSERVICE_T" BEFORE INSERT OR UPDATE ON MAXSERVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXSERVICE_T" ENABLE
