-- TRIGGER: MAXIMO.MAXSYSKEYS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXSYSKEYS_T" BEFORE INSERT OR UPDATE ON MAXSYSKEYS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXSYSKEYS_T" ENABLE
