-- TRIGGER: MAXIMO.MAXSERVSECURITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXSERVSECURITY_T" BEFORE INSERT OR UPDATE ON MAXSERVSECURITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXSERVSECURITY_T" ENABLE
