-- TRIGGER: MAXIMO.MAXSESSION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXSESSION_T" BEFORE INSERT OR UPDATE ON MAXSESSION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXSESSION_T" ENABLE
