-- TRIGGER: MAXIMO.MAXSYSINDEXES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXSYSINDEXES_T" BEFORE INSERT OR UPDATE ON MAXSYSINDEXES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXSYSINDEXES_T" ENABLE
