-- TRIGGER: MAXIMO.MAXSEQUENCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXSEQUENCE_T" BEFORE INSERT OR UPDATE ON MAXSEQUENCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXSEQUENCE_T" ENABLE
