-- TRIGGER: MAXIMO.MAXTOKEN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTOKEN_T" BEFORE INSERT OR UPDATE ON MAXTOKEN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTOKEN_T" ENABLE
