-- TRIGGER: MAXIMO.MAXTHREADLOGGER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTHREADLOGGER_T" BEFORE INSERT OR UPDATE ON MAXTHREADLOGGER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTHREADLOGGER_T" ENABLE
