-- TRIGGER: MAXIMO.MAXTESTFIX_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTESTFIX_T" BEFORE INSERT OR UPDATE ON MAXTESTFIX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTESTFIX_T" ENABLE
