-- TRIGGER: MAXIMO.MAXTABLECFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTABLECFG_T" BEFORE INSERT OR UPDATE ON MAXTABLECFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTABLECFG_T" ENABLE
