-- TRIGGER: MAXIMO.MAXTABLE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTABLE_T" BEFORE INSERT OR UPDATE ON MAXTABLE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTABLE_T" ENABLE
