-- TRIGGER: MAXIMO.MAXTHREADLOGGERDE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTHREADLOGGERDE_T" BEFORE INSERT OR UPDATE ON MAXTHREADLOGGERDET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTHREADLOGGERDE_T" ENABLE
