-- TRIGGER: MAXIMO.MAXTRANSFORMPROC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXTRANSFORMPROC_T" BEFORE INSERT OR UPDATE ON MAXTRANSFORMPROC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXTRANSFORMPROC_T" ENABLE
