-- TRIGGER: MAXIMO.MAXUSERAPPLOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXUSERAPPLOG_T" BEFORE INSERT OR UPDATE ON MAXUSERAPPLOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXUSERAPPLOG_T" ENABLE
