-- TRIGGER: MAXIMO.MAXUSER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXUSER_T" BEFORE INSERT OR UPDATE ON MAXUSER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXUSER_T" ENABLE
