-- TRIGGER: MAXIMO.MAXUSERSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXUSERSTATUS_T" BEFORE INSERT OR UPDATE ON MAXUSERSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXUSERSTATUS_T" ENABLE
