-- TRIGGER: MAXIMO.MAXUSERNPS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXUSERNPS_T" BEFORE INSERT OR UPDATE ON MAXUSERNPS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXUSERNPS_T" ENABLE
