-- TRIGGER: MAXIMO.MAXVIEWCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXVIEWCFG_T" BEFORE INSERT OR UPDATE ON MAXVIEWCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXVIEWCFG_T" ENABLE
