-- TRIGGER: MAXIMO.MAXVIEWCOLUMNCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXVIEWCOLUMNCFG_T" BEFORE INSERT OR UPDATE ON MAXVIEWCOLUMNCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXVIEWCOLUMNCFG_T" ENABLE
