-- TRIGGER: MAXIMO.MAXVIEWCOLUMN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXVIEWCOLUMN_T" BEFORE INSERT OR UPDATE ON MAXVIEWCOLUMN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXVIEWCOLUMN_T" ENABLE
