-- TRIGGER: MAXIMO.MAXVIEW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXVIEW_T" BEFORE INSERT OR UPDATE ON MAXVIEW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXVIEW_T" ENABLE
