-- TRIGGER: MAXIMO.MAXWORKCENTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXWORKCENTER_T" BEFORE INSERT OR UPDATE ON MAXWORKCENTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXWORKCENTER_T" ENABLE
