-- TRIGGER: MAXIMO.MAXWSREGISTRY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXWSREGISTRY_T" BEFORE INSERT OR UPDATE ON MAXWSREGISTRY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXWSREGISTRY_T" ENABLE
