-- TRIGGER: MAXIMO.MAXWORKCENTERFILE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXWORKCENTERFILE_T" BEFORE INSERT OR UPDATE ON MAXWORKCENTERFILES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MAXWORKCENTERFILE_T" ENABLE
