-- TRIGGER: MAXIMO.MAXXREFOVERVAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MAXXREFOVERVAL_T" BEFORE INSERT OR UPDATE ON MAXXREFOVERVAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MAXXREFOVERVAL_T" ENABLE
