-- TRIGGER: MAXIMO.MEA_DUMMY_TABLE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MEA_DUMMY_TABLE_T" BEFORE INSERT OR UPDATE ON MEA_DUMMY_TABLE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MEA_DUMMY_TABLE_T" ENABLE
