-- TRIGGER: MAXIMO.MEASUREUNIT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MEASUREUNIT_T" BEFORE INSERT OR UPDATE ON MEASUREUNIT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MEASUREUNIT_T" ENABLE
