-- TRIGGER: MAXIMO.MEASUREMENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MEASUREMENT_T" BEFORE INSERT OR UPDATE ON MEASUREMENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MEASUREMENT_T" ENABLE
