-- TRIGGER: MAXIMO.MEASUREPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MEASUREPOINT_T" BEFORE INSERT OR UPDATE ON MEASUREPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MEASUREPOINT_T" ENABLE
