-- TRIGGER: MAXIMO.MEASUREPOINTFORMU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MEASUREPOINTFORMU_T" BEFORE INSERT OR UPDATE ON MEASUREPOINTFORMULA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MEASUREPOINTFORMU_T" ENABLE
