-- TRIGGER: MAXIMO.METERGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."METERGROUP_T" BEFORE INSERT OR UPDATE ON METERGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."METERGROUP_T" ENABLE
