-- TRIGGER: MAXIMO.METERINGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."METERINGROUP_T" BEFORE INSERT OR UPDATE ON METERINGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."METERINGROUP_T" ENABLE
