-- TRIGGER: MAXIMO.METERREADING_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."METERREADING_T" BEFORE INSERT OR UPDATE ON METERREADING FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."METERREADING_T" ENABLE
