-- TRIGGER: MAXIMO.METER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."METER_T" BEFORE INSERT OR UPDATE ON METER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."METER_T" ENABLE
