-- TRIGGER: MAXIMO.METHODATTRMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."METHODATTRMAP_T" BEFORE INSERT OR UPDATE ON METHODATTRMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."METHODATTRMAP_T" ENABLE
