-- TRIGGER: MAXIMO.MFMAILWFNODECFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILWFNODECFG_T" BEFORE INSERT OR UPDATE ON MFMAILWFNODECFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILWFNODECFG_T" ENABLE
