-- TRIGGER: MAXIMO.MFMAILSTVALCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILSTVALCFG_T" BEFORE INSERT OR UPDATE ON MFMAILSTVALCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILSTVALCFG_T" ENABLE
