-- TRIGGER: MAXIMO.MFMAILWF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILWF_T" BEFORE INSERT OR UPDATE ON MFMAILWF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILWF_T" ENABLE
