-- TRIGGER: MAXIMO.MFMAILWFVALCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILWFVALCFG_T" BEFORE INSERT OR UPDATE ON MFMAILWFVALCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILWFVALCFG_T" ENABLE
