-- TRIGGER: MAXIMO.MFMAILTRACK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILTRACK_T" BEFORE INSERT OR UPDATE ON MFMAILTRACK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILTRACK_T" ENABLE
