-- TRIGGER: MAXIMO.MFMAILCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILCFG_T" BEFORE INSERT OR UPDATE ON MFMAILCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILCFG_T" ENABLE
