-- TRIGGER: MAXIMO.MFMAILSTCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MFMAILSTCFG_T" BEFORE INSERT OR UPDATE ON MFMAILSTCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MFMAILSTCFG_T" ENABLE
