-- TRIGGER: MAXIMO.MOBILEDBCROPAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MOBILEDBCROPAR_T" BEFORE INSERT OR UPDATE ON MOBILEDBCROPAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MOBILEDBCROPAR_T" ENABLE
