-- TRIGGER: MAXIMO.MODAVAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MODAVAIL_T" BEFORE INSERT OR UPDATE ON MODAVAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MODAVAIL_T" ENABLE
