-- TRIGGER: MAXIMO.MODELATTRMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MODELATTRMAP_T" BEFORE INSERT OR UPDATE ON MODELATTRMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MODELATTRMAP_T" ENABLE
