-- TRIGGER: MAXIMO.MR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MR_T" BEFORE INSERT OR UPDATE ON MR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MR_T" ENABLE
