-- TRIGGER: MAXIMO.MRCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MRCOST_T" BEFORE INSERT OR UPDATE ON MRCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MRCOST_T" ENABLE
