-- TRIGGER: MAXIMO.MRLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MRLINE_T" BEFORE INSERT OR UPDATE ON MRLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MRLINE_T" ENABLE
