-- TRIGGER: MAXIMO.MRSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MRSTATUS_T" BEFORE INSERT OR UPDATE ON MRSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MRSTATUS_T" ENABLE
