-- TRIGGER: MAXIMO.MSGHUBPROVIDER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MSGHUBPROVIDER_T" BEFORE INSERT OR UPDATE ON MSGHUBPROVIDER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MSGHUBPROVIDER_T" ENABLE
