-- TRIGGER: MAXIMO.MSGHUBPROVIDERTYP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MSGHUBPROVIDERTYP_T" BEFORE INSERT OR UPDATE ON MSGHUBPROVIDERTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MSGHUBPROVIDERTYP_T" ENABLE
