-- TRIGGER: MAXIMO.MSGHUBPROVIDERCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MSGHUBPROVIDERCFG_T" BEFORE INSERT OR UPDATE ON MSGHUBPROVIDERCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MSGHUBPROVIDERCFG_T" ENABLE
