-- TRIGGER: MAXIMO.MULTIASSETLOCCIPR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MULTIASSETLOCCIPR_T" BEFORE INSERT OR UPDATE ON MULTIASSETLOCCIPR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MULTIASSETLOCCIPR_T" ENABLE
