-- TRIGGER: MAXIMO.MXCOLLAB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MXCOLLAB_T" BEFORE INSERT OR UPDATE ON MXCOLLAB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MXCOLLAB_T" ENABLE
