-- TRIGGER: MAXIMO.MXCOLLABREF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MXCOLLABREF_T" BEFORE INSERT OR UPDATE ON MXCOLLABREF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MXCOLLABREF_T" ENABLE
