-- TRIGGER: MAXIMO.MXODMAPP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MXODMAPP_T" BEFORE INSERT OR UPDATE ON MXODMAPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MXODMAPP_T" ENABLE
