-- TRIGGER: MAXIMO.MXODMAPPPKG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MXODMAPPPKG_T" BEFORE INSERT OR UPDATE ON MXODMAPPPKG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."MXODMAPPPKG_T" ENABLE
