-- TRIGGER: MAXIMO.MXTOUR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."MXTOUR_T" BEFORE INSERT OR UPDATE ON MXTOUR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."MXTOUR_T" ENABLE
