-- TRIGGER: MAXIMO.NAMEDUSERS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."NAMEDUSERS_T" BEFORE INSERT OR UPDATE ON NAMEDUSERS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."NAMEDUSERS_T" ENABLE
