-- TRIGGER: MAXIMO.NOTFMSGTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."NOTFMSGTEMPLATE_T" BEFORE INSERT OR UPDATE ON NOTFMSGTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."NOTFMSGTEMPLATE_T" ENABLE
