-- TRIGGER: MAXIMO.NUMERICDOMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."NUMERICDOMAIN_T" BEFORE INSERT OR UPDATE ON NUMERICDOMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."NUMERICDOMAIN_T" ENABLE
