-- TRIGGER: MAXIMO.NUMRANGEDOMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."NUMRANGEDOMAIN_T" BEFORE INSERT OR UPDATE ON NUMRANGEDOMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."NUMRANGEDOMAIN_T" ENABLE
