-- TRIGGER: MAXIMO.OBJECTFORMULA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OBJECTFORMULA_T" BEFORE INSERT OR UPDATE ON OBJECTFORMULA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OBJECTFORMULA_T" ENABLE
