-- TRIGGER: MAXIMO.OBJECTFORMULACOND_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OBJECTFORMULACOND_T" BEFORE INSERT OR UPDATE ON OBJECTFORMULACOND FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."OBJECTFORMULACOND_T" ENABLE
