-- TRIGGER: MAXIMO.OFFLINEGEODATABAS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OFFLINEGEODATABAS_T" BEFORE INSERT OR UPDATE ON OFFLINEGEODATABASE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."OFFLINEGEODATABAS_T" ENABLE
