-- TRIGGER: MAXIMO.OFFLINEAREAPACKAG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OFFLINEAREAPACKAG_T" BEFORE INSERT OR UPDATE ON OFFLINEAREAPACKAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."OFFLINEAREAPACKAG_T" ENABLE
