-- TRIGGER: MAXIMO.OMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OMP_T" BEFORE INSERT OR UPDATE ON OMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OMP_T" ENABLE
