-- TRIGGER: MAXIMO.OMPCIRLN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OMPCIRLN_T" BEFORE INSERT OR UPDATE ON OMPCIRLN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OMPCIRLN_T" ENABLE
