-- TRIGGER: MAXIMO.OMPIMLMORLN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OMPIMLMORLN_T" BEFORE INSERT OR UPDATE ON OMPIMLMORLN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OMPIMLMORLN_T" ENABLE
