-- TRIGGER: MAXIMO.OMPIMRLN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OMPIMRLN_T" BEFORE INSERT OR UPDATE ON OMPIMRLN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OMPIMRLN_T" ENABLE
