-- TRIGGER: MAXIMO.ORGANIZATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ORGANIZATION_T" BEFORE INSERT OR UPDATE ON ORGANIZATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ORGANIZATION_T" ENABLE
