-- TRIGGER: MAXIMO.OSACCESSLOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSACCESSLOG_T" BEFORE INSERT OR UPDATE ON OSACCESSLOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSACCESSLOG_T" ENABLE
