-- TRIGGER: MAXIMO.OSEVENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSEVENT_T" BEFORE INSERT OR UPDATE ON OSEVENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSEVENT_T" ENABLE
