-- TRIGGER: MAXIMO.OSEVENTCONDITION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSEVENTCONDITION_T" BEFORE INSERT OR UPDATE ON OSEVENTCONDITION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSEVENTCONDITION_T" ENABLE
