-- TRIGGER: MAXIMO.OSLCTRANSACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCTRANSACTION_T" BEFORE INSERT OR UPDATE ON OSLCTRANSACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCTRANSACTION_T" ENABLE
