-- TRIGGER: MAXIMO.OSLCPROVIDER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCPROVIDER_T" BEFORE INSERT OR UPDATE ON OSLCPROVIDER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCPROVIDER_T" ENABLE
