-- TRIGGER: MAXIMO.OSLCDOMAIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCDOMAIN_T" BEFORE INSERT OR UPDATE ON OSLCDOMAIN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCDOMAIN_T" ENABLE
