-- TRIGGER: MAXIMO.OSLCINTGRPMEMBERS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCINTGRPMEMBERS_T" BEFORE INSERT OR UPDATE ON OSLCINTGRPMEMBERS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCINTGRPMEMBERS_T" ENABLE
