-- TRIGGER: MAXIMO.OSLCINTGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCINTGROUP_T" BEFORE INSERT OR UPDATE ON OSLCINTGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCINTGROUP_T" ENABLE
