-- TRIGGER: MAXIMO.OSLCCOMMONPROPS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCCOMMONPROPS_T" BEFORE INSERT OR UPDATE ON OSLCCOMMONPROPS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCCOMMONPROPS_T" ENABLE
