-- TRIGGER: MAXIMO.OSLCQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCQUERY_T" BEFORE INSERT OR UPDATE ON OSLCQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCQUERY_T" ENABLE
