-- TRIGGER: MAXIMO.OSLCRESOURCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCRESOURCE_T" BEFORE INSERT OR UPDATE ON OSLCRESOURCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCRESOURCE_T" ENABLE
