-- TRIGGER: MAXIMO.OSLCSPDEFN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCSPDEFN_T" BEFORE INSERT OR UPDATE ON OSLCSPDEFN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCSPDEFN_T" ENABLE
