-- TRIGGER: MAXIMO.OSLCINTQUERYPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCINTQUERYPARAM_T" BEFORE INSERT OR UPDATE ON OSLCINTQUERYPARAMS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCINTQUERYPARAM_T" ENABLE
