-- TRIGGER: MAXIMO.OSLCRESOURCETYPES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCRESOURCETYPES_T" BEFORE INSERT OR UPDATE ON OSLCRESOURCETYPES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCRESOURCETYPES_T" ENABLE
