-- TRIGGER: MAXIMO.OSLCINTERACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCINTERACTION_T" BEFORE INSERT OR UPDATE ON OSLCINTERACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCINTERACTION_T" ENABLE
