-- TRIGGER: MAXIMO.OSLCBUSRES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCBUSRES_T" BEFORE INSERT OR UPDATE ON OSLCBUSRES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCBUSRES_T" ENABLE
