-- TRIGGER: MAXIMO.OSLCNSPREFIX_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCNSPREFIX_T" BEFORE INSERT OR UPDATE ON OSLCNSPREFIX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCNSPREFIX_T" ENABLE
