-- TRIGGER: MAXIMO.OSLCINTQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCINTQUERY_T" BEFORE INSERT OR UPDATE ON OSLCINTQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCINTQUERY_T" ENABLE
