-- TRIGGER: MAXIMO.OSLCRESOURCEDETAI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSLCRESOURCEDETAI_T" BEFORE INSERT OR UPDATE ON OSLCRESOURCEDETAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSLCRESOURCEDETAI_T" ENABLE
