-- TRIGGER: MAXIMO.OSOSLCMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSOSLCMAP_T" BEFORE INSERT OR UPDATE ON OSOSLCMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSOSLCMAP_T" ENABLE
