-- TRIGGER: MAXIMO.OSOSLCACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSOSLCACTION_T" BEFORE INSERT OR UPDATE ON OSOSLCACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSOSLCACTION_T" ENABLE
