-- TRIGGER: MAXIMO.OSUSERSUBSCRIPTIO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSUSERSUBSCRIPTIO_T" BEFORE INSERT OR UPDATE ON OSUSERSUBSCRIPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSUSERSUBSCRIPTIO_T" ENABLE
