-- TRIGGER: MAXIMO.OSUSED_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSUSED_T" BEFORE INSERT OR UPDATE ON OSUSED FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."OSUSED_T" ENABLE
