-- TRIGGER: MAXIMO.OSUSERNOTIFICATIO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."OSUSERNOTIFICATIO_T" BEFORE INSERT OR UPDATE ON OSUSERNOTIFICATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."OSUSERNOTIFICATIO_T" ENABLE
