-- TRIGGER: MAXIMO.PALETTEITEM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PALETTEITEM_T" BEFORE INSERT OR UPDATE ON PALETTEITEM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PALETTEITEM_T" ENABLE
