-- TRIGGER: MAXIMO.PASSWORDHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PASSWORDHISTORY_T" BEFORE INSERT OR UPDATE ON PASSWORDHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PASSWORDHISTORY_T" ENABLE
