-- TRIGGER: MAXIMO.PDSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PDSPEC_T" BEFORE INSERT OR UPDATE ON PDSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PDSPEC_T" ENABLE
