-- TRIGGER: MAXIMO.PERSONSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSONSTATUS_T" BEFORE INSERT OR UPDATE ON PERSONSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PERSONSTATUS_T" ENABLE
