-- TRIGGER: MAXIMO.PERSON_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSON_T" BEFORE INSERT OR UPDATE ON PERSON FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PERSON_T" ENABLE
