-- TRIGGER: MAXIMO.PERSONCAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSONCAL_T" BEFORE INSERT OR UPDATE ON PERSONCAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PERSONCAL_T" ENABLE
