-- TRIGGER: MAXIMO.PERSONDEFAULTAPP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSONDEFAULTAPP_T" BEFORE INSERT OR UPDATE ON PERSONDEFAULTAPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PERSONDEFAULTAPP_T" ENABLE
