-- TRIGGER: MAXIMO.PERSONANCESTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSONANCESTOR_T" BEFORE INSERT OR UPDATE ON PERSONANCESTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PERSONANCESTOR_T" ENABLE
