-- TRIGGER: MAXIMO.PERSONGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSONGROUP_T" BEFORE INSERT OR UPDATE ON PERSONGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PERSONGROUP_T" ENABLE
