-- TRIGGER: MAXIMO.PERSONGROUPTEAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PERSONGROUPTEAM_T" BEFORE INSERT OR UPDATE ON PERSONGROUPTEAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PERSONGROUPTEAM_T" ENABLE
