-- TRIGGER: MAXIMO.PLUSCTPMASTERPM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPMASTERPM_T" BEFORE INSERT OR UPDATE ON PLUSCTPMASTERPM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPMASTERPM_T" ENABLE
