-- TRIGGER: MAXIMO.PLUSCTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTEMPLATE_T" BEFORE INSERT OR UPDATE ON PLUSCTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTEMPLATE_T" ENABLE
