-- TRIGGER: MAXIMO.PLUSSMAPSERVICELA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSSMAPSERVICELA_T" BEFORE INSERT OR UPDATE ON PLUSSMAPSERVICELAYER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSSMAPSERVICELA_T" ENABLE
