-- TRIGGER: MAXIMO.PLUSCTPDATASHEET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPDATASHEET_T" BEFORE INSERT OR UPDATE ON PLUSCTPDATASHEET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPDATASHEET_T" ENABLE
