-- TRIGGER: MAXIMO.PLUSSGISFEATURE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSSGISFEATURE_T" BEFORE INSERT OR UPDATE ON PLUSSGISFEATURE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSSGISFEATURE_T" ENABLE
