-- TRIGGER: MAXIMO.PLUSCTPSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPSPEC_T" BEFORE INSERT OR UPDATE ON PLUSCTPSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPSPEC_T" ENABLE
