-- TRIGGER: MAXIMO.PLUSCASSETSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCASSETSTATUS_T" BEFORE INSERT OR UPDATE ON PLUSCASSETSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCASSETSTATUS_T" ENABLE
