-- TRIGGER: MAXIMO.PLUSSTOOLPERSISTE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSSTOOLPERSISTE_T" BEFORE INSERT OR UPDATE ON PLUSSTOOLPERSISTENCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSSTOOLPERSISTE_T" ENABLE
