-- TRIGGER: MAXIMO.PLUSCWODSINSTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCWODSINSTR_T" BEFORE INSERT OR UPDATE ON PLUSCWODSINSTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCWODSINSTR_T" ENABLE
