-- TRIGGER: MAXIMO.PLUSSFEATURECL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSSFEATURECL_T" BEFORE INSERT OR UPDATE ON PLUSSFEATURECL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSSFEATURECL_T" ENABLE
