-- TRIGGER: MAXIMO.PLUSCDSCONFIG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCDSCONFIG_T" BEFORE INSERT OR UPDATE ON PLUSCDSCONFIG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCDSCONFIG_T" ENABLE
