-- TRIGGER: MAXIMO.PLUSCWODSPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCWODSPOINT_T" BEFORE INSERT OR UPDATE ON PLUSCWODSPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCWODSPOINT_T" ENABLE
