-- TRIGGER: MAXIMO.PLUSCTPHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPHISTORY_T" BEFORE INSERT OR UPDATE ON PLUSCTPHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPHISTORY_T" ENABLE
