-- TRIGGER: MAXIMO.PLUSCTPASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPASSET_T" BEFORE INSERT OR UPDATE ON PLUSCTPASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPASSET_T" ENABLE
