-- TRIGGER: MAXIMO.PLUSCDSASSETLIN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCDSASSETLIN_T" BEFORE INSERT OR UPDATE ON PLUSCDSASSETLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCDSASSETLIN_T" ENABLE
