-- TRIGGER: MAXIMO.PLUSCJPDATASHEE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCJPDATASHEE_T" BEFORE INSERT OR UPDATE ON PLUSCJPDATASHEET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCJPDATASHEE_T" ENABLE
