-- TRIGGER: MAXIMO.PLUSCWODS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCWODS_T" BEFORE INSERT OR UPDATE ON PLUSCWODS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCWODS_T" ENABLE
