-- TRIGGER: MAXIMO.PLUSCTPMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPMETER_T" BEFORE INSERT OR UPDATE ON PLUSCTPMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPMETER_T" ENABLE
