-- TRIGGER: MAXIMO.PLUSCDSINSTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCDSINSTR_T" BEFORE INSERT OR UPDATE ON PLUSCDSINSTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCDSINSTR_T" ENABLE
