-- TRIGGER: MAXIMO.PLUSCTPSPAREPART_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCTPSPAREPART_T" BEFORE INSERT OR UPDATE ON PLUSCTPSPAREPART FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCTPSPAREPART_T" ENABLE
