-- TRIGGER: MAXIMO.PLUSSGEOCODESERVI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSSGEOCODESERVI_T" BEFORE INSERT OR UPDATE ON PLUSSGEOCODESERVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSSGEOCODESERVI_T" ENABLE
