-- TRIGGER: MAXIMO.PLUSCWODSANYWPST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCWODSANYWPST_T" BEFORE INSERT OR UPDATE ON PLUSCWODSANYWPST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSCWODSANYWPST_T" ENABLE
