-- TRIGGER: MAXIMO.PLUSCJPSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCJPSTATUS_T" BEFORE INSERT OR UPDATE ON PLUSCJPSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCJPSTATUS_T" ENABLE
