-- TRIGGER: MAXIMO.PLUSSSPATIALREFER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSSSPATIALREFER_T" BEFORE INSERT OR UPDATE ON PLUSSSPATIALREFERENCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PLUSSSPATIALREFER_T" ENABLE
