-- TRIGGER: MAXIMO.PLUSCDSPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCDSPOINT_T" BEFORE INSERT OR UPDATE ON PLUSCDSPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCDSPOINT_T" ENABLE
