-- TRIGGER: MAXIMO.PLUSCPMEXTDATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PLUSCPMEXTDATE_T" BEFORE INSERT OR UPDATE ON PLUSCPMEXTDATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PLUSCPMEXTDATE_T" ENABLE
