-- TRIGGER: MAXIMO.PM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PM_T" BEFORE INSERT OR UPDATE ON PM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PM_T" ENABLE
