-- TRIGGER: MAXIMO.PMFORECAST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMFORECAST_T" BEFORE INSERT OR UPDATE ON PMFORECAST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMFORECAST_T" ENABLE
