-- TRIGGER: MAXIMO.PMFORECASTLABOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMFORECASTLABOR_T" BEFORE INSERT OR UPDATE ON PMFORECASTLABOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMFORECASTLABOR_T" ENABLE
