-- TRIGGER: MAXIMO.PMFORECASTMATERIA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMFORECASTMATERIA_T" BEFORE INSERT OR UPDATE ON PMFORECASTMATERIAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMFORECASTMATERIA_T" ENABLE
