-- TRIGGER: MAXIMO.PMFORECASTSERVICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMFORECASTSERVICE_T" BEFORE INSERT OR UPDATE ON PMFORECASTSERVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMFORECASTSERVICE_T" ENABLE
