-- TRIGGER: MAXIMO.PMIMODELINFO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMIMODELINFO_T" BEFORE INSERT OR UPDATE ON PMIMODELINFO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."PMIMODELINFO_T" ENABLE
