-- TRIGGER: MAXIMO.PMMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMMETER_T" BEFORE INSERT OR UPDATE ON PMMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMMETER_T" ENABLE
