-- TRIGGER: MAXIMO.PMSEASONS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMSEASONS_T" BEFORE INSERT OR UPDATE ON PMSEASONS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMSEASONS_T" ENABLE
