-- TRIGGER: MAXIMO.PMSEQUENCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PMSEQUENCE_T" BEFORE INSERT OR UPDATE ON PMSEQUENCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PMSEQUENCE_T" ENABLE
