-- TRIGGER: MAXIMO.PO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PO_T" BEFORE INSERT OR UPDATE ON PO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PO_T" ENABLE
