-- TRIGGER: MAXIMO.POCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."POCOST_T" BEFORE INSERT OR UPDATE ON POCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."POCOST_T" ENABLE
