-- TRIGGER: MAXIMO.POINTWO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."POINTWO_T" BEFORE INSERT OR UPDATE ON POINTWO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."POINTWO_T" ENABLE
