-- TRIGGER: MAXIMO.POLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."POLINE_T" BEFORE INSERT OR UPDATE ON POLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."POLINE_T" ENABLE
