-- TRIGGER: MAXIMO.PORTLETDISPLAY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PORTLETDISPLAY_T" BEFORE INSERT OR UPDATE ON PORTLETDISPLAY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PORTLETDISPLAY_T" ENABLE
