-- TRIGGER: MAXIMO.PORTLET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PORTLET_T" BEFORE INSERT OR UPDATE ON PORTLET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PORTLET_T" ENABLE
