-- TRIGGER: MAXIMO.POSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."POSTATUS_T" BEFORE INSERT OR UPDATE ON POSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."POSTATUS_T" ENABLE
