-- TRIGGER: MAXIMO.POTERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."POTERM_T" BEFORE INSERT OR UPDATE ON POTERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."POTERM_T" ENABLE
