-- TRIGGER: MAXIMO.PPCRAFTRATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PPCRAFTRATE_T" BEFORE INSERT OR UPDATE ON PPCRAFTRATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PPCRAFTRATE_T" ENABLE
