-- TRIGGER: MAXIMO.PPLABORRATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PPLABORRATE_T" BEFORE INSERT OR UPDATE ON PPLABORRATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PPLABORRATE_T" ENABLE
