-- TRIGGER: MAXIMO.PR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PR_T" BEFORE INSERT OR UPDATE ON PR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PR_T" ENABLE
