-- TRIGGER: MAXIMO.PRCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PRCOST_T" BEFORE INSERT OR UPDATE ON PRCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PRCOST_T" ENABLE
