-- TRIGGER: MAXIMO.PREMIUMPAY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PREMIUMPAY_T" BEFORE INSERT OR UPDATE ON PREMIUMPAY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PREMIUMPAY_T" ENABLE
