-- TRIGGER: MAXIMO.PRICALC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PRICALC_T" BEFORE INSERT OR UPDATE ON PRICALC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PRICALC_T" ENABLE
