-- TRIGGER: MAXIMO.PRLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PRLINE_T" BEFORE INSERT OR UPDATE ON PRLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PRLINE_T" ENABLE
