-- TRIGGER: MAXIMO.PRODUCTUPDATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PRODUCTUPDATE_T" BEFORE INSERT OR UPDATE ON PRODUCTUPDATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PRODUCTUPDATE_T" ENABLE
