-- TRIGGER: MAXIMO.PROPERTYDEFAULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PROPERTYDEFAULT_T" BEFORE INSERT OR UPDATE ON PROPERTYDEFAULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PROPERTYDEFAULT_T" ENABLE
