-- TRIGGER: MAXIMO.PROPERTYASSOC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PROPERTYASSOC_T" BEFORE INSERT OR UPDATE ON PROPERTYASSOC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PROPERTYASSOC_T" ENABLE
