-- TRIGGER: MAXIMO.PRSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PRSTATUS_T" BEFORE INSERT OR UPDATE ON PRSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PRSTATUS_T" ENABLE
