-- TRIGGER: MAXIMO.PRTERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."PRTERM_T" BEFORE INSERT OR UPDATE ON PRTERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."PRTERM_T" ENABLE
