-- TRIGGER: MAXIMO.QUALIFICATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUALIFICATION_T" BEFORE INSERT OR UPDATE ON QUALIFICATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."QUALIFICATION_T" ENABLE
