-- TRIGGER: MAXIMO.QUALCRAFTSKILL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUALCRAFTSKILL_T" BEFORE INSERT OR UPDATE ON QUALCRAFTSKILL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."QUALCRAFTSKILL_T" ENABLE
