-- TRIGGER: MAXIMO.QUALSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUALSTATUS_T" BEFORE INSERT OR UPDATE ON QUALSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."QUALSTATUS_T" ENABLE
