-- TRIGGER: MAXIMO.QUERYTEMPLATEATTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUERYTEMPLATEATTR_T" BEFORE INSERT OR UPDATE ON QUERYTEMPLATEATTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."QUERYTEMPLATEATTR_T" ENABLE
