-- TRIGGER: MAXIMO.QUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUERY_T" BEFORE INSERT OR UPDATE ON QUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."QUERY_T" ENABLE
