-- TRIGGER: MAXIMO.QUERYRECORDSTATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUERYRECORDSTATE_T" BEFORE INSERT OR UPDATE ON QUERYRECORDSTATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."QUERYRECORDSTATE_T" ENABLE
