-- TRIGGER: MAXIMO.QUERYTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUERYTEMPLATE_T" BEFORE INSERT OR UPDATE ON QUERYTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."QUERYTEMPLATE_T" ENABLE
