-- TRIGGER: MAXIMO.QUOTATIONLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."QUOTATIONLINE_T" BEFORE INSERT OR UPDATE ON QUOTATIONLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."QUOTATIONLINE_T" ENABLE
