-- TRIGGER: MAXIMO.RECONTASKFILTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONTASKFILTER_T" BEFORE INSERT OR UPDATE ON RECONTASKFILTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONTASKFILTER_T" ENABLE
