-- TRIGGER: MAXIMO.RECONRULECLAUSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONRULECLAUSE_T" BEFORE INSERT OR UPDATE ON RECONRULECLAUSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONRULECLAUSE_T" ENABLE
