-- TRIGGER: MAXIMO.RECONCOMPFILTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONCOMPFILTER_T" BEFORE INSERT OR UPDATE ON RECONCOMPFILTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONCOMPFILTER_T" ENABLE
