-- TRIGGER: MAXIMO.RECONRULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONRULE_T" BEFORE INSERT OR UPDATE ON RECONRULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONRULE_T" ENABLE
