-- TRIGGER: MAXIMO.RECORDTIMEZONE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECORDTIMEZONE_T" BEFORE INSERT OR UPDATE ON RECORDTIMEZONE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECORDTIMEZONE_T" ENABLE
