-- TRIGGER: MAXIMO.RECONLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONLINK_T" BEFORE INSERT OR UPDATE ON RECONLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONLINK_T" ENABLE
