-- TRIGGER: MAXIMO.RECONTASKLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONTASKLINK_T" BEFORE INSERT OR UPDATE ON RECONTASKLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONTASKLINK_T" ENABLE
