-- TRIGGER: MAXIMO.RECONTASKCOMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONTASKCOMP_T" BEFORE INSERT OR UPDATE ON RECONTASKCOMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONTASKCOMP_T" ENABLE
