-- TRIGGER: MAXIMO.RECONMULTILINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONMULTILINK_T" BEFORE INSERT OR UPDATE ON RECONMULTILINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONMULTILINK_T" ENABLE
