-- TRIGGER: MAXIMO.RECONRESULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RECONRESULT_T" BEFORE INSERT OR UPDATE ON RECONRESULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RECONRESULT_T" ENABLE
