-- TRIGGER: MAXIMO.RELATEDRECORD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATEDRECORD_T" BEFORE INSERT OR UPDATE ON RELATEDRECORD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RELATEDRECORD_T" ENABLE
