-- TRIGGER: MAXIMO.RELATIONRULESEXT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATIONRULESEXT_T" BEFORE INSERT OR UPDATE ON RELATIONRULESEXT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RELATIONRULESEXT_T" ENABLE
