-- TRIGGER: MAXIMO.RELATEDAPPAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATEDAPPAUTH_T" BEFORE INSERT OR UPDATE ON RELATEDAPPAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."RELATEDAPPAUTH_T" ENABLE
