-- TRIGGER: MAXIMO.RELATEDWORKCENTER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATEDWORKCENTER_T" BEFORE INSERT OR UPDATE ON RELATEDWORKCENTER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."RELATEDWORKCENTER_T" ENABLE
