-- TRIGGER: MAXIMO.RELATIONRULES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATIONRULES_T" BEFORE INSERT OR UPDATE ON RELATIONRULES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RELATIONRULES_T" ENABLE
