-- TRIGGER: MAXIMO.RELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATION_T" BEFORE INSERT OR UPDATE ON RELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RELATION_T" ENABLE
