-- TRIGGER: MAXIMO.RELATEDSLA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RELATEDSLA_T" BEFORE INSERT OR UPDATE ON RELATEDSLA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RELATEDSLA_T" ENABLE
