-- TRIGGER: MAXIMO.REORDERMUTEX_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REORDERMUTEX_T" BEFORE INSERT OR UPDATE ON REORDERMUTEX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REORDERMUTEX_T" ENABLE
