-- TRIGGER: MAXIMO.REORDERPAD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REORDERPAD_T" BEFORE INSERT OR UPDATE ON REORDERPAD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REORDERPAD_T" ENABLE
