-- TRIGGER: MAXIMO.REPFACAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPFACAUTH_T" BEFORE INSERT OR UPDATE ON REPFACAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPFACAUTH_T" ENABLE
