-- TRIGGER: MAXIMO.REPORTATTACHUNCPA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTATTACHUNCPA_T" BEFORE INSERT OR UPDATE ON REPORTATTACHUNCPATH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."REPORTATTACHUNCPA_T" ENABLE
