-- TRIGGER: MAXIMO.REPORTRUNLOCK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTRUNLOCK_T" BEFORE INSERT OR UPDATE ON REPORTRUNLOCK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTRUNLOCK_T" ENABLE
