-- TRIGGER: MAXIMO.REPORTSCHED_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTSCHED_T" BEFORE INSERT OR UPDATE ON REPORTSCHED FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTSCHED_T" ENABLE
