-- TRIGGER: MAXIMO.REPORTHYPERLINKQU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTHYPERLINKQU_T" BEFORE INSERT OR UPDATE ON REPORTHYPERLINKQUERYURL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTHYPERLINKQU_T" ENABLE
