-- TRIGGER: MAXIMO.REPORTADHOC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTADHOC_T" BEFORE INSERT OR UPDATE ON REPORTADHOC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTADHOC_T" ENABLE
