-- TRIGGER: MAXIMO.REPORT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORT_T" BEFORE INSERT OR UPDATE ON REPORT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORT_T" ENABLE
