-- TRIGGER: MAXIMO.REPORTATTACHDOCS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTATTACHDOCS_T" BEFORE INSERT OR UPDATE ON REPORTATTACHDOCS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTATTACHDOCS_T" ENABLE
