-- TRIGGER: MAXIMO.REPORTBROSDPURL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTBROSDPURL_T" BEFORE INSERT OR UPDATE ON REPORTBROSDPURL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTBROSDPURL_T" ENABLE
