-- TRIGGER: MAXIMO.REPORTDISPFMT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTDISPFMT_T" BEFORE INSERT OR UPDATE ON REPORTDISPFMT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."REPORTDISPFMT_T" ENABLE
