-- TRIGGER: MAXIMO.REPORTLABEL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTLABEL_T" BEFORE INSERT OR UPDATE ON REPORTLABEL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTLABEL_T" ENABLE
