-- TRIGGER: MAXIMO.REPORTSECATTKEY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTSECATTKEY_T" BEFORE INSERT OR UPDATE ON REPORTSECATTKEY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTSECATTKEY_T" ENABLE
