-- TRIGGER: MAXIMO.REPORTJOB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTJOB_T" BEFORE INSERT OR UPDATE ON REPORTJOB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTJOB_T" ENABLE
