-- TRIGGER: MAXIMO.REPORTBROS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTBROS_T" BEFORE INSERT OR UPDATE ON REPORTBROS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTBROS_T" ENABLE
