-- TRIGGER: MAXIMO.REPORTWHERE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTWHERE_T" BEFORE INSERT OR UPDATE ON REPORTWHERE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."REPORTWHERE_T" ENABLE
