-- TRIGGER: MAXIMO.REPORTLISTCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTLISTCFG_T" BEFORE INSERT OR UPDATE ON REPORTLISTCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTLISTCFG_T" ENABLE
