-- TRIGGER: MAXIMO.REPORTAPPAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTAPPAUTH_T" BEFORE INSERT OR UPDATE ON REPORTAPPAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTAPPAUTH_T" ENABLE
