-- TRIGGER: MAXIMO.REPORTOUTPUTAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTOUTPUTAUTH_T" BEFORE INSERT OR UPDATE ON REPORTOUTPUTAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTOUTPUTAUTH_T" ENABLE
