-- TRIGGER: MAXIMO.REPORTEXPVALUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTEXPVALUE_T" BEFORE INSERT OR UPDATE ON REPORTEXPVALUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTEXPVALUE_T" ENABLE
