-- TRIGGER: MAXIMO.REPORTADHOCSUM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTADHOCSUM_T" BEFORE INSERT OR UPDATE ON REPORTADHOCSUM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTADHOCSUM_T" ENABLE
