-- TRIGGER: MAXIMO.REPORTPROCSCHED_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTPROCSCHED_T" BEFORE INSERT OR UPDATE ON REPORTPROCSCHED FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTPROCSCHED_T" ENABLE
