-- TRIGGER: MAXIMO.REPORTEMAILFILE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTEMAILFILE_T" BEFORE INSERT OR UPDATE ON REPORTEMAILFILE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."REPORTEMAILFILE_T" ENABLE
