-- TRIGGER: MAXIMO.REPORTUSAGELOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTUSAGELOG_T" BEFORE INSERT OR UPDATE ON REPORTUSAGELOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTUSAGELOG_T" ENABLE
