-- TRIGGER: MAXIMO.REPORTADHOCCALC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTADHOCCALC_T" BEFORE INSERT OR UPDATE ON REPORTADHOCCALC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTADHOCCALC_T" ENABLE
