-- TRIGGER: MAXIMO.REPORTBROSPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTBROSPARAM_T" BEFORE INSERT OR UPDATE ON REPORTBROSPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTBROSPARAM_T" ENABLE
