-- TRIGGER: MAXIMO.REPORTDEPEND_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTDEPEND_T" BEFORE INSERT OR UPDATE ON REPORTDEPEND FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTDEPEND_T" ENABLE
