-- TRIGGER: MAXIMO.REPORTRUNPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTRUNPARAM_T" BEFORE INSERT OR UPDATE ON REPORTRUNPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTRUNPARAM_T" ENABLE
