-- TRIGGER: MAXIMO.REPORTOUTPUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTOUTPUT_T" BEFORE INSERT OR UPDATE ON REPORTOUTPUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTOUTPUT_T" ENABLE
