-- TRIGGER: MAXIMO.REPORTADHOCFIELD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTADHOCFIELD_T" BEFORE INSERT OR UPDATE ON REPORTADHOCFIELD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTADHOCFIELD_T" ENABLE
