-- TRIGGER: MAXIMO.REPORTPROCRESERVE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTPROCRESERVE_T" BEFORE INSERT OR UPDATE ON REPORTPROCRESERVE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTPROCRESERVE_T" ENABLE
