-- TRIGGER: MAXIMO.REPORTDSPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTDSPARAM_T" BEFORE INSERT OR UPDATE ON REPORTDSPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTDSPARAM_T" ENABLE
