-- TRIGGER: MAXIMO.REPORTFILEEXPORT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTFILEEXPORT_T" BEFORE INSERT OR UPDATE ON REPORTFILEEXPORT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTFILEEXPORT_T" ENABLE
