-- TRIGGER: MAXIMO.REPORTDESIGN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTDESIGN_T" BEFORE INSERT OR UPDATE ON REPORTDESIGN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTDESIGN_T" ENABLE
