-- TRIGGER: MAXIMO.REPORTAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTAUTH_T" BEFORE INSERT OR UPDATE ON REPORTAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTAUTH_T" ENABLE
