-- TRIGGER: MAXIMO.REPORTOSAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTOSAUTH_T" BEFORE INSERT OR UPDATE ON REPORTOSAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTOSAUTH_T" ENABLE
