-- TRIGGER: MAXIMO.REPORTOUTPUTCNT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTOUTPUTCNT_T" BEFORE INSERT OR UPDATE ON REPORTOUTPUTCNT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTOUTPUTCNT_T" ENABLE
