-- TRIGGER: MAXIMO.REPORTRUNQUEUE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTRUNQUEUE_T" BEFORE INSERT OR UPDATE ON REPORTRUNQUEUE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTRUNQUEUE_T" ENABLE
