-- TRIGGER: MAXIMO.REPORTPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTPARAM_T" BEFORE INSERT OR UPDATE ON REPORTPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTPARAM_T" ENABLE
