-- TRIGGER: MAXIMO.REPORTDS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REPORTDS_T" BEFORE INSERT OR UPDATE ON REPORTDS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."REPORTDS_T" ENABLE
