-- TRIGGER: MAXIMO.REQUESTLOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."REQUESTLOG_T" BEFORE INSERT OR UPDATE ON REQUESTLOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."REQUESTLOG_T" ENABLE
