-- TRIGGER: MAXIMO.RESOURCEBYLEVEL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RESOURCEBYLEVEL_T" BEFORE INSERT OR UPDATE ON RESOURCEBYLEVEL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."RESOURCEBYLEVEL_T" ENABLE
