-- TRIGGER: MAXIMO.RESOURCELEVELS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RESOURCELEVELS_T" BEFORE INSERT OR UPDATE ON RESOURCELEVELS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."RESOURCELEVELS_T" ENABLE
