-- TRIGGER: MAXIMO.RESTSYSACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RESTSYSACTION_T" BEFORE INSERT OR UPDATE ON RESTSYSACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."RESTSYSACTION_T" ENABLE
