-- TRIGGER: MAXIMO.RESULTSETCOLS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RESULTSETCOLS_T" BEFORE INSERT OR UPDATE ON RESULTSETCOLS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RESULTSETCOLS_T" ENABLE
