-- TRIGGER: MAXIMO.RFQ_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RFQ_T" BEFORE INSERT OR UPDATE ON RFQ FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RFQ_T" ENABLE
