-- TRIGGER: MAXIMO.RFQLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RFQLINE_T" BEFORE INSERT OR UPDATE ON RFQLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RFQLINE_T" ENABLE
