-- TRIGGER: MAXIMO.RFQSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RFQSTATUS_T" BEFORE INSERT OR UPDATE ON RFQSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RFQSTATUS_T" ENABLE
