-- TRIGGER: MAXIMO.RFQTERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RFQTERM_T" BEFORE INSERT OR UPDATE ON RFQTERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RFQTERM_T" ENABLE
