-- TRIGGER: MAXIMO.RFQVENDOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RFQVENDOR_T" BEFORE INSERT OR UPDATE ON RFQVENDOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RFQVENDOR_T" ENABLE
