-- TRIGGER: MAXIMO.RFQVENDORTERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."RFQVENDORTERM_T" BEFORE INSERT OR UPDATE ON RFQVENDORTERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."RFQVENDORTERM_T" ENABLE
