-- TRIGGER: MAXIMO.ROUTES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ROUTES_T" BEFORE INSERT OR UPDATE ON ROUTES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ROUTES_T" ENABLE
