-- TRIGGER: MAXIMO.ROUTE_STOP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."ROUTE_STOP_T" BEFORE INSERT OR UPDATE ON ROUTE_STOP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."ROUTE_STOP_T" ENABLE
