-- TRIGGER: MAXIMO.SAFETYLEXICON_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SAFETYLEXICON_T" BEFORE INSERT OR UPDATE ON SAFETYLEXICON FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SAFETYLEXICON_T" ENABLE
