-- TRIGGER: MAXIMO.SAFETYPLAN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SAFETYPLAN_T" BEFORE INSERT OR UPDATE ON SAFETYPLAN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SAFETYPLAN_T" ENABLE
