-- TRIGGER: MAXIMO.SCCONFIG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SCCONFIG_T" BEFORE INSERT OR UPDATE ON SCCONFIG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SCCONFIG_T" ENABLE
