-- TRIGGER: MAXIMO.SCHEDULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SCHEDULE_T" BEFORE INSERT OR UPDATE ON SCHEDULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SCHEDULE_T" ENABLE
