-- TRIGGER: MAXIMO.SCHEDULELINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SCHEDULELINE_T" BEFORE INSERT OR UPDATE ON SCHEDULELINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SCHEDULELINE_T" ENABLE
