-- TRIGGER: MAXIMO.SCHTOOLTIP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SCHTOOLTIP_T" BEFORE INSERT OR UPDATE ON SCHTOOLTIP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SCHTOOLTIP_T" ENABLE
