-- TRIGGER: MAXIMO.SCRIPTLAUNCHPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SCRIPTLAUNCHPOINT_T" BEFORE INSERT OR UPDATE ON SCRIPTLAUNCHPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SCRIPTLAUNCHPOINT_T" ENABLE
