-- TRIGGER: MAXIMO.SCTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SCTEMPLATE_T" BEFORE INSERT OR UPDATE ON SCTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SCTEMPLATE_T" ENABLE
