-- TRIGGER: MAXIMO.SERVERSESSION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SERVERSESSION_T" BEFORE INSERT OR UPDATE ON SERVERSESSION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SERVERSESSION_T" ENABLE
