-- TRIGGER: MAXIMO.SETS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SETS_T" BEFORE INSERT OR UPDATE ON SETS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SETS_T" ENABLE
