-- TRIGGER: MAXIMO.SHIFT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SHIFT_T" BEFORE INSERT OR UPDATE ON SHIFT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SHIFT_T" ENABLE
