-- TRIGGER: MAXIMO.SHIPMENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SHIPMENT_T" BEFORE INSERT OR UPDATE ON SHIPMENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SHIPMENT_T" ENABLE
