-- TRIGGER: MAXIMO.SHIPMENTLINE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SHIPMENTLINE_T" BEFORE INSERT OR UPDATE ON SHIPMENTLINE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SHIPMENTLINE_T" ENABLE
