-- TRIGGER: MAXIMO.SIGOPTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SIGOPTION_T" BEFORE INSERT OR UPDATE ON SIGOPTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SIGOPTION_T" ENABLE
