-- TRIGGER: MAXIMO.SITE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SITE_T" BEFORE INSERT OR UPDATE ON SITE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SITE_T" ENABLE
