-- TRIGGER: MAXIMO.SITEAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SITEAUTH_T" BEFORE INSERT OR UPDATE ON SITEAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SITEAUTH_T" ENABLE
