-- TRIGGER: MAXIMO.SKDACTIVITYQBE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDACTIVITYQBE_T" BEFORE INSERT OR UPDATE ON SKDACTIVITYQBE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDACTIVITYQBE_T" ENABLE
