-- TRIGGER: MAXIMO.SKDACTIVITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDACTIVITY_T" BEFORE INSERT OR UPDATE ON SKDACTIVITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDACTIVITY_T" ENABLE
