-- TRIGGER: MAXIMO.SKDACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDACTION_T" BEFORE INSERT OR UPDATE ON SKDACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDACTION_T" ENABLE
