-- TRIGGER: MAXIMO.SKDAPPLETEXT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDAPPLETEXT_T" BEFORE INSERT OR UPDATE ON SKDAPPLETEXT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDAPPLETEXT_T" ENABLE
