-- TRIGGER: MAXIMO.SKDASSETLOCQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDASSETLOCQUERY_T" BEFORE INSERT OR UPDATE ON SKDASSETLOCQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDASSETLOCQUERY_T" ENABLE
