-- TRIGGER: MAXIMO.SKDCOMPLIANCEWOLI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDCOMPLIANCEWOLI_T" BEFORE INSERT OR UPDATE ON SKDCOMPLIANCEWOLIST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDCOMPLIANCEWOLI_T" ENABLE
