-- TRIGGER: MAXIMO.SKDCOMPLIANCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDCOMPLIANCE_T" BEFORE INSERT OR UPDATE ON SKDCOMPLIANCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDCOMPLIANCE_T" ENABLE
