-- TRIGGER: MAXIMO.SKDCONSTRAINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDCONSTRAINT_T" BEFORE INSERT OR UPDATE ON SKDCONSTRAINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDCONSTRAINT_T" ENABLE
