-- TRIGGER: MAXIMO.SKDCAPACITYPLANPA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDCAPACITYPLANPA_T" BEFORE INSERT OR UPDATE ON SKDCAPACITYPLANPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDCAPACITYPLANPA_T" ENABLE
