-- TRIGGER: MAXIMO.SKDCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDCOST_T" BEFORE INSERT OR UPDATE ON SKDCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDCOST_T" ENABLE
