-- TRIGGER: MAXIMO.SKDDATAVALRESULT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDDATAVALRESULT_T" BEFORE INSERT OR UPDATE ON SKDDATAVALRESULT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDDATAVALRESULT_T" ENABLE
