-- TRIGGER: MAXIMO.SKDDATAVALMSG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDDATAVALMSG_T" BEFORE INSERT OR UPDATE ON SKDDATAVALMSG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDDATAVALMSG_T" ENABLE
