-- TRIGGER: MAXIMO.SKDDATAGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDDATAGROUP_T" BEFORE INSERT OR UPDATE ON SKDDATAGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDDATAGROUP_T" ENABLE
