-- TRIGGER: MAXIMO.SKDEXTRACAPACITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDEXTRACAPACITY_T" BEFORE INSERT OR UPDATE ON SKDEXTRACAPACITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDEXTRACAPACITY_T" ENABLE
