-- TRIGGER: MAXIMO.SKDEMAVAILRES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDEMAVAILRES_T" BEFORE INSERT OR UPDATE ON SKDEMAVAILRES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDEMAVAILRES_T" ENABLE
