-- TRIGGER: MAXIMO.SKDGVPREF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDGVPREF_T" BEFORE INSERT OR UPDATE ON SKDGVPREF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDGVPREF_T" ENABLE
