-- TRIGGER: MAXIMO.SKDLABORMODPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDLABORMODPARAM_T" BEFORE INSERT OR UPDATE ON SKDLABORMODPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDLABORMODPARAM_T" ENABLE
