-- TRIGGER: MAXIMO.SKDLABORHRSTEMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDLABORHRSTEMP_T" BEFORE INSERT OR UPDATE ON SKDLABORHRSTEMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDLABORHRSTEMP_T" ENABLE
