-- TRIGGER: MAXIMO.SKDLABORHRS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDLABORHRS_T" BEFORE INSERT OR UPDATE ON SKDLABORHRS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDLABORHRS_T" ENABLE
