-- TRIGGER: MAXIMO.SKDOPASCPSSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOPASCPSSTATUS_T" BEFORE INSERT OR UPDATE ON SKDOPASCPSSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDOPASCPSSTATUS_T" ENABLE
