-- TRIGGER: MAXIMO.SKDORIGINDESTMATR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDORIGINDESTMATR_T" BEFORE INSERT OR UPDATE ON SKDORIGINDESTMATRIX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDORIGINDESTMATR_T" ENABLE
