-- TRIGGER: MAXIMO.SKDOPASCPSPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOPASCPSPARAM_T" BEFORE INSERT OR UPDATE ON SKDOPASCPSPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDOPASCPSPARAM_T" ENABLE
