-- TRIGGER: MAXIMO.SKDOBJECTMGR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOBJECTMGR_T" BEFORE INSERT OR UPDATE ON SKDOBJECTMGR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDOBJECTMGR_T" ENABLE
