-- TRIGGER: MAXIMO.SKDOVERRIDEAVAIL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOVERRIDEAVAIL_T" BEFORE INSERT OR UPDATE ON SKDOVERRIDEAVAIL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDOVERRIDEAVAIL_T" ENABLE
