-- TRIGGER: MAXIMO.SKDODMERUN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDODMERUN_T" BEFORE INSERT OR UPDATE ON SKDODMERUN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDODMERUN_T" ENABLE
