-- TRIGGER: MAXIMO.SKDOPTPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOPTPARAM_T" BEFORE INSERT OR UPDATE ON SKDOPTPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDOPTPARAM_T" ENABLE
