-- TRIGGER: MAXIMO.SKDODMAPP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDODMAPP_T" BEFORE INSERT OR UPDATE ON SKDODMAPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDODMAPP_T" ENABLE
