-- TRIGGER: MAXIMO.SKDOPASCPSKPI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOPASCPSKPI_T" BEFORE INSERT OR UPDATE ON SKDOPASCPSKPI FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDOPASCPSKPI_T" ENABLE
