-- TRIGGER: MAXIMO.SKDODMEMSG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDODMEMSG_T" BEFORE INSERT OR UPDATE ON SKDODMEMSG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDODMEMSG_T" ENABLE
