-- TRIGGER: MAXIMO.SKDODMEUNSCHEDULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDODMEUNSCHEDULE_T" BEFORE INSERT OR UPDATE ON SKDODMEUNSCHEDULEDTASK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDODMEUNSCHEDULE_T" ENABLE
