-- TRIGGER: MAXIMO.SKDOPASCPSCONFLIC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDOPASCPSCONFLIC_T" BEFORE INSERT OR UPDATE ON SKDOPASCPSCONFLICT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDOPASCPSCONFLIC_T" ENABLE
