-- TRIGGER: MAXIMO.SKDODMECONFLICTME_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDODMECONFLICTME_T" BEFORE INSERT OR UPDATE ON SKDODMECONFLICTMESSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDODMECONFLICTME_T" ENABLE
