-- TRIGGER: MAXIMO.SKDODMERESOURCESU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDODMERESOURCESU_T" BEFORE INSERT OR UPDATE ON SKDODMERESOURCESUMMARY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDODMERESOURCESU_T" ENABLE
