-- TRIGGER: MAXIMO.SKDPROPERTYMAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROPERTYMAP_T" BEFORE INSERT OR UPDATE ON SKDPROPERTYMAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROPERTYMAP_T" ENABLE
