-- TRIGGER: MAXIMO.SKDPROJECTOBJ_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECTOBJ_T" BEFORE INSERT OR UPDATE ON SKDPROJECTOBJ FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECTOBJ_T" ENABLE
