-- TRIGGER: MAXIMO.SKDPROJECTASSTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECTASSTS_T" BEFORE INSERT OR UPDATE ON SKDPROJECTASSTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECTASSTS_T" ENABLE
