-- TRIGGER: MAXIMO.SKDPMFORECASTJP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPMFORECASTJP_T" BEFORE INSERT OR UPDATE ON SKDPMFORECASTJP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPMFORECASTJP_T" ENABLE
