-- TRIGGER: MAXIMO.SKDPMFORECAST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPMFORECAST_T" BEFORE INSERT OR UPDATE ON SKDPMFORECAST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPMFORECAST_T" ENABLE
