-- TRIGGER: MAXIMO.SKDPROJECTPUBLISH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECTPUBLISH_T" BEFORE INSERT OR UPDATE ON SKDPROJECTPUBLISH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECTPUBLISH_T" ENABLE
