-- TRIGGER: MAXIMO.SKDPROJECTSHIFTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECTSHIFTS_T" BEFORE INSERT OR UPDATE ON SKDPROJECTSHIFTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECTSHIFTS_T" ENABLE
