-- TRIGGER: MAXIMO.SKDPROJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECT_T" BEFORE INSERT OR UPDATE ON SKDPROJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECT_T" ENABLE
