-- TRIGGER: MAXIMO.SKDPMFOCOST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPMFOCOST_T" BEFORE INSERT OR UPDATE ON SKDPMFOCOST FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPMFOCOST_T" ENABLE
