-- TRIGGER: MAXIMO.SKDPROJECTEMWO_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECTEMWO_T" BEFORE INSERT OR UPDATE ON SKDPROJECTEMWO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECTEMWO_T" ENABLE
