-- TRIGGER: MAXIMO.SKDPROJECTSCENARI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPROJECTSCENARI_T" BEFORE INSERT OR UPDATE ON SKDPROJECTSCENARIO FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPROJECTSCENARI_T" ENABLE
