-- TRIGGER: MAXIMO.SKDPMFOCOSTTEMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDPMFOCOSTTEMP_T" BEFORE INSERT OR UPDATE ON SKDPMFOCOSTTEMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDPMFOCOSTTEMP_T" ENABLE
