-- TRIGGER: MAXIMO.SKDQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDQUERY_T" BEFORE INSERT OR UPDATE ON SKDQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDQUERY_T" ENABLE
