-- TRIGGER: MAXIMO.SKDRESOBJECT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDRESOBJECT_T" BEFORE INSERT OR UPDATE ON SKDRESOBJECT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDRESOBJECT_T" ENABLE
