-- TRIGGER: MAXIMO.SKDRESOURCEUSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDRESOURCEUSE_T" BEFORE INSERT OR UPDATE ON SKDRESOURCEUSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDRESOURCEUSE_T" ENABLE
