-- TRIGGER: MAXIMO.SKDRESOURCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDRESOURCE_T" BEFORE INSERT OR UPDATE ON SKDRESOURCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDRESOURCE_T" ENABLE
