-- TRIGGER: MAXIMO.SKDRESOURCEVIEW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDRESOURCEVIEW_T" BEFORE INSERT OR UPDATE ON SKDRESOURCEVIEW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDRESOURCEVIEW_T" ENABLE
