-- TRIGGER: MAXIMO.SKDRESLEVELPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDRESLEVELPARAM_T" BEFORE INSERT OR UPDATE ON SKDRESLEVELPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDRESLEVELPARAM_T" ENABLE
