-- TRIGGER: MAXIMO.SKDRESERVATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDRESERVATION_T" BEFORE INSERT OR UPDATE ON SKDRESERVATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDRESERVATION_T" ENABLE
