-- TRIGGER: MAXIMO.SKDSTATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDSTATE_T" BEFORE INSERT OR UPDATE ON SKDSTATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDSTATE_T" ENABLE
