-- TRIGGER: MAXIMO.SKDSCENRUNKPIDEF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDSCENRUNKPIDEF_T" BEFORE INSERT OR UPDATE ON SKDSCENRUNKPIDEF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDSCENRUNKPIDEF_T" ENABLE
