-- TRIGGER: MAXIMO.SKDSPATIALPARAM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDSPATIALPARAM_T" BEFORE INSERT OR UPDATE ON SKDSPATIALPARAM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDSPATIALPARAM_T" ENABLE
