-- TRIGGER: MAXIMO.SKDTEMPLATES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDTEMPLATES_T" BEFORE INSERT OR UPDATE ON SKDTEMPLATES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDTEMPLATES_T" ENABLE
