-- TRIGGER: MAXIMO.SKDUSAGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDUSAGE_T" BEFORE INSERT OR UPDATE ON SKDUSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDUSAGE_T" ENABLE
