-- TRIGGER: MAXIMO.SKDWORKPLANEXTCAP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDWORKPLANEXTCAP_T" BEFORE INSERT OR UPDATE ON SKDWORKPLANEXTCAP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SKDWORKPLANEXTCAP_T" ENABLE
