-- TRIGGER: MAXIMO.SKDWOBREAKINOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SKDWOBREAKINOUT_T" BEFORE INSERT OR UPDATE ON SKDWOBREAKINOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."SKDWOBREAKINOUT_T" ENABLE
