-- TRIGGER: MAXIMO.SLA_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLA_T" BEFORE INSERT OR UPDATE ON SLA FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLA_T" ENABLE
