-- TRIGGER: MAXIMO.SLAASSETLOC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLAASSETLOC_T" BEFORE INSERT OR UPDATE ON SLAASSETLOC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLAASSETLOC_T" ENABLE
