-- TRIGGER: MAXIMO.SLACOMMITMENTS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLACOMMITMENTS_T" BEFORE INSERT OR UPDATE ON SLACOMMITMENTS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLACOMMITMENTS_T" ENABLE
