-- TRIGGER: MAXIMO.SLACONTRACT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLACONTRACT_T" BEFORE INSERT OR UPDATE ON SLACONTRACT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLACONTRACT_T" ENABLE
