-- TRIGGER: MAXIMO.SLAKPI_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLAKPI_T" BEFORE INSERT OR UPDATE ON SLAKPI FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLAKPI_T" ENABLE
