-- TRIGGER: MAXIMO.SLARECORDS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLARECORDS_T" BEFORE INSERT OR UPDATE ON SLARECORDS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLARECORDS_T" ENABLE
