-- TRIGGER: MAXIMO.SLROUTE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SLROUTE_T" BEFORE INSERT OR UPDATE ON SLROUTE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SLROUTE_T" ENABLE
