-- TRIGGER: MAXIMO.SMS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SMS_T" BEFORE INSERT OR UPDATE ON SMS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SMS_T" ENABLE
