-- TRIGGER: MAXIMO.SOLUTIONSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SOLUTIONSPEC_T" BEFORE INSERT OR UPDATE ON SOLUTIONSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SOLUTIONSPEC_T" ENABLE
