-- TRIGGER: MAXIMO.SOLUTIONSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SOLUTIONSTATUS_T" BEFORE INSERT OR UPDATE ON SOLUTIONSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SOLUTIONSTATUS_T" ENABLE
