-- TRIGGER: MAXIMO.SOLUTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SOLUTION_T" BEFORE INSERT OR UPDATE ON SOLUTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SOLUTION_T" ENABLE
