-- TRIGGER: MAXIMO.SPAREPART_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SPAREPART_T" BEFORE INSERT OR UPDATE ON SPAREPART FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SPAREPART_T" ENABLE
