-- TRIGGER: MAXIMO.SPRELATEDASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SPRELATEDASSET_T" BEFORE INSERT OR UPDATE ON SPRELATEDASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SPRELATEDASSET_T" ENABLE
