-- TRIGGER: MAXIMO.SPWORKASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."SPWORKASSET_T" BEFORE INSERT OR UPDATE ON SPWORKASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."SPWORKASSET_T" ENABLE
