-- TRIGGER: MAXIMO.STOREROOMANCESTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."STOREROOMANCESTOR_T" BEFORE INSERT OR UPDATE ON STOREROOMANCESTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."STOREROOMANCESTOR_T" ENABLE
