-- TRIGGER: MAXIMO.TAGLOCK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAGLOCK_T" BEFORE INSERT OR UPDATE ON TAGLOCK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAGLOCK_T" ENABLE
