-- TRIGGER: MAXIMO.TAGOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAGOUT_T" BEFORE INSERT OR UPDATE ON TAGOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAGOUT_T" ENABLE
