-- TRIGGER: MAXIMO.TAMITDPAHWM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAMITDPAHWM_T" BEFORE INSERT OR UPDATE ON TAMITDPAHWM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAMITDPAHWM_T" ENABLE
