-- TRIGGER: MAXIMO.TAMITSWPRTNUM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAMITSWPRTNUM_T" BEFORE INSERT OR UPDATE ON TAMITSWPRTNUM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAMITSWPRTNUM_T" ENABLE
