-- TRIGGER: MAXIMO.TASKSCHEDULER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TASKSCHEDULER_T" BEFORE INSERT OR UPDATE ON TASKSCHEDULER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TASKSCHEDULER_T" ENABLE
