-- TRIGGER: MAXIMO.TAX_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAX_T" BEFORE INSERT OR UPDATE ON TAX FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAX_T" ENABLE
