-- TRIGGER: MAXIMO.TAXORDER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAXORDER_T" BEFORE INSERT OR UPDATE ON TAXORDER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAXORDER_T" ENABLE
