-- TRIGGER: MAXIMO.TAXTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TAXTYPE_T" BEFORE INSERT OR UPDATE ON TAXTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TAXTYPE_T" ENABLE
