-- TRIGGER: MAXIMO.TDTVERSION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TDTVERSION_T" BEFORE INSERT OR UPDATE ON TDTVERSION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TDTVERSION_T" ENABLE
