-- TRIGGER: MAXIMO.TEMPLATESTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TEMPLATESTATUS_T" BEFORE INSERT OR UPDATE ON TEMPLATESTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TEMPLATESTATUS_T" ENABLE
