-- TRIGGER: MAXIMO.TERM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TERM_T" BEFORE INSERT OR UPDATE ON TERM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TERM_T" ENABLE
