-- TRIGGER: MAXIMO.TICKET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TICKET_T" BEFORE INSERT OR UPDATE ON TICKET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TICKET_T" ENABLE
