-- TRIGGER: MAXIMO.TIMEZONERULE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TIMEZONERULE_T" BEFORE INSERT OR UPDATE ON TIMEZONERULE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TIMEZONERULE_T" ENABLE
