-- TRIGGER: MAXIMO.TKSERVICEADDRESS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TKSERVICEADDRESS_T" BEFORE INSERT OR UPDATE ON TKSERVICEADDRESS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TKSERVICEADDRESS_T" ENABLE
