-- TRIGGER: MAXIMO.TKSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TKSTATUS_T" BEFORE INSERT OR UPDATE ON TKSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TKSTATUS_T" ENABLE
