-- TRIGGER: MAXIMO.TKTEMPLTACTIVITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TKTEMPLTACTIVITY_T" BEFORE INSERT OR UPDATE ON TKTEMPLTACTIVITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TKTEMPLTACTIVITY_T" ENABLE
