-- TRIGGER: MAXIMO.TKTEMPLATESPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TKTEMPLATESPEC_T" BEFORE INSERT OR UPDATE ON TKTEMPLATESPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TKTEMPLATESPEC_T" ENABLE
