-- TRIGGER: MAXIMO.TKTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TKTEMPLATE_T" BEFORE INSERT OR UPDATE ON TKTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TKTEMPLATE_T" ENABLE
