-- TRIGGER: MAXIMO.TLOAMASSETGRP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMASSETGRP_T" BEFORE INSERT OR UPDATE ON TLOAMASSETGRP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMASSETGRP_T" ENABLE
