-- TRIGGER: MAXIMO.TLOAMFSNEVENTLIST_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMFSNEVENTLIST_T" BEFORE INSERT OR UPDATE ON TLOAMFSNEVENTLISTENER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMFSNEVENTLIST_T" ENABLE
