-- TRIGGER: MAXIMO.TLOAMDPAHWM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMDPAHWM_T" BEFORE INSERT OR UPDATE ON TLOAMDPAHWM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMDPAHWM_T" ENABLE
