-- TRIGGER: MAXIMO.TLOAMFSNRUNSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMFSNRUNSTATUS_T" BEFORE INSERT OR UPDATE ON TLOAMFSNRUNSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMFSNRUNSTATUS_T" ENABLE
