-- TRIGGER: MAXIMO.TLOAMSOFTWARE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMSOFTWARE_T" BEFORE INSERT OR UPDATE ON TLOAMSOFTWARE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMSOFTWARE_T" ENABLE
