-- TRIGGER: MAXIMO.TLOAMPRMDFLT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMPRMDFLT_T" BEFORE INSERT OR UPDATE ON TLOAMPRMDFLT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMPRMDFLT_T" ENABLE
