-- TRIGGER: MAXIMO.TLOAMSWREL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMSWREL_T" BEFORE INSERT OR UPDATE ON TLOAMSWREL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMSWREL_T" ENABLE
