-- TRIGGER: MAXIMO.TLOAMSWCATALOG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TLOAMSWCATALOG_T" BEFORE INSERT OR UPDATE ON TLOAMSWCATALOG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TLOAMSWCATALOG_T" ENABLE
