-- TRIGGER: MAXIMO.TOKENLICUSERNAME_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENLICUSERNAME_T" BEFORE INSERT OR UPDATE ON TOKENLICUSERNAME FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENLICUSERNAME_T" ENABLE
