-- TRIGGER: MAXIMO.TOKENRESTPROD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENRESTPROD_T" BEFORE INSERT OR UPDATE ON TOKENRESTPROD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENRESTPROD_T" ENABLE
