-- TRIGGER: MAXIMO.TOKENLICTYPESTATU_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENLICTYPESTATU_T" BEFORE INSERT OR UPDATE ON TOKENLICTYPESTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENLICTYPESTATU_T" ENABLE
