-- TRIGGER: MAXIMO.TOKENLICUSERS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENLICUSERS_T" BEFORE INSERT OR UPDATE ON TOKENLICUSERS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENLICUSERS_T" ENABLE
