-- TRIGGER: MAXIMO.TOKENLICSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENLICSTATUS_T" BEFORE INSERT OR UPDATE ON TOKENLICSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENLICSTATUS_T" ENABLE
