-- TRIGGER: MAXIMO.TOKENLICFEATURES_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENLICFEATURES_T" BEFORE INSERT OR UPDATE ON TOKENLICFEATURES FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENLICFEATURES_T" ENABLE
