-- TRIGGER: MAXIMO.TOKENLICENSE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOKENLICENSE_T" BEFORE INSERT OR UPDATE ON TOKENLICENSE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."TOKENLICENSE_T" ENABLE
