-- TRIGGER: MAXIMO.TOOLQUAL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."TOOLQUAL_T" BEFORE INSERT OR UPDATE ON TOOLQUAL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."TOOLQUAL_T" ENABLE
