-- TRIGGER: MAXIMO.USERPREF_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."USERPREF_T" BEFORE INSERT OR UPDATE ON USERPREF FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."USERPREF_T" ENABLE
