-- TRIGGER: MAXIMO.USERQUERY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."USERQUERY_T" BEFORE INSERT OR UPDATE ON USERQUERY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."USERQUERY_T" ENABLE
