-- TRIGGER: MAXIMO.USERNOTIFICATIONP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."USERNOTIFICATIONP_T" BEFORE INSERT OR UPDATE ON USERNOTIFICATIONPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."USERNOTIFICATIONP_T" ENABLE
