-- TRIGGER: MAXIMO.USERDEVICE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."USERDEVICE_T" BEFORE INSERT OR UPDATE ON USERDEVICE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."USERDEVICE_T" ENABLE
