-- TRIGGER: MAXIMO.USERPURGL_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."USERPURGL_T" BEFORE INSERT OR UPDATE ON USERPURGL FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."USERPURGL_T" ENABLE
