-- TRIGGER: MAXIMO.VIEWMANAGER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."VIEWMANAGER_T" BEFORE INSERT OR UPDATE ON VIEWMANAGER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."VIEWMANAGER_T" ENABLE
