-- TRIGGER: MAXIMO.WARRANTYASSET_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WARRANTYASSET_T" BEFORE INSERT OR UPDATE ON WARRANTYASSET FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WARRANTYASSET_T" ENABLE
