-- TRIGGER: MAXIMO.WATSONVRIMG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WATSONVRIMG_T" BEFORE INSERT OR UPDATE ON WATSONVRIMG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WATSONVRIMG_T" ENABLE
