-- TRIGGER: MAXIMO.WCRELATEDTEMPLATE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WCRELATEDTEMPLATE_T" BEFORE INSERT OR UPDATE ON WCRELATEDTEMPLATE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WCRELATEDTEMPLATE_T" ENABLE
