-- TRIGGER: MAXIMO.WCTEMPLATEAUTH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WCTEMPLATEAUTH_T" BEFORE INSERT OR UPDATE ON WCTEMPLATEAUTH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WCTEMPLATEAUTH_T" ENABLE
