-- TRIGGER: MAXIMO.WEATHERORG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERORG_T" BEFORE INSERT OR UPDATE ON WEATHERORG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERORG_T" ENABLE
