-- TRIGGER: MAXIMO.WEATHERALERTIMPAC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERALERTIMPAC_T" BEFORE INSERT OR UPDATE ON WEATHERALERTIMPACT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERALERTIMPAC_T" ENABLE
