-- TRIGGER: MAXIMO.WEATHERPRODUCT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERPRODUCT_T" BEFORE INSERT OR UPDATE ON WEATHERPRODUCT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERPRODUCT_T" ENABLE
