-- TRIGGER: MAXIMO.WEATHERUSAGE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERUSAGE_T" BEFORE INSERT OR UPDATE ON WEATHERUSAGE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERUSAGE_T" ENABLE
