-- TRIGGER: MAXIMO.WEATHERCFGATTR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERCFGATTR_T" BEFORE INSERT OR UPDATE ON WEATHERCFGATTR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERCFGATTR_T" ENABLE
