-- TRIGGER: MAXIMO.WEATHERZONE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERZONE_T" BEFORE INSERT OR UPDATE ON WEATHERZONE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERZONE_T" ENABLE
