-- TRIGGER: MAXIMO.WEATHERENDPOINT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERENDPOINT_T" BEFORE INSERT OR UPDATE ON WEATHERENDPOINT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERENDPOINT_T" ENABLE
