-- TRIGGER: MAXIMO.WEATHERGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERGROUP_T" BEFORE INSERT OR UPDATE ON WEATHERGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERGROUP_T" ENABLE
