-- TRIGGER: MAXIMO.WEATHERASSETSUB_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERASSETSUB_T" BEFORE INSERT OR UPDATE ON WEATHERASSETSUB FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERASSETSUB_T" ENABLE
