-- TRIGGER: MAXIMO.WEATHERCFG_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERCFG_T" BEFORE INSERT OR UPDATE ON WEATHERCFG FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERCFG_T" ENABLE
