-- TRIGGER: MAXIMO.WEATHERAPP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WEATHERAPP_T" BEFORE INSERT OR UPDATE ON WEATHERAPP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WEATHERAPP_T" ENABLE
