-- TRIGGER: MAXIMO.WFACTIVATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFACTIVATION_T" BEFORE INSERT OR UPDATE ON WFACTIVATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFACTIVATION_T" ENABLE
