-- TRIGGER: MAXIMO.WFACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFACTION_T" BEFORE INSERT OR UPDATE ON WFACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFACTION_T" ENABLE
