-- TRIGGER: MAXIMO.WFAPPTOOLBAR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFAPPTOOLBAR_T" BEFORE INSERT OR UPDATE ON WFAPPTOOLBAR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFAPPTOOLBAR_T" ENABLE
