-- TRIGGER: MAXIMO.WFASSIGNMENT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFASSIGNMENT_T" BEFORE INSERT OR UPDATE ON WFASSIGNMENT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFASSIGNMENT_T" ENABLE
