-- TRIGGER: MAXIMO.WFASGNGROUP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFASGNGROUP_T" BEFORE INSERT OR UPDATE ON WFASGNGROUP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFASGNGROUP_T" ENABLE
