-- TRIGGER: MAXIMO.WFCALLSTACK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFCALLSTACK_T" BEFORE INSERT OR UPDATE ON WFCALLSTACK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFCALLSTACK_T" ENABLE
