-- TRIGGER: MAXIMO.WFINPUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFINPUT_T" BEFORE INSERT OR UPDATE ON WFINPUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFINPUT_T" ENABLE
