-- TRIGGER: MAXIMO.WFINSTANCE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFINSTANCE_T" BEFORE INSERT OR UPDATE ON WFINSTANCE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFINSTANCE_T" ENABLE
