-- TRIGGER: MAXIMO.WFINTERACTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFINTERACTION_T" BEFORE INSERT OR UPDATE ON WFINTERACTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFINTERACTION_T" ENABLE
