-- TRIGGER: MAXIMO.WFNODE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFNODE_T" BEFORE INSERT OR UPDATE ON WFNODE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFNODE_T" ENABLE
