-- TRIGGER: MAXIMO.WFPROCESS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFPROCESS_T" BEFORE INSERT OR UPDATE ON WFPROCESS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFPROCESS_T" ENABLE
