-- TRIGGER: MAXIMO.WFREVISION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFREVISION_T" BEFORE INSERT OR UPDATE ON WFREVISION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFREVISION_T" ENABLE
