-- TRIGGER: MAXIMO.WFSTOP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFSTOP_T" BEFORE INSERT OR UPDATE ON WFSTOP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFSTOP_T" ENABLE
