-- TRIGGER: MAXIMO.WFSTART_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFSTART_T" BEFORE INSERT OR UPDATE ON WFSTART FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFSTART_T" ENABLE
