-- TRIGGER: MAXIMO.WFTASK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WFTASK_T" BEFORE INSERT OR UPDATE ON WFTASK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WFTASK_T" ENABLE
