-- TRIGGER: MAXIMO.WMASSIGNTMP_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WMASSIGNTMP_T" BEFORE INSERT OR UPDATE ON WMASSIGNTMP FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WMASSIGNTMP_T" ENABLE
