-- TRIGGER: MAXIMO.WMMATCH_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WMMATCH_T" BEFORE INSERT OR UPDATE ON WMMATCH FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WMMATCH_T" ENABLE
