-- TRIGGER: MAXIMO.WMMATCHCRW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WMMATCHCRW_T" BEFORE INSERT OR UPDATE ON WMMATCHCRW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WMMATCHCRW_T" ENABLE
