-- TRIGGER: MAXIMO.WOANCESTOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOANCESTOR_T" BEFORE INSERT OR UPDATE ON WOANCESTOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOANCESTOR_T" ENABLE
