-- TRIGGER: MAXIMO.WOCONTRACT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOCONTRACT_T" BEFORE INSERT OR UPDATE ON WOCONTRACT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOCONTRACT_T" ENABLE
