-- TRIGGER: MAXIMO.WOGEN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOGEN_T" BEFORE INSERT OR UPDATE ON WOGEN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOGEN_T" ENABLE
