-- TRIGGER: MAXIMO.WOHAZARD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOHAZARD_T" BEFORE INSERT OR UPDATE ON WOHAZARD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOHAZARD_T" ENABLE
