-- TRIGGER: MAXIMO.WOHAZARDPREC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOHAZARDPREC_T" BEFORE INSERT OR UPDATE ON WOHAZARDPREC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOHAZARDPREC_T" ENABLE
