-- TRIGGER: MAXIMO.WOLOCKOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOLOCKOUT_T" BEFORE INSERT OR UPDATE ON WOLOCKOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOLOCKOUT_T" ENABLE
