-- TRIGGER: MAXIMO.WOMATSTATUSSYNC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOMATSTATUSSYNC_T" BEFORE INSERT OR UPDATE ON WOMATSTATUSSYNC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOMATSTATUSSYNC_T" ENABLE
