-- TRIGGER: MAXIMO.WOMETER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOMETER_T" BEFORE INSERT OR UPDATE ON WOMETER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOMETER_T" ENABLE
