-- TRIGGER: MAXIMO.WOOWNERHISTORY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOOWNERHISTORY_T" BEFORE INSERT OR UPDATE ON WOOWNERHISTORY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOOWNERHISTORY_T" ENABLE
