-- TRIGGER: MAXIMO.WOPRECAUTION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOPRECAUTION_T" BEFORE INSERT OR UPDATE ON WOPRECAUTION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOPRECAUTION_T" ENABLE
