-- TRIGGER: MAXIMO.WORELEXT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORELEXT_T" BEFORE INSERT OR UPDATE ON WORELEXT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORELEXT_T" ENABLE
