-- TRIGGER: MAXIMO.WORKPRIORITY_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORKPRIORITY_T" BEFORE INSERT OR UPDATE ON WORKPRIORITY FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORKPRIORITY_T" ENABLE
