-- TRIGGER: MAXIMO.WORKORDERSPEC_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORKORDERSPEC_T" BEFORE INSERT OR UPDATE ON WORKORDERSPEC FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORKORDERSPEC_T" ENABLE
