-- TRIGGER: MAXIMO.WORKPERIOD_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORKPERIOD_T" BEFORE INSERT OR UPDATE ON WORKPERIOD FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORKPERIOD_T" ENABLE
