-- TRIGGER: MAXIMO.WORKTYPE_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORKTYPE_T" BEFORE INSERT OR UPDATE ON WORKTYPE FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORKTYPE_T" ENABLE
