-- TRIGGER: MAXIMO.WORKVIEW_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORKVIEW_T" BEFORE INSERT OR UPDATE ON WORKVIEW FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORKVIEW_T" ENABLE
