-- TRIGGER: MAXIMO.WORKORDER_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WORKORDER_T" BEFORE INSERT OR UPDATE ON WORKORDER FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WORKORDER_T" ENABLE
