-- TRIGGER: MAXIMO.WOSAFETYLINK_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOSAFETYLINK_T" BEFORE INSERT OR UPDATE ON WOSAFETYLINK FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOSAFETYLINK_T" ENABLE
