-- TRIGGER: MAXIMO.WOSAFETYPLAN_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOSAFETYPLAN_T" BEFORE INSERT OR UPDATE ON WOSAFETYPLAN FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOSAFETYPLAN_T" ENABLE
