-- TRIGGER: MAXIMO.WOSTATUS_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOSTATUS_T" BEFORE INSERT OR UPDATE ON WOSTATUS FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOSTATUS_T" ENABLE
