-- TRIGGER: MAXIMO.WOTAGOUT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOTAGOUT_T" BEFORE INSERT OR UPDATE ON WOTAGOUT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOTAGOUT_T" ENABLE
