-- TRIGGER: MAXIMO.WOTASKRELATION_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOTASKRELATION_T" BEFORE INSERT OR UPDATE ON WOTASKRELATION FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WOTASKRELATION_T" ENABLE
