-- TRIGGER: MAXIMO.WOWEATHERALERT_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WOWEATHERALERT_T" BEFORE INSERT OR UPDATE ON WOWEATHERALERT FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;
ALTER TRIGGER "MAXIMO"."WOWEATHERALERT_T" ENABLE
