-- TRIGGER: MAXIMO.WPITEM_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WPITEM_T" BEFORE INSERT OR UPDATE ON WPITEM FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WPITEM_T" ENABLE
