-- TRIGGER: MAXIMO.WPLABOR_T
CREATE OR REPLACE EDITIONABLE TRIGGER "MAXIMO"."WPLABOR_T" BEFORE INSERT OR UPDATE ON WPLABOR FOR EACH ROW DECLARE NEXTVAL INTEGER; BEGIN SELECT MAXSEQ.NEXTVAL INTO NEXTVAL FROM DUAL; :NEW.ROWSTAMP := NEXTVAL; END;

ALTER TRIGGER "MAXIMO"."WPLABOR_T" ENABLE
