-- INDEX: MAXIMO.COMMODITIDES_TIDX
CREATE INDEX "MAXIMO"."COMMODITIDES_TIDX" ON "MAXIMO"."COMMODITIES" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
