-- INDEX: MAXIMO.COMPANIESNAM_TIDX
CREATE INDEX "MAXIMO"."COMPANIESNAM_TIDX" ON "MAXIMO"."COMPANIES" ("NAME") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
