-- INDEX: MAXIMO.COMPANIESFRE_TIDX
CREATE INDEX "MAXIMO"."COMPANIESFRE_TIDX" ON "MAXIMO"."COMPANIES" ("FREIGHTTERMS") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
