-- INDEX: MAXIMO.COMPMASTENAM_TIDX
CREATE INDEX "MAXIMO"."COMPMASTENAM_TIDX" ON "MAXIMO"."COMPMASTER" ("NAME") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
