-- INDEX: MAXIMO.CONTRACT_NDX3
CREATE INDEX "MAXIMO"."CONTRACT_NDX3" ON "MAXIMO"."CONTRACT" ("FREIGHTTERMS") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
