-- INDEX: MAXIMO.CONTRACTLINE_NDX2
CREATE INDEX "MAXIMO"."CONTRACTLINE_NDX2" ON "MAXIMO"."CONTRACTLINE" ("REMARK") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
