-- INDEX: MAXIMO.CONTRACT_NDX2
CREATE INDEX "MAXIMO"."CONTRACT_NDX2" ON "MAXIMO"."CONTRACT" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
