-- INDEX: MAXIMO.CRAFTDES_TIDX
CREATE INDEX "MAXIMO"."CRAFTDES_TIDX" ON "MAXIMO"."CRAFT" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
