-- INDEX: MAXIMO.CRAFTSKILL_NDX2
CREATE INDEX "MAXIMO"."CRAFTSKILL_NDX2" ON "MAXIMO"."CRAFTSKILL" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
