-- INDEX: MAXIMO.CRONTASKDEF_T1DX
CREATE INDEX "MAXIMO"."CRONTASKDEF_T1DX" ON "MAXIMO"."CRONTASKDEF" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
