-- INDEX: MAXIMO.CRONTASKINSTA_T1DX
CREATE INDEX "MAXIMO"."CRONTASKINSTA_T1DX" ON "MAXIMO"."CRONTASKINSTANCE" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
