-- INDEX: MAXIMO.CURRENCYDES_TIDX
CREATE INDEX "MAXIMO"."CURRENCYDES_TIDX" ON "MAXIMO"."CURRENCY" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
