-- INDEX: MAXIMO.DMPACKAGEDEF_T1DX
CREATE INDEX "MAXIMO"."DMPACKAGEDEF_T1DX" ON "MAXIMO"."DMPACKAGEDEF" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
