-- INDEX: MAXIMO.DOCINFODES_TIDX
CREATE INDEX "MAXIMO"."DOCINFODES_TIDX" ON "MAXIMO"."DOCINFO" ("DESCRIPTION") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('lexer global_lexer language column LANGCODE')
