-- DDL for VIEW MAXIMO.ACTIVE_ASSETS_VIEW
CREATE OR REPLACE VIEW "MAXIMO"."ACTIVE_ASSETS_VIEW" AS
SELECT 
    ASSETNUM,
    DESCRIPTION,
    LOCATION,
    STATUS,
    SITEID,
    ORGID,
    MANUFACTURER,
    PURCHASEPRICE,
    INSTALLDATE,
    STATUSDATE
FROM 
    MAXIMO.ASSET
WHERE 
    STATUS = 'OPERATING'
    AND DISABLED = 0
