-- VIEW: MAXIMO.BIMDESIGNSPEC
CREATE OR REPLACE VIEW "MAXIMO"."BIMDESIGNSPEC" AS
select 
				bimproductbase.bimproductbaseid, 
				bimproductbase.bimassettype, 
				bimproductbase.changeby, 
				bimproductbase.changedate, 
				bimproductbase.classstructureid, 
				bimproductbase.designspec, 
				bimproductbase.itemnum, 
				bimproductbase.itemsetid, 
				bimproductbase.langcode, 
				bimproductbase.modelid, 
				bimproductbase.name, 
				bimproductbase.orgid, 
				bimproductbase.productid, 
				bimproductbase.rowstamp, 
				bimproductbase.status, 
				bimproductbase.statusdate, 
				
				bimproductbase.description, 
				bimproductbase.hasld, 
				
				bimproductbase.accessibilityperformance, 
				bimproductbase.category, 
				bimproductbase.codeperformance, 
				bimproductbase.color, 
				bimproductbase.constituents, 
				bimproductbase.createdby, 
				bimproductbase.createdon, 
				bimproductbase.durationunit, 
				
				bimproductbase.expectedlife, 
				bimproductbase.features, 
				bimproductbase.finish, 
				bimproductbase.grade, 
				bimproductbase.heightunits, 
				bimproductbase.laborwarrantyduration, 
				bimproductbase.lengthunits, 
				bimproductbase.material, 
				bimproductbase.nominalheight, 
				bimproductbase.nominallength, 
				bimproductbase.nominalweight, 
				bimproductbase.nominalwidth, 
				bimproductbase.partswarrantduration, 
				bimproductbase.productsize, 
				bimproductbase.shape, 
				bimproductbase.sustainabilityperformance, 
				bimproductbase.warrantydesc, 
				bimproductbase.warrantydurationunit, 
				bimproductbase.weightunits,
				bimproductbase.widthunits,
				
				bimproductbase.eq01, 
				bimproductbase.eq02, 
				bimproductbase.eq03, 
				bimproductbase.eq4, 
				bimproductbase.eq5, 
				bimproductbase.eq6, 
				bimproductbase.eq7, 
				bimproductbase.eq8, 
				bimproductbase.eq9
			 from bimproductbase where designspec=1
