-- DDL for VIEW MAXIMO.VW_ASSETSPECHIST_NUM_MANDATORY
CREATE OR REPLACE VIEW "MAXIMO"."VW_ASSETSPECHIST_NUM_MANDATORY" AS
SELECT ASSETSPECHISTID, ASSETNUM, NUMVALUE, MANDATORY
FROM MAXIMO.ASSETSPECHIST
WHERE MANDATORY = 1 AND NUMVALUE IS NOT NULL
