-- DDL for VIEW MAXIMO.VW_ASSETSPECHIST_FEATURE_SUMMARY
CREATE OR REPLACE VIEW "MAXIMO"."VW_ASSETSPECHIST_FEATURE_SUMMARY" AS
SELECT ASSETNUM, 
       STARTASSETFEATURE, ENDASSETFEATURE, 
       STARTMEASURE, ENDMEASURE
FROM MAXIMO.ASSETSPECHIST
WHERE STARTASSETFEATURE IS NOT NULL AND ENDASSETFEATURE IS NOT NULL
