-- DDL for VIEW MAXIMO.VW_CRONTASKHIST_ERRORS
CREATE OR REPLACE VIEW "MAXIMO"."VW_CRONTASKHIST_ERRORS" AS
SELECT CRONTASKNAME, INSTANCENAME, STARTTIME, ENDTIME, RUNTIMEERROR
FROM MAXIMO.CRONTASKHISTORY
WHERE RUNTIMEERROR IS NOT NULL
