-- DDL for VIEW MAXIMO.VW_CRONTASKHIST_DURATION
CREATE OR REPLACE VIEW "MAXIMO"."VW_CRONTASKHIST_DURATION" AS
SELECT CRONTASKNAME, INSTANCENAME, STARTTIME, ENDTIME,
       ROUND((ENDTIME - STARTTIME) * 24 * 60, 2) AS RUN_MINUTES
FROM MAXIMO.CRONTASKHISTORY
WHERE ENDTIME IS NOT NULL
